### PR TITLE
Add a tutorial for the cross-validation and hyper-parameter tuning modules

### PR DESCRIPTION
**Pull request by micyril**

### CODE REVIEW

**Comment by micyril** [comment]
> I think this looks good, but I wanted to ask if you were ok if I added some details on what cross-validation and hyper-parameter tuning are after merge.
If you are asking for my permission for editing these tutorials after this PR is merged, my answer is yes, and you didn't even need to ask about it.

**Comment by rcurtin** [comment]
Oops, this one fell off my radar---I had everything ready to go last week but forgot to actually do the merge.  I merged this with some changes, but it looks like Github is not picking up the merge commit correctly or I did it wrong.  Anyway, the tutorials are merged with some changes in 8e58465.  Thanks again for writing the tutorials and let me know if you see any problems with the changes I made.

**Comment by micyril** [comment]
I think the changes you have made are very good - they make the tutorials much more comprehensive. I left some minor comments in the places where I think we can be a bit more precise.

**Comment by rcurtin** [comment]
Thanks, I appreciate the comments.  I handled all of them (except one I responded to on Github) in a6065e4.

**Pull request closed without merging**
