### PR TITLE
Update COPYRIGHT.txt

### PR DESCRIPTION
**Pull request by coatless**
Bumped Ryan's year to 2023 & added myself.

@eddelbuettel want me to add you as well?

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Sure, that would be kind. 

From a _really cursory_ check it may be 2017 - 2023 for me.  Standard open sauce (ie debian) email please.

```
edd@rob:~/git/mlpack(master)$ git ls | grep -i eddelbuettel
* ecae05f727 - (HEAD -> master, origin/master, origin/HEAD) Update RcppArmadillo header locations (8 weeks ago) <Dirk Eddelbuettel>
* | | | | | | | | | | | | | | | |   db088bd156 - Merge pull request #890 from eddelbuettel/master (6 years ago) <Ryan Curtin>
| * | | | | | | | | | | | | | | | fa2d416247 - minor documentation update (6 years ago) <Dirk Eddelbuettel>
* | | | | | | |   d7a97df7ea - Merge pull request #814 from eddelbuettel/bugfix/last_stdcout_to_destination (6 years ago) <Ryan Curtin>
| * | | | | | | | 6dd6008253 - (bugfix/last_stdcout_to_destination) switch last (!) remaining std::cout to destination (6 years ago) <Dirk Eddelbuettel>
edd@rob:~/git/mlpack(master)$ 
```

**Comment by coatless** [comment]
Added in https://github.com/mlpack/mlpack/pull/3377/commits/ed882bd12f28c827eca7b2b43718ab1d518f7f92.

I used the `@debian.org` e-mail.

**Comment by eddelbuettel** [comment]
Thanks.  All other year ranges whitespace free:  `yyyy-yyyy`.  Maybe align?

**Review by zoq — APPROVED** [review]

**Comment by coatless** [comment]
@zoq could we hold off on merging until more contributors have a chance to respond? Avoids having multiple PRs become active :)

**Comment by shrit** [comment]
please someone add me

**Pull request merged**
