### PR TITLE
Resolve calculation of accuracy

### PR DESCRIPTION
**Pull request by Yashwants19**

### CODE REVIEW

**Comment by rcurtin** [comment]
Can you add a description of what the problem is and how you're fixing it to the PR please?  :+1:

**Comment by Yashwants19** [comment]
Hi @rcurtin previously when I was enabling -p for getting prediction and also at same time -L for setting test_labels than I was getting Nan at the place of accuracy. May be because of std::move(predictions)

**Comment by Yashwants19** [comment]
Sorry Earlier I didn't provide the description.

**Comment by rcurtin** [comment]
Nice fix, thanks!  I updated `HISTORY.md` during merge in 7824ae057.

**Pull request merged**
