### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by dtimson**
A small change to return the optimization objective function value (loss) from FFN::Train. Useful so progress can be tracked dynamically, for example plotting.

Also, a minor doc correction.

### CODE REVIEW

**Comment by zoq** [comment]
Do you like to add the option to the allowed option list in https://github.com/mlpack/mlpack/blob/master/README.md as well?

**Comment by zoq** [comment]
Also, maybe we should rename the PR to avoid any confusion?

**Comment by dtimson** [comment]
OK. I've also filled out the list in build.hpp, and referred to it in the readme.

**Comment by dtimson** [comment]
Also, the values returned from Train() look good to me, thanks. Good job walragatver!

**Comment by ShikharJ** [comment]
@dtimson Thanks for the contribution!

**Pull request merged**
