### PR TITLE
refactor ccov() to avoid use of Op and Glue (for mlpack-3.0.x - lightweight version)

### PR DESCRIPTION
**Pull request by conradsnicta**
This PR is intended for the mlpack-3.x branch, targeting the next patch release (eg. mlpack 3.0.5).
It addresses issue https://github.com/mlpack/mlpack/issues/1849.
It is related to @jeffin143's PR https://github.com/mlpack/mlpack/pull/1855 which is targeting the master branch.

The present PR is less ambitious, as it removes the use of Op and Glue classes but retains use of other internal Armadillo functionality.  As such, this PR is _not_ meant to replace https://github.com/mlpack/mlpack/pull/1855. Instead, it is intended only for the next patch release in the 3.0.x series, keeping changes to the bare minimum.

@rcurtin @zoq

### CODE REVIEW

**Comment by rcurtin** [comment]
Note also the discussion of how this affects the release at the bottom of #1846.

**Comment by rcurtin** [comment]
Wait, hang on, this was the wrong PR...

**Comment by jeffin143** [comment]
> Wait, hang on, this was the wrong PR...

Wrong PR, in what Sense ?

**Comment by rcurtin** [comment]
Sorry, I should have actually just deleted the comment.  My error was that I meant to make that approval comment on #1855 but did it here instead. :+1:

**Comment by rcurtin** [comment]
Closed in favor of #1855.  @conradsnicta thanks for your help with this.

**Pull request closed without merging**
