### PR TITLE
memory job check

### PR DESCRIPTION
**Pull request by zoq**
This is just a test to check if the static analysis job works as expected.

### CODE REVIEW

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Alright, static analysis job fixed, now let's fix the memory job, which now has to use catch instead of boost test arguments.

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Alright, memory job fixed as well, let's close the test PR.

**Comment by rcurtin** [comment]
Awesome; one by one we will get the build green again. :smile:

**Comment by jeffin143** [comment]
@rcurtin @zoq seem so you didn't take Saturday leave ?

**Pull request closed without merging**
