### PR TITLE
Solve static code analysis issues

### PR DESCRIPTION
**Pull request by zoq**
The PR is mainly used to identify correct warnings, and later fix the issues.

### CODE REVIEW

**Comment by zoq** [comment]
This are the remaining Deepcode warnings, once fixed I will add the PVS-Studio and Infer warnings. @rcurtin can you go over the remaining warnings and check if they should be fixed or filtered out?

I would filter:

- http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.94330477-c012-44e0-8761-408895dc0b4e/#52
- http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.71afd45c-3931-4d73-b37d-d672dedee956/#89

and fix:

- http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.abf5a944-8cf3-459e-bd0e-cc5a1c6b1fe5/#39

not sure about:

- http://ci.mlpack.org/view/pull%20requests/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.d972621c-2271-4e6f-9e33-a2aed4ce22f8/#438

**Comment by rcurtin** [comment]
> This are the remaining Deepcode warnings, once fixed I will add the PVS-Studio and Infer warnings. @rcurtin can you go over the remaining warnings and check if they should be fixed or filtered out?
> 
> I would filter:
> 
>     * http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.94330477-c012-44e0-8761-408895dc0b4e/#52

Agreed---that should get freed later on.

>     * http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.71afd45c-3931-4d73-b37d-d672dedee956/#89

Agreed on this one too; we only call this function if the fstream is already open.

> and fix:
> 
>     * http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.abf5a944-8cf3-459e-bd0e-cc5a1c6b1fe5/#39

Hmm, up to you.  I *think* (but am not sure) that the idea was to test that, perhaps, no exception was thrown during serialization.  But it's also possible that the check became superfluous after the cereal transition.  I suppose it shouldn't hurt to remove the check entirely.

> not sure about:
> 
>     * http://ci.mlpack.org/view/pull%20requests/job/pull-requests-mlpack-static-code-analysis/8148/cppcheck/source.d972621c-2271-4e6f-9e33-a2aed4ce22f8/#438

I'd suggest:

```
if (MAX_OVERLAP > 0 && overlapBestAreaAxis / areaBestAreaAxis < MAX_OVERLAP)
```

If `MAX_OVERLAP` is `0`, the compiler should be able to detect that and optimize out that whole if statement body.

Thanks for working on this!  Very cool to get the static code analysis working better. :+1:

**Comment by zoq** [comment]
Infer check enabled.

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
Is it trying to do a unity build or something?  (I just glanced briefly at the error output.)  I don't think unity builds actually work for mlpack; or, at least, I haven't tested it in a long time.  If that is what it's doing, if you can get it to build the "usual" way, I think it might work. :smile:

**Comment by zoq** [comment]
I think it's clashing with cotire, I don't think I do something unusual here. I couldn't find a way to disable cotire, so I guess I will just remove the line from the cmake file and see if it works.

**Comment by rcurtin** [comment]
Another way could be to simply do a regex on `CMakeLists.txt` to comment out the `cotire(mlpack)` line, or alternately add something like this:

```
set_target_properties(example PROPERTIES COTIRE_ADD_UNITY_BUILD FALSE)
```

**Comment by zoq** [comment]
Right, I removed all the cotire parts from the `CMakeLists.txt`, now I have some filtering to do - http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/8193/.

**Comment by rcurtin** [comment]
Ohh, you're manually starting the builds---I just clicked the one here and saw it was still hiccuping on cotire, so I thought I might try and help out.  But it seems I am light years behind :smile:

**Comment by zoq** [comment]
Right, in this case, the build will still fail until https://github.com/mlpack/mlpack/pull/2918 is merged.

**Review by rcurtin — APPROVED** [review]
Nice fixes! :+1:

**Pull request merged**
