### PR TITLE
Scheduled workflow must run on main repository only.

### PR DESCRIPTION
**Pull request by Yashwants19**
Update CLI11 and Update catch workflow is also running on forked repositories. In this PR I have try to fix this issue.

### CODE REVIEW

**Comment by Yashwants19** [comment]
I guess auto cancel workflow never worked properly, Hence if all agree we can remove the `Cancel` job.

**Comment by zoq** [comment]
> I guess auto cancel workflow never worked properly, Hence if all agree we can remove the `Cancel` job.

Yeah, I would remove the `cancel` job.

**Review by rcurtin — APPROVED** [review]
Looks good to me!  Thanks! :+1:

**Review by zoq — APPROVED** [review]
Looks good to me as well.

**Comment by Yashwants19** [comment]
Please don't merge this. I want to test something here.

**Comment by Yashwants19** [comment]
I have checked this, This is working fine. Lets merge this. Thank You approval.

**Pull request merged**
