### PR TITLE
Update Armadillo to minimum version of 8.400.0

### PR DESCRIPTION
**Pull request by jeffin143**
@rcurtin , Did you on purpose leave arma version in CMake, if so please go ahead and close it :)

### CODE REVIEW

**Comment by jeffin143** [comment]
Travis , just timed out :)

**Comment by rcurtin** [comment]
Nice catch, thanks.  Looks like I'll have to upgrade Armadillo on some of the build systems; let me do that now...

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
There we go, got the build servers working with the right version of Armadillo.

**Comment by rcurtin** [comment]
Thanks @jeffin143! :+1:

**Pull request merged**
