### PR TITLE
move cxx11 target_compile_features call

### LINKED ISSUE #2509: Following up with a TODO in NewCXX11.cmake
In https://github.com/mlpack/mlpack/blob/master/CMake/NewCXX11.cmake it's recommended that come the far-off date of late 2016 or min cmake 3.1, that the contents of that file should be moved to the main cmakelists. Are we still interested in doing so?

### PR DESCRIPTION
**Pull request by birm**
Fixes #2509

### CODE REVIEW

**Comment by birm** [comment]
Apparently I've confused git somehow. Let me see if I can figure out why.

**Comment by rcurtin** [comment]
Thanks @birm!

**Comment by rcurtin** [comment]
Oh, wait, I will wait to merge until AppVeyor is done... :)

**Comment by zoq** [comment]
> Awesome, thanks for this quick refactoring! I think that the memory checks fail because they had no tests to run. I'll think about how to update that job configuration...

What about we just create an empty report, let's test that.

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Pull request merged**
