### PR TITLE
Add NumDescendants to hoeffding tree

### PR DESCRIPTION
**Pull request by sam0410**
issue #977

### CODE REVIEW

**Comment by sam0410** [comment]
Hi @rcurtin, can you please see if the test is fine?
Thanks

**Comment by rcurtin** [comment]
The Travis test has failed; please fix that and then I can review this.

**Comment by rcurtin** [comment]
Closing for inactivity.  Feel free to reopen if you have a chance to look into this further.

**Comment by sam0410** [comment]
Hi @rcurtin ,
I am not sure how to push the tree root into stack. I try to do
`std::stack<HoeffdingTree<>*> stack;`
`stack.push(this);` 
`invalid use of ‘this’ in non-member function`
thanks.

**Comment by rcurtin** [comment]
You've defined `NumDescendants()` as a static function; it is not a member of the `HoeffdingTree` class.

**Comment by sam0410** [comment]
Thanks ! I fixed it now.
I will open a PR now.

**Pull request closed without merging**
