### PR TITLE
Removed support for MSVC version older than 2015 fro CMake, Issue#508

### PR DESCRIPTION
**Pull request by hercky**
With this Cmake will only support Microsoft Visual Studio version 2015  !

### CODE REVIEW

**Comment by rcurtin** [comment]
Why MSVC15 instead of MSVC14?  Have you tested this?

**Comment by hercky** [comment]
From the issue it appeared as if MSVC older than 15 need to be removed. Should the check only be on MSVC flag ? 

I don't have Visual Studio so couldn't test it. Any other way of testing it ?

**Comment by rcurtin** [comment]
The error you have made is that the MSVC15 macro is not one that exists.  If you read the CMake documentation you would see that Visual Studio 2015 is represented by the MSVC14 macro:
https://cmake.org/cmake/help/v3.1/variable/MSVC14.html

I cannot accept this patch until it is tested to ensure that it doesn't break anything; so it must be tested on Windows with Visual Studio 2015 to ensure that it still works, and also on at least one earlier version of Visual Studio to ensure that the CMake configuration fails.

**Comment by hercky** [comment]
Oh, I won't be able to test it then, closing the pull request.

My bad, sorry for wasting your time !

**Comment by rcurtin** [comment]
Maybe AppVeyor might be a way to test here, but I haven't been able to look into it.  What I have learned over the years is, if you don't test it when you merge in, then you will be testing it later when someone reports a problem with it. :)

**Pull request closed without merging**
