### PR TITLE
Convolution Hotfix

### PR DESCRIPTION
**Pull request by shubham1206agra**
Correction to weight slice access

### CODE REVIEW

**Review by rcurtin — COMMENTED** [review]
Should we also make changes to `Gradient()`?

**Comment by shubham1206agra** [comment]
> Should we also make changes to `Gradient()`?

Can you look into failing test please

**Comment by rcurtin** [comment]
> > Should we also make changes to `Gradient()`?
> 
> Can you look into failing test please

I doubt that I will manage to solve the issue today or tomorrow so I would suggest that you dig in and take a look at what has changed too.  That particular test that failed is checking that the results are the same regardless of batch size.  So there is likely an invalid access somewhere, which only comes into play when the batch size is greater than 1.

**Comment by rcurtin** [comment]
It took me a long time to reproduce this, but it seems to reproduce *specifically* with Armadillo 9.800.6.  (Armadillo 9.800.4 is not affected, nor is newer versions.)  I haven't yet figured out exactly what is going on, but it probably has to do with something not being correctly initialized.  Is `WeightSize()` correct?  I am not sure... I think it should be:

```c++
  size_t WeightSize() const
  {
    return (maps * inMaps * kernelWidth * kernelHeight) + maps;
  }
```

where I've just dropped the `higherInDimensions` term there.

Anyway, I'm not 100% certain yet, but if you play around with it, that might be a place to start.  You can use `valgrind` to find if and where uninitialized memory is being used, and you should be able to track that back down to whatever the actual bug is.

**Comment by rcurtin** [comment]
Got it!  The loop that rotates the filters is wrong.  It was previously this:

```c++
  // To perform the backward pass, we need to rotate all the filters.
  arma::Cube<typename MatType::elem_type> rotatedFilters(weight.n_cols,
      weight.n_rows, weight.n_slices);
  for (size_t map = 0; map < maps; ++map)
  {
    Rotate180(weight.slice(map), rotatedFilters.slice(map));
  }
```

and you need to change the bounds of the loop:

```c++
  // To perform the backward pass, we need to rotate all the filters.
  arma::Cube<typename MatType::elem_type> rotatedFilters(weight.n_cols,
      weight.n_rows, weight.n_slices);
  for (size_t map = 0; map < (maps * inMaps); ++map)
  {
    Rotate180(weight.slice(map), rotatedFilters.slice(map));
  }
```

Now it passes valgrind without any issues, once I make that change.  I think the fact that the issue only appeared on a specific version of Armadillo has to do with how memory is initialized by default in different Armadillo versions.  (This is why I am happy we test with many different versions---it helps expose bugs!)

I do still think `WeightSize()` is wrong, but the error is not fatal: it just allocates too much memory, and then never uses it.  If you want to fix that too I would appreciate it. :)

**Review by rcurtin — APPROVED** [review]
Thanks!  The test failures seem unrelated.  Also, I checked and this does cause the `mnist_cnn` example to converge faster.

*Before*

```
Epoch 1/60
9.4583880 [====================================================================================================] 100% - ETA: 0s - loss: 9.44963
1080/1080 [====================================================================================================] 100% - 50.6889s/epoch; 46ms/step; loss: 9.45838
Validation loss: 12441.4.
Epoch 2/60
1.2956680 [====================================================================================================] 100% - ETA: 0s - loss: 1.29446
1080/1080 [====================================================================================================] 100% - 50.6542s/epoch; 46ms/step; loss: 1.29566
Validation loss: 5402.87.
Epoch 3/60
0.6787280 [====================================================================================================] 100% - ETA: 0s - loss: 0.678092
1080/1080 [====================================================================================================] 100% - 50.822s/epoch; 47ms/step; loss: 0.67872
Validation loss: 3447.2.
Epoch 4/60
0.4608880 [====================================================================================================] 100% - ETA: 0s - loss: 0.460453
1080/1080 [====================================================================================================] 100% - 50.76s/epoch; 46ms/step; loss: 0.46088
Validation loss: 2625.26.
Epoch 5/60
0.3506130 [====================================================================================================] 100% - ETA: 0s - loss: 0.350289
1080/1080 [====================================================================================================] 100% - 50.833s/epoch; 47ms/step; loss: 0.350613
Validation loss: 2064.95.
```

*After*

```
Epoch 1/60
8.4917180 [====================================================================================================] 100% - ETA: 0s - loss: 8.48386
1080/1080 [====================================================================================================] 100% - 51.6354s/epoch; 47ms/step; loss: 8.49171
Validation loss: 10344.8.
Epoch 2/60
1.1411380 [====================================================================================================] 100% - ETA: 0s - loss: 1.14007
1080/1080 [====================================================================================================] 100% - 52.8717s/epoch; 48ms/step; loss: 1.14113
Validation loss: 4464.7.
Epoch 3/60
0.5980410 [====================================================================================================] 100% - ETA: 0s - loss: 0.597488
1080/1080 [====================================================================================================] 100% - 51.775s/epoch; 47ms/step; loss: 0.598041
Validation loss: 2676.62.
Epoch 4/60
0.3828350 [====================================================================================================] 100% - ETA: 0s - loss: 0.38248
1080/1080 [====================================================================================================] 100% - 51.7212s/epoch; 47ms/step; loss: 0.382835
Validation loss: 1853.03.
Epoch 5/60
0.2701930 [====================================================================================================] 100% - ETA: 0s - loss: 0.269943
1080/1080 [====================================================================================================] 100% - 51.7557s/epoch; 47ms/step; loss: 0.270193
Validation loss: 1426.94.
```

**Comment by shubham1206agra** [comment]
@rcurtin Please merge this.

**Comment by rcurtin** [comment]
Thanks again! :rocket:

**Pull request merged**
