### PR TITLE
Test config

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
including `CTest` in the cmake file in the tests folder removes the error of not having the dartconfig file while running tests for all the builds through ctest.

### CODE REVIEW

**Review by rcurtin — APPROVED** [review]
Thanks, nice fix! :+1:

**Review by rcurtin — CHANGES_REQUESTED** [review]
Actually, I clicked approve too quickly, sorry about that!  It looks like the MacOS builds are actually timing out.  It turns out including CTest seems to set a default timeout that's way too low:

https://stackoverflow.com/questions/45009595/how-to-overwrite-ctest-default-timeout-1500-in-cmakelists-txt

I suppose we could set the timeout for mlpack_test to 0, so that there is no timeout.  Do you want to try that?

**Comment by Aakash-kaushik** [comment]
> Actually, I clicked approve too quickly, sorry about that! It looks like the MacOS builds are actually timing out. It turns out including CTest seems to set a default timeout that's way too low:
> 
> https://stackoverflow.com/questions/45009595/how-to-overwrite-ctest-default-timeout-1500-in-cmakelists-txt
> 
> I suppose we could set the timeout for mlpack_test to 0, so that there is no timeout. Do you want to try that?

Sure, I will do that.

**Comment by Aakash-kaushik** [comment]
Let's see if this works.

**Comment by Aakash-kaushik** [comment]
Should work this time.

**Review by rcurtin — APPROVED** [review]
Perfect, thank you for fixing that timeout issue! :+1:

**Comment by Aakash-kaushik** [comment]
> Perfect, thank you for fixing that timeout issue! 👍

Thanks to you for providing that solution. I did the same thing for the models repo but there wasn't any big test so i didn't face this.

**Review by Yashwants19 — APPROVED** [review]
Looks good to me. :+1:

**Pull request merged**
