### PR TITLE
Uniform interface for Softmax and Logistic Regression

### PR DESCRIPTION
**Pull request by sagarbhathwar**
Added a few overloads to Classify method is softmax regression and the tests for them, so that Softmax and Logistic regression have a uniform interface

Noticed two failed tests. Unable to verify if these are due to anything that I have changed
`load_save_test.cpp(683): fatal error: in "LoadSaveTest/LoadHDF5Test": critical check test.n_rows == 4 has failed [2 != 4]`

`nmf_test.cpp(95): fatal error: in "NMFTest/NMFRandomDivTest": absolute value of arma::norm(v - wh, "fro") / arma::norm(v, "fro"){0.071824514847599066} exceeds 0.014999999999999999`

Please verify and comment on any changes to be made

Thank you

### CODE REVIEW

**Comment by sagarbhathwar** [comment]
@rcurtin Please review

**Comment by rcurtin** [comment]
@sagarbhathwar: I received an email already when you opened the PR.  I will review it when I have time; there is no need to notify me multiple times.

**Comment by sagarbhathwar** [comment]
I used a function which was introduced only in Armadilla 7.300. I will fix it to be backward compatible. Apologies

**Comment by rcurtin** [comment]
Thanks!

**Comment by sagarbhathwar** [comment]
Thank you, Ryan! I will close the issue now

**Pull request merged**
