### PR TITLE
Remove R-bindings build from azure pipeline.

### PR DESCRIPTION
**Pull request by Yashwants19**
After the discussion with @zoq and @rcurtin on irc, I am trying to remove R-bindings build from azure deveops pipeline, and enable testing in github-actions. I have also change upload-artifact on failure of R-CMD-check from check folder to  check and install logs.

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Is it possible to rename the jobs? Maybe use a similar naming scheme as we do for azure? Or at least drop the `R CMD check mlpack` part?

**Comment by Yashwants19** [comment]
Definitely we can change the name of jobs, if you can help me with this, it will be a great help, as I am really bad at naming conventions :sweat_smile: .

**Comment by zoq** [comment]
What about:

- (Windows R)
- (macOS R)
- (Linux R)
- (mlpack R tarball)

I mainly reused what we already have.

**Review by zoq — APPROVED** [review]
Looks good to me, let's hope we don't run into any limitations.

**Review by rcurtin — APPROVED** [review]
@Yashwants19 looks good to me, but if you don't mind me asking, what's the reason to move to Github actions instead of keeping this as an Azure build?

**Comment by Yashwants19** [comment]
Only the reason to remove R-bindings from azure pipeline is because we are testing/checking R-bindings for windows, macOS and Linux on github-actions, Hence we doesn't see any reason to test it twice for macOS or Linux on azure. And the only thing that we are not doing on github-actions is that we are not building mlpack_test here, which I have also enabled. Let me know, If I am missing something here I can revert these changes. :)

**Comment by rcurtin** [comment]
Sounds good!  I'll go ahead and merge it.  If we start running into issues like 'out of minutes' or something like this, it shouldn't be hard to migrate it back to Azure if we need. :+1:

**Pull request merged**
