### PR TITLE
Fix R-bindings documentation.

### PR DESCRIPTION
**Pull request by Yashwants19**
In this PR I have tried to fix the documentation for R-bindings which doesn't require output for example: [preprocess_describe](https://www.mlpack.org/doc/mlpack-git/r_documentation.html#preprocess_describe). 

I have also tried to fix output_model(`blmodel` --> `blr_model`) which doesn't look correct, for [example](https://www.mlpack.org/doc/mlpack-git/r_documentation.html#example-2).

### CODE REVIEW

**Review by rcurtin — COMMENTED** [review]
Looks good to me, at least for the part of omitting a list of empty output options.

But does this fix the `blmodel` -> `blr_model` issue?  I also noticed that the `bayesian_linear_regression` binding is actually called `bayesian_linearegression`... maybe `StripType()` or something is not quite right?  The issue seems to be specific to the R bindings.

Also, I think that we should fix the Markdown bindings to handle an empty set of output options by not printing any table.  I think that can be done by changing the lines in `src/mlpack/bindings/markdown/print_docs.cpp` at lines 176-177 from this:

```
    cout << "| ***name*** | ***type*** | ***description*** |" << endl;
    cout << "|------------|------------|-------------------|" << endl;
```

to this:

```

    // Determine if there are any output options, to see if we need
    // to print the header of the output options table.
    bool hasOutputOptions = false;
    for (map<string, ParamData>::iterator it = parameters.begin();
        it != parameters.end(); ++it)
    {
      if (!it->second.input)
      {
        hasOutputOptions = true;
        break;
      }
    }

    if (hasOutputOptions)
    {    
      cout << "| ***name*** | ***type*** | ***description*** |" << endl;
      cout << "|------------|------------|-------------------|" << endl;
    }
```

Anyway, I think that will work.  Let me know if I overlooked something.

**Comment by Yashwants19** [comment]
> But does this fix the blmodel -> blr_model issue? I also noticed that the bayesian_linear_regression binding is actually called bayesian_linearegression... maybe StripType() or something is not quite right? The issue seems to be specific to the R bindings.

You are right it might not fix this problem, I guess we are building this perfectly(which can also seen [here](https://gist.github.com/Yashwants19/c6a34f7bf681527ab8eb5caefa1102f2#example-14)), I think so somehow our website is skipping the first occurrence of `r_`, hence should I change the languge from `r` to `r-binding` or something similar?

**Comment by rcurtin** [comment]
@Yashwants19 you're right---I think I found the place in the processing scripts where this happened, and I opened this PR: https://github.com/mlpack/mlpack.org/pull/38.  So I think we can change it back to just `r` instead of `r-binding`. :+1:

**Comment by Yashwants19** [comment]
> @Yashwants19 you're right---I think I found the place in the processing scripts where this happened, and I opened this PR: [mlpack/mlpack.org#38](https://github.com/mlpack/mlpack.org/pull/38). So I think we can change it back to just `r` instead of `r-binding`.

Awesome, Thank you for opening the PR, I have revert `r-binding` back to `r`.

**Review by rcurtin — APPROVED** [review]
Awesome, looks great! :+1:

**Comment by rcurtin** [comment]
Thanks @Yashwants19!  I rebuilt the webpage and the `bayesian_linear_regression` binding shows up with the right name now:
https://www.mlpack.org/doc/mlpack-3.4.1/r_documentation.html#example-2

**Pull request merged**
