### PR TITLE
Fix the latex ELiSH expression.

### PR DESCRIPTION
**Pull request by zoq**
I was building the website documentation and run into an issue with the latex expression.

### CODE REVIEW

**Comment by rcurtin** [comment]
Awesome!  I had been meaning to get around to figuring out what was broken but I hadn't done it.  

I was confused about why the doxygen LaTeX build wouldn't have failed when the original commit was made, but, it looks like job actually doesn't fail when there's an error:

```
! LaTeX Error: Bad math environment delimiter.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.211 \begin{eqnarray*} \begin{equation}
                                         y(x)= \begin{cases} x / (1 + e^{-x}...

? 
! Emergency stop.
 ...                                              
                                                  
l.211 \begin{eqnarray*} \begin{equation}
                                         y(x)= \begin{cases} x / (1 + e^{-x}...
```

I can look into it if you like; probably we just need to specify some option to Doxygen to make it fail on any LaTeX error.

**Comment by zoq** [comment]
> I can look into it if you like; probably we just need to specify some option to Doxygen to make it fail on any LaTeX error.

I was just planning to use http://www.doxygen.nl/manual/config.html#cfg_warn_as_error.

**Comment by zoq** [comment]
With e82643e, I'm able to build the doc without skipping the render process, there are still a bunch of warnings we should fix, but looks like @birm is looking into that here: https://github.com/mlpack/mlpack/pull/2400.

**Comment by rcurtin** [comment]
What do you think, should be rebase these changes onto #2400 and then merge when everything is fixed?  The fixes here look good to me, but I'm hesitant to merge something where the LaTeX build will fail until #2400, so to me it seems like a good idea to merge both of those at once. :)

**Comment by zoq** [comment]
Sounds reasonable, maybe @birm can cherry-pick the commits and I'll close this one after that.

**Comment by birm** [comment]
Brought into #2400 with https://github.com/mlpack/mlpack/pull/2400/commits/f3ad22b301db3830718e3014d11fbd14732abef3

**Comment by zoq** [comment]
Great, let's close this one.

**Pull request closed without merging**
