### PR TITLE
Quick Fix Julia Build Failure

### PR DESCRIPTION
**Pull request by kartikdutt18**
Hi everyone, It's an attempt to fix Build failure of Julia. This will test (https://github.com/Homebrew/homebrew-cask/pull/77272#issue-376756379).

### CODE REVIEW

**Comment by kartikdutt18** [comment]
I am pretty sure it will work with brew update , Just wanted to check if the issue is resolved. I will close once Julia build is complete.

**Comment by kartikdutt18** [comment]
Hi @zoq, I think we need to add `brew update `  in macOS-setup.yml . If you refer to this [link](https://dev.azure.com/mlpack/mlpack/_build/results?buildId=619&view=logs&j=7fdb82b0-4024-50f2-cd8f-419b00dd5cf6&t=48d602b1-1a3a-57b2-6228-666bf2ff2980&l=170). A commit made today failed in installing Julia. Also I think it would better to add update in installation so that if any checksum error occurs in future (once it is rectified in home-brew) it will be automatically fixed in mlpack. Is this okay?
Thanks.

**Comment by zoq** [comment]
Fine with me, but is `brew update --force` necessary or could we just use `brew update`.

**Comment by kartikdutt18** [comment]
I think `brew update` will work fine, I used `--force` as a commit to restart all tests. Sorry about that, I have changed it back to `brew update`.

**Pull request merged**
