### PR TITLE
Update optimizer batch support

### PR DESCRIPTION
**Pull request by Rajiv2605**
I have refractored SGDTestFunction as of now.

### CODE REVIEW

**Comment by Rajiv2605** [comment]
@zoq Which all codes need to be updated?

**Comment by zoq** [comment]
@Rajiv2605 If you like you can continue with ``LogisticRegressionFunction``.

**Comment by Rajiv2605** [comment]
@zoq I am trying to understand the code base. From where should I start?

**Comment by rcurtin** [comment]
Hi Rajiv,

Thanks for taking a look into this one.  I just wanted to say---please keep in mind that there is a lot of activity in this repository so maintainers typically won't have the time to provide in-depth guidance for each bug.  For learning the codebase, I suggest looking at http://www.mlpack.org/involved.html and http://www.mlpack.org/gsoc.html for guides on how to get started, and if elements of the codebase still don't make sense, it is probably a good idea to read up on some C++ template metaprogramming resources or machine learning resources.

I hope this is helpful! :)

**Comment by Rajiv2605** [comment]
Thanks! I'll do that:+1:

**Comment by Rajiv2605** [comment]
@zoq I don't get why we should refractor to support batch optimization when minibatch-sgd is already existant.

**Comment by zoq** [comment]
Minibatch SGD doesn't work on "real" batches, we evaluate each example and accumulate the the result later, but there are some existing function e.g. neural network which could benefit from "real" batch computation e.g. we only have to iterate over a specific matrix once. I hope this is helpful, let me know if I should clarify anything further.

**Comment by Rajiv2605** [comment]
@zoq Thanks! Currently, I am trying to understand the code-base completely. So, I am taking time to go through each method in the library... :smile:

**Comment by Rajiv2605** [comment]
@zoq My local repo got deleted and the branch in which I was pushing got deleted along with it. After that, I was unable to push changes to the branch even after re-cloning it. Hence, I am closing this pull request and creating a new one #1073.

**Comment by zoq** [comment]
Okay, no problem.

**Pull request closed without merging**
