### PR TITLE
For confidence scores for classes in naive bayes

### PR DESCRIPTION
**Pull request by sam0410**
For issue #593 
Not merge ready yet.

### CODE REVIEW

**Comment by sam0410** [comment]
Hi @rcurtin !
The PR is now merge ready. It includes all the changes in issue number #902 as well.
Thanks!

**Comment by rcurtin** [comment]
Hello @sam0410, can you please split this PR?  It is much easier to review a PR that only considers one issue instead of two.  Thanks!

**Comment by sam0410** [comment]
Hi @zoq !
Yes, I have split the PR.
Thanks!

**Comment by rcurtin** [comment]
Sorry, picky comment, but the commit history here basically just reverted the commits from the other issue.  Could you instead make a new branch and cherry-pick only the relevant commits (or force push only the correct commits to this branch)?  Otherwise it fills the history with unnecessary log messages, etc.

It might be easiest to just make a new branch and close this PR, up to you.

**Comment by sam0410** [comment]
Hi @rcurtin !
Yes, I'll close this one and make a new one

**Comment by samO410** [comment]
Hi @zoq !
I opened pull request #917 
Thanks!

**Pull request closed without merging**
