### PR TITLE
Add spectral norm layer

### PR DESCRIPTION
**Pull request by saksham189**

### CODE REVIEW

**Comment by zoq** [comment]
Interesting this is the first PR I see in mlpack that uses the Github draft feature.

**Comment by ShikharJ** [comment]
@saksham189 Could you mention what's remaining to be done here?

**Comment by saksham189** [comment]
@ShikharJ  I need to work on the `Gradient` function and add the numerical gradient test.

**Comment by rcurtin** [comment]
This code touches the ANN code, and there was recently a big refactoring of the ANN code in #2259, so be sure to merge the master branch into your branch here to make sure that nothing will fail if this PR is merged. :+1: (I'm pasting this message into all possibly relevant PRs.)

**Pull request closed without merging**
