### PR TITLE
Triplet Loss Function for Siamese Network (issue #1699)

### PR DESCRIPTION
**Pull request by Hemal-Mamtora**
There was some issue encountered in #1744. So I have created a new pull request and closed the old one. I would be working on Triplet loss function implementation from this branch and this pull request.

### CODE REVIEW

**Comment by Hemal-Mamtora** [comment]
> There was some issue encountered in #1744. So I have created a new pull request and closed the old one. I would be working on Triplet loss function implementation from this branch and this pull request.

Apologies for the inconvenience caused

**Comment by zoq** [comment]
Okay, let me know if you need any help with the build issue.

**Comment by rcurtin** [comment]
This code touches the ANN code, and there was recently a big refactoring of the ANN code in #2259, so be sure to merge the master branch into your branch here to make sure that nothing will fail if this PR is merged. :+1: (I'm pasting this message into all possibly relevant PRs.)

Also, this one hasn't been touched since last May... @Hemal-Mamtora, any interest in seeing this one through and fixing the build issues?  If not we can let it go stale and close it unless @ShikharJ wants to keep it open. :+1:

**Comment by rcurtin** [comment]
Ack, clicked the wrong button, sorry about that.

**Comment by Hemal-Mamtora** [comment]
@rcurtin , I had thought of completing this recently, but  then I saw a recent PR implementing the Same Loss Function. (This one #2208).   

@prince776, 
So, since you are doing it, I think we could close this. 
Also please take care about the #2259, since it is applicable to #2208 as well.
Lastly, could you confirm that this is the same Loss Function? 
So that I could close this PR.
Thanks.

**Comment by prince776** [comment]
Yes @Hemal-Mamtora these are the same Loss functions.

**Comment by Hemal-Mamtora** [comment]
Closing

**Pull request closed without merging**
