### PR TITLE
Use c++11 random.

### PR DESCRIPTION
**Pull request by VladimirGl**
if we use c++11 we can use std random module instead of boost random.

### CODE REVIEW

**Comment by VladimirGl** [comment]
This pull request is not finished. Need to check all tests.

**Comment by VladimirGl** [comment]
maybe this can help to solve #261

**Comment by rcurtin** [comment]
Looks good to me, but this does break AllkRANNTest/NaiveSearchExact (in `allkrann_search_test.cpp`), which actually has a comment to the effect of "if the random number generator changes, this test breaks".  Sigh...

So that test needs to be rewritten.  All of the other tests appear to be fine.  I've added that to my queue of things to do...

**Comment by rcurtin** [comment]
3eabb52 simply removes NaiveSearchExact; it wasn't a very well-written test and I didn't think it tested anything useful.  Now we can merge this.

**Comment by rcurtin** [comment]
54071ca removes references to Boost.Random.

**Pull request merged**
