### PR TITLE
Doxygen size_t workaround

### PR DESCRIPTION
**Pull request by zoq**
The recent doxygen version(s) fail to build the documentation because it reports `size_t` as an undocumented parameter. @birm already reported the issue (https://github.com/doxygen/doxygen/issues/7818). I figured it would be better to apply the workaround he suggested instead of breaking the build.

### CODE REVIEW

**Comment by zoq** [comment]
Looks like the workaround fails with older doxygen...

**Comment by rcurtin** [comment]
@zoq yeah, version 1.8.13 is what we use on mlpack.org.  If we were to upgrade that, it might break all of the processing of the Doxygen output for the website.  Should we perhaps downgrade all of the doxygen versions on the build systems to 1.8.13 and make our workaround specific to that version?

**Comment by zoq** [comment]
> @zoq yeah, version 1.8.13 is what we use on mlpack.org. If we were to upgrade that, it might break all of the processing of the Doxygen output for the website. Should we perhaps downgrade all of the doxygen versions on the build systems to 1.8.13 and make our workaround specific to that version?

Yeah, let's downgrade all build nodes to 1.8.13. Also to avoid a build failure, should we make the documentation building optional, and disable it by default? That way, we can avoid build failures if doxygen and dot is installed.

**Comment by rcurtin** [comment]
Ok, that sounds good to me; I got Doxygen 1.8.13 installed on pretzel and bigglesworth, and used `apt-mark hold doxygen` so those versions don't accidentally get upgraded.

Getting the Jenkins changes done will require https://github.com/mlpack/mlpack/pull/2730 to be merged, but it should work just fine once that's available. :+1:

**Pull request closed without merging**
