### PR TITLE
Make R bindings depend on `pkgbuild`

### PR DESCRIPTION
**Pull request by rcurtin**
If a user installs packages only through `install.packages()` in their R session, it's possible they may end up with roxygen2, but not pkgbuild---which is required in our case.   See #3079.

This PR fixes that by adding pkgbuild as a required dependency.

I also found that newer versions of R output the version strings in regular old `'`s, not those fancy directional single quotes. :)  So I adapted our scripts to work in those cases too.

### CODE REVIEW

**Comment by rcurtin** [comment]
(ping: @coatless)

**Comment by coatless** [comment]
Thanks for the ping. Looks like how `roxygen2` functions changed recently to require `pkgbuild` being present prior to generating the documentation. This is a bit odd, but understandable as the cpp toolchain for RStudio-oriented packages is evolving. 

I think adding this requirement should be fine.

**Comment by coatless** [comment]
Looking at the issue, I think the required packages are present, but the build toolchain on GitHub actions is not detecting where a few packages are:


```
-- Could NOT find R_BH (missing: R_BH) 
-- Found R_testthat: /home/runner/work/_temp/Library/testthat  
-- Could NOT find R_pkgbuild (missing: R_PKGBUILD) 
CMake Error at src/mlpack/bindings/R/CMakeLists.txt:68 (message):
  Could not Build R Bindings, Following modules are not available:

      - Rcpp
      - RcppArmadillo
      - RcppEnsmallen
      - BH
      - pkgbuild
```

**Comment by coatless** [comment]
Looks like the issue for this is coming from the `;` being inserted into some version information? 

https://github.com/mlpack/mlpack/runs/4062172389?check_suite_focus=true#step:9:153

```
-- Found R: /usr/local/bin/R (found suitable version "4.1.1", minimum required is "4.0") 
-- Found R_roxygen2: /home/runner/work/_temp/Library/roxygen2  
Error in if (a[k] > b[k]) return(1) else if (a[k] < b[k]) return(-1L) : 
  missing value where TRUE/FALSE needed
Calls: compareVersion
In addition: Warning message:
In compareVersion(";1.0.7;", "0.12.12") : NAs introduced by coercion
Execution halted
CMake Warning at CMake/FindRModule.cmake:49 (message):
  Unsuitable version of R module Rcpp (0.12.12 or greater required).
Call Stack (most recent call first):
  src/mlpack/bindings/R/CMakeLists.txt:37 (find_r_module)
```

**Comment by rcurtin** [comment]
Thanks for pointing that out @coatless---I made a change to now strip semicolons too, and everything seems to build fine. :+1:

**Comment by coatless** [comment]
@rcurtin yup. This looks good to go! 

@zoq mind 👍 ?

**Review by zoq — APPROVED** [review]
Nice!

**Review by coatless — APPROVED** [review]
Look's great! Thanks for fixing the version comparison issue.

**Comment by eddelbuettel** [comment]
I am coming to this late (congrats on getting 4.0.0 out of the door) and just wanted to (somewhat pedantically, my bad) add that `pkgbuild` is *never* a requirement. Packages that pay attention to their build setup (e.g. `data.table` but many others come to mind too) do neither use nor require it. 

That said it's all an opt-in. 

If you all are happy with `pkgbuild` and the usual tail of package that development entails, more power to you.  Peace out.

**Comment by eddelbuettel** [comment]
(It may all be related to roxygen2, of course, and just _how_ you write roxygen documentation. I still keep `roxygen2` version  6.0.1 around for what I do by myself but indeed for some package work with other I have to rely on newer `roxygen2` and it seems to pull `pkgbuild` in. Ah well. Too me this seems like madness:

```r
> db <- tools::CRAN_package_db()
> length(tools::package_dependencies("roxygen2", recursive=TRUE, db=db)[[1]])
[1] 30
> 
```

but to others it is just the way things are.  I filed a bug report when `roxygen2` started to willy nilly recompile the package for which was a filter from src/ and/or R/ to man/ but alas nothing changed.  So I keep 6.0.1 for my use. Still creates .Rd files.)

**Comment by rcurtin** [comment]
Thanks for the clarification---certainly I wouldn't have any issue with redoing our setup to not require pkgbuild, but at least to me it seems like we have something that works, so no particular need to touch it.

**Pull request merged**
