### PR TITLE
Fix AMF tutorial

### PR DESCRIPTION
**Pull request by shyama7004**
This PR improves the Alternating Matrix Factorization (AMF) tutorial by correcting typographical errors, enhancing formatting for better clarity and usability and addition of some useful links.

### CODE REVIEW

**Comment by shyama7004** [comment]
@mlpack-jenkins test this

**Comment by shyama7004** [comment]
@mlpack-jenkins test this please

**Comment by shyama7004** [comment]
@shrit can you review the changes please.

**Comment by rcurtin** [comment]
I don't see any pragmatic improvements to the tutorial here, other than changing the tone and words to make it look like it was written by an LLM.  And that is not an improvement (it is the opposite).  So I see no reason to merge.

**Comment by shyama7004** [comment]
> I don't see any pragmatic improvements to the tutorial here, other than changing the tone and words to make it look like it was written by an LLM. And that is not an improvement (it is the opposite). So I see no reason to merge.

I read the doc and tried some improvements and refined it with chat gpt. If you don't think it's necessary I will close the Pr.

**Comment by rcurtin** [comment]
I would rather spend reviewer time (which is extremely limited!  I am hesitant to even take the time to type this response) on PRs that actually fix bugs or address real issues with mlpack.  It's true that documentation can always be improved, but LLM tools should not be used to write documentation.  I don't mind simple documentation improvements that are quick to review, but reviewing this one would take a very long time.  I'll take a very simple example: ChatGPT changed `V ~ WH` to `V ≈ WH`, which is *not* the same thing.  If you want to argue for that change in specific, you would have to understand why the author originally chose the notation that they did and make a case for why that should be overruled.  And that is only the first of many issues I would have if I looked through it closely.  See also: [Chesterton's fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence)

I know it can be frustrating to make a contribution to an open source project and have it quickly turned down, but I hope that this clarifies a little bit *why* I turned it down, and why using LLMs is not really an effective strategy for contributing to complex numerical software projects.

**Comment by shyama7004** [comment]
> I would rather spend reviewer time (which is extremely limited! I am hesitant to even take the time to type this response) on PRs that actually fix bugs or address real issues with mlpack. It's true that documentation can always be improved, but LLM tools should not be used to write documentation. I don't mind simple documentation improvements that are quick to review, but reviewing this one would take a very long time. I'll take a very simple example: ChatGPT changed `V ~ WH` to `V ≈ WH`, which is _not_ the same thing. If you want to argue for that change in specific, you would have to understand why the author originally chose the notation that they did and make a case for why that should be overruled. And that is only the first of many issues I would have if I looked through it closely. See also: [Chesterton's fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence)
> 
> I know it can be frustrating to make a contribution to an open source project and have it quickly turned down, but I hope that this clarifies a little bit _why_ I turned it down, and why using LLMs is not really an effective strategy for contributing to complex numerical software projects.

 I will try to make better and more relevant PRs, thanks for the feedback.

**Pull request closed without merging**
