### PR TITLE
SGD with momentum update.

### PR DESCRIPTION
**Pull request by arunreddy**
Implemented SGD with the momentum update towards  #893.

1. Implemented based on the sgd momentum algorithm from Deep learning book (http://www.deeplearningbook.org/) - Section 8.3.2
2. Added a hyperparamter `momentum` and set the default value to 0.5.
3. Added a test case similar to other optimizer test cases.

### CODE REVIEW

**Comment by rcurtin** [comment]
There's a lot of code duplication here with the regular SGD optimizer.  I think we can reduce that by refactoring the SGD class to include a template parameter that either represents whether or not momentum should be used, or a template class that defines the momentum to be applied to each step.  Let me know what you think of that idea.

**Comment by arunreddy** [comment]
@rcurtin I completely agree that lot of code is duplicated. MomentumSGD is same as SGD with 5 new lines of code. How about adding a momentum parameter, when the `momentum=0`  it falls back to vanilla SGD.

**Comment by rcurtin** [comment]
The only problem with a parameter like that is that it will be evaluated at runtime. :)

If we make it a compile-time parameter (i.e. a template parameter), then the compiled code we get doesn't check the value of momentum at every iteration.  Since SGD is kind of an inner loop to a lot of calculations, I think it's important here to make it as fast as possible.

Now, you could use a template parameter that's a boolean, and then check the value of that inside a function, and that will be optimized away at compile-time.  That'll work for this momentum strategy, but if someone wants to implement some other variant of momentum later, it will not work there.  That's why I suggested a policy class (or template class parameter) there, but if someone wanted another variant of momentum later, they could also do the refactoring to a template class parameter at that time.

**Comment by arunreddy** [comment]
Yeah, it is going to evaluated every time. If I understand your approach right.. 

```

**Comment by arunreddy** [comment]
Yeah, it is going to evaluated every time. If I understand your approach right.. we can have something like `momentum_update` as template class parameter along with `DecomposableFunctionType`..

``` c++
template<typename DecomposableFunctionType,bool momentum_update>
class SGD
{ 
...
}
```

The object can be instantiated as:
``` c++
// No momentum update
SGD<LogisticRegressionFunction<>,false> sgd(lrf);  

// With momentum update
SGD<LogisticRegressionFunction<>,true> sgd(lrf);  
```

and in the iteration loop we will have
``` c++
    // And update the iterate.
   if(momentum_update){
      v = momentum*v - stepSize * gradient;
      iterate += v;
   }else{
      iterate -= stepSize * gradient;
   }
```
that optimizes the code in the compile time.

**Comment by arunreddy** [comment]
I get the whole point of policy class now. So can I create `MomentumPolicy` type that is passed to `SGD` and create a two classes a default `NoMomentumPolicy` with flag set to `false` and a `SimpleMomentumPolicy` with the flag set to `true` and the hyperparameter?

**Comment by arunreddy** [comment]
Can I follow something similar to https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/amf/amf.hpp?

**Comment by arunreddy** [comment]
@rcurtin: Please ignore my last two comments. 

After discussing with @zoq I have introduced a template param `UpdatePolicyType`, which defaults to EmptyUpdate (vanilla SGD). The updates with momentum can reside in MomentumUpdate. 

Here is the work in progress: https://github.com/arunreddy/mlpack/tree/sgd_momentum_policy/src/mlpack/core/optimizers/sgd

**Comment by rcurtin** [comment]
Yep, that is the basic idea that I was thinking.  Sorry that I was not able to respond yesterday.  This is nice because it allows us to make many different variants of SGD that can be dropped in place.

**Comment by arunreddy** [comment]
Thanks, working in that direction.

**Comment by rcurtin** [comment]
Closing in favor of #925.

**Pull request closed without merging**
