### PR TITLE
Documentation with sphinx+breathe+exhale

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
Req: 
```
1. Sphinx
2. exhale 
3. breathe
4. karma-sphinx-theme
```
All of these can be simply installed with pip and these are the exact component names, then go to docs and run `make html`

You are going to see that doxygen runs successfully but then it encounters a error somewhere else if this step succeeds we would only need to add a line to index.rst in `doc/sphinx/index.rst` to have a documentation which we can further tune, but for now this errors holds us back. 

Feel free to ask if anything is keeping you from reproducing this and this is no final things i just opened this PR so we can see what we want and experiment over this.

### CODE REVIEW

**Comment by shrit** [comment]
I think it is more ideal to use markdown instead of restructured text. The reason for this is that most of us use markdown in day-to-day life, and this will make importing tutorials and documentation to mlpack website simple task.

**Comment by Aakash-kaushik** [comment]
> I think it is more ideal to use Markdown instead of restructured text. The reason for this is that most of us use Markdown in day-to-day life, and this will make importing tutorials and documentation to mlpack website a simple task.

I don't think that will be a issue because we still use doxygen to produce the output from the preexisting code and at the end you get html pages which again i don't think will be a problem to deploy on the mlpack website. 

But i might not be understanding something so do let me know.

**Comment by zoq** [comment]
> You are going to see that doxygen runs successfully but then it encounters a error somewhere else if this step succeeds we would only need to add a line to index.rst in `doc/sphinx/index.rst` to have a documentation which we can further tune, but for now this errors holds us back.

Can you post the error here as well, I haven't tested the setup at this point, but there might be an easy solution for the error you see, like currently we have to build the documentation with a specific doxygen version to make it fully work.

**Comment by rcurtin** [comment]
I thought `breathe` and `exhale` was a joke because setting up Sphinx was stressful, but now I look closer and see those are actually package names! :joy: 

Awesome work @Aakash-kaushik; I'll take a look when I have a chance. :+1:

**Comment by Aakash-kaushik** [comment]
> > You are going to see that doxygen runs successfully but then it encounters a error somewhere else if this step succeeds we would only need to add a line to index.rst in `doc/sphinx/index.rst` to have a documentation which we can further tune, but for now this errors holds us back.
> 
> Can you post the error here as well, I haven't tested the setup at this point, but there might be an easy solution for the error you see, like currently we have to build the documentation with a specific doxygen version to make it fully work.

```bash
(!) Exception caught while parsing:Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/exhale/deploy.py", line 394, in explode
    textRoot.parse()
  File "/usr/local/lib/python3.9/dist-packages/exhale/graph.py", line 1061, in parse
    self.parseFunctionSignatures()
  File "/usr/local/lib/python3.9/dist-packages/exhale/graph.py", line 2002, in parseFunctionSignatures
    parameters.append(param.type.text)
AttributeError: 'NoneType' object has no attribute 'text'
```
So this isn't much of a error that we could debug this comes when exhale tries to parse the xml files generated by doxygen but as you say we use a speciifc version of it, that might be the cause i can install that and try again if i know which one it is ?

**Comment by Aakash-kaushik** [comment]
> I thought `breathe` and `exhale` was a joke because setting up Sphinx was stressful, but now I look closer and see those are actually package names! 
> 
> Awesome work @Aakash-kaushik; I'll take a look when I have a chance.

btw setting up these things were a pain because of so many components, but the biggest pain point is when you google search for any of their documentations, i don't know why but but there are complete documents on `how to breathe`. I probably was doing something wrong all my life. :laughing:

**Comment by zoq** [comment]
We currently build the docs with doxygen 1.8.13.

**Comment by zoq** [comment]
Btw. not sure you already showed this in the chat, but feel free to post an image of the documentation you already generated and showed in the call today; this was already pretty neat.

**Comment by Aakash-kaushik** [comment]
> Btw. not sure you already showed this in the chat, but feel free to post an image of the documentation you already generated and showed in the call today; this was already pretty neat.

Hey, So i was going to do this yesterday but got confused if you actually asked for it or not. 
So here is a small video showing just that. 


https://user-images.githubusercontent.com/39410692/122882202-93ca7080-d359-11eb-8d6e-95aa1cc8bac6.mp4

**Comment by Aakash-kaushik** [comment]
> > Btw. not sure you already showed this in the chat, but feel free to post an image of the documentation you already generated and showed in the call today; this was already pretty neat.
> 
> Hey, So i was going to do this yesterday but got confused if you actually asked for it or not.
> So here is a small video showing just that.
> 
>  Screencast.from.22-06-21.12_52_25.PM.IST.mp4

btw the gitter/lag is only in the video

**Comment by Aakash-kaushik** [comment]
> We currently build the docs with doxygen 1.8.13.

So i am running ubuntu 21.04 and seems like the package was dropped in bionic and also needs llvm6 so i did try just getting the deb package from launchpad but that's like a invitation to dependency hell, you install doxygen 1.18.13 try llvm6, llvm has other dependencies so i just used the repos and added them to my source.list but not much use so haven't been much successful trying to install this.

**Comment by Aakash-kaushik** [comment]
So having installed `doxygen=1.18.3` i did get past this error and encountered something that probably can be debugged but includes files and declaration that i have never seen, here is the [issue and discussion](https://github.com/sphinx-doc/sphinx/issues/9371) that i had on sphinx's github so if someone is ready to debug this, the help would be appreciated

**Comment by astrojuanlu** [comment]
> I think it is more ideal to use Markdown instead of restructured text.

I know it's yet another piece to add, but you can do this with MyST, see https://www.sphinx-doc.org/en/master/usage/markdown.html and https://myst-parser.readthedocs.io/en/latest/sphinx/intro.html

**Comment by Aakash-kaushik** [comment]
For anyone who wants to see who it might look, I was able to set it up for the models repo, so have a look here: https://github.com/mlpack/models/pull/64

**Comment by rcurtin** [comment]
Really cool to see this effort.  When I tried to build locally, I also got the error `AttributeError: 'NoneType' object has no attribute 'text'`.  It seems like this is fixed by using an older Doxygen, but I thought it might be useful to dig a bit deeper.  So I simply printed the object `param` right before the crash (it iterates over these before crashing), and got some like this...

```
param:
<param>
<type>SOURCES add_to_cli11.hpp cli_option.hpp default_param.hpp default_param_impl.hpp delete_allocated_memory.hpp end_program.hpp get_allocated_memory.hpp get_param.hpp get_raw_param.hpp get_printable_param.hpp get_printable_param_impl.hpp get_printable_param_name.hpp get_printable_param_name_impl.hpp get_printable_param_value.hpp get_printable_param_value_impl.hpp in_place_copy.hpp map_parameter_name.hpp output_param.hpp output_param_impl.hpp parameter_type.hpp parse_command_line.hpp print_doc_functions.hpp print_doc_functions_impl.hpp print_help.hpp print_help.cpp print_type_doc.hpp print_type_doc_impl.hpp set_param.hpp string_type_param.hpp string_type_param_impl.</type>
<declname>hpp</declname>
</param>
param:
<param>
<declname>${dir}</declname>
</param>
```

That's not C++ though, that's CMake.  (You can find the relevant bits in `src/mlpack/bindings/cli/CMakeLists.txt` and `src/mlpack/bindings/CMakeLists.txt`.)  I tried changing `exclude_patterns` in `doc/source/conf.py` to:

```
exclude_patterns = ['*.cmake']
```

but this did not seem to help.  Maybe there is some other way that the CMake files need to be excluded from the documentation build?

**Comment by Aakash-kaushik** [comment]
> Really cool to see this effort. When I tried to build locally, I also got the error `AttributeError: 'NoneType' object has no attribute 'text'`. It seems like this is fixed by using an older Doxygen, but I thought it might be useful to dig a bit deeper. So I simply printed the object `param` right before the crash (it iterates over these before crashing), and got some like this...
> 
> ```
> param:
> <param>
> <type>SOURCES add_to_cli11.hpp cli_option.hpp default_param.hpp default_param_impl.hpp delete_allocated_memory.hpp end_program.hpp get_allocated_memory.hpp get_param.hpp get_raw_param.hpp get_printable_param.hpp get_printable_param_impl.hpp get_printable_param_name.hpp get_printable_param_name_impl.hpp get_printable_param_value.hpp get_printable_param_value_impl.hpp in_place_copy.hpp map_parameter_name.hpp output_param.hpp output_param_impl.hpp parameter_type.hpp parse_command_line.hpp print_doc_functions.hpp print_doc_functions_impl.hpp print_help.hpp print_help.cpp print_type_doc.hpp print_type_doc_impl.hpp set_param.hpp string_type_param.hpp string_type_param_impl.</type>
> <declname>hpp</declname>
> </param>
> param:
> <param>
> <declname>${dir}</declname>
> </param>
> ```
> 
> That's not C++ though, that's CMake. (You can find the relevant bits in `src/mlpack/bindings/cli/CMakeLists.txt` and `src/mlpack/bindings/CMakeLists.txt`.) I tried changing `exclude_patterns` in `doc/source/conf.py` to:
> 
> ```
> exclude_patterns = ['*.cmake']
> ```
> 
> but this did not seem to help. Maybe there is some other way that the CMake files need to be excluded from the documentation build?

That actually is weird because we have the binding dir in exclude pattern in the doxyfile so the xml for that should never be produced but if it's parsing it i believe it is produced, i will take another look too.

**Comment by Aakash-kaushik** [comment]
And thanks for debugging the issue, makes much more sense now.

**Comment by Aakash-kaushik** [comment]
Keep open

**Comment by shrit** [comment]
@Aakash-kaushik That is really cool, the video looks great, let us know if you need any help with this pull request :+1:

**Comment by Aakash-kaushik** [comment]
> @Aakash-kaushik That is really cool, the video looks great, let us know if you need any help with this pull request 👍

Hi @shrit i was running a bit busy with so many things, but i think i will be able to work on this PR in the coming time.
Will post the updates on this PR itself.

**Comment by Aakash-kaushik** [comment]
I guess it's okay to attract some attention to this now, I was able to build the documentation and I know the things are placed all over the place but we can organize them the main part was parsing it, I hope we are past that now so below is a janky version of the hopefully new documentation.

https://user-images.githubusercontent.com/39410692/130361826-953e5736-6a95-438a-b1aa-1767060d6fd6.mp4

theme, format, and all of that can be changed later, but I don't know much about organizing content in RST files so some help/guidance there would be appreciated. and we can use an extension that parses content from markdown files so we won't need to shift to writing content in RST, it's just the customizing part.

**Comment by Aakash-kaushik** [comment]
> I guess it's okay to attract some attention to this now, I was able to build the documentation and I know the things are placed all over the place but we can organize them the main part was parsing it, I hope we are past that now so below is a janky version of the hopefully new documentation.
> 
>  Screencast.from.22-08-21.09_24_36.PM.IST.mp4 
> theme, format, and all of that can be changed later, but I don't know much about organizing content in RST files so some help/guidance there would be appreciated. and we can use an extension that parses content from markdown files so we won't need to shift to writing content in RST, it's just the customizing part.

Hi, So as we were able to get past the parsing error, we now need to discuss how we would like to present the documentation and which direction it should go to, so for discussing that can we hold a meet on this Friday(27th Aug) on the same time(1700 UTC) as mlpack meet in the same zoom room. 
everybody is welcome for the meet.

**Comment by Aakash-kaushik** [comment]
https://user-images.githubusercontent.com/39410692/132045199-7197e55e-30bf-49e2-a75f-8d79ae160738.mp4

**Comment by shrit** [comment]
@Aakash-kaushik what type of issue did you face when trying to use the Press theme?

**Comment by Aakash-kaushik** [comment]
> @Aakash-kaushik what type of issue did you face when trying to use the Press theme?

Hi, I don't exactly remember it but i can reproduce it tomorrow and let you know.

**Comment by shrit** [comment]
@Aakash-kaushik no problem, if you would like you can choose the same theme that you have selected for the mlpack models, it will be easier for this step.

**Comment by Aakash-kaushik** [comment]
Hi, I realized that I would not be able to work on this specific task as much as I wanted. I don't want it to stop so I will generate the initial docs or at least a good version of them which would further only need tuning them or writing some new RST files for how the docs should look. 
I will also write a [doxygen](https://github.com/mlpack/jenkins-conf/blob/master/Dockerfiles/jenkins-models-doc.Dockerfile) file similar to the one I wrote for the models repository so the generation of docs can be automated.

**Comment by Aakash-kaushik** [comment]
> Hi, I realized that I would not be able to work on this specific task as much as I wanted. I don't want it to stop so I will generate the initial docs or at least a good version of them which would further only need tuning them or writing some new RST files for how the docs should look. I will also write a [doxygen](https://github.com/mlpack/jenkins-conf/blob/master/Dockerfiles/jenkins-models-doc.Dockerfile) file similar to the one I wrote for the models repository so the generation of docs can be automated.

I would still try to actively help wherever i can, but I am not sure if i can dedicate time.

**Comment by Aakash-kaushik** [comment]
Created a [PR](https://github.com/mlpack/jenkins-conf/pull/28) to merge docker file.

**Pull request closed without merging**
