### PR TITLE
Attempt to fix double-free of XPtrs for R bindings

### LINKED ISSUE #3021: R RandomForest Leads to a Crash
#### Issue description

Hi, 

Thanks for this great package. I was interested in using the random forest classifier in R's mlpack for a classification problem using relatively large matrices (thousands of rows each with 200 features, so a 1000s x 200 dimension). The random forest classifier works great when I run it once, but within a few seconds after one run of a call of the classifier, my RStudio session crashes and forces a restart, with a message "Error occurred during transmission." I looked up why this could happen in RStudio and the most likely cause is that the memory in the session is maxed out by running the function.

I would appreciate any insights in understanding what exactly is causing this issue. 

Thank you so much!

#### Your environment

 * version of mlpack: mlpack 3.4.2.1 
 * operating system: not relevant (this is via a cluster)
 * compiler:
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

### PR DESCRIPTION
**Pull request by rcurtin**
This is an attempt to fix #3021.  I am not the best at R, so I would really appreciate if @Yashwants19 or @coatless or @eddelbuettel might give this one a look. :)

The problem I was trying to solve was a double-free of an XPtr when R's `gc()` function was called (detailed in #3021).  In short, what was happening was that an mlpack binding would take in a pre-trained model pointer (represented in R as an `XPtr`), and then the binding would run.  The binding might then return that exact same model pointer in a *new* `XPtr`, meaning that there were now *two* `XPtr`s in R that pointed to the same memory.  Then, when the garbage collection ran, *both* `XPtr`s would be free, causing segfaults.

The solution I settled on here is to collect all the models represented as `XPtr`s that the user passes as input to a binding in a list.  Then, after we run the binding, if the binding produces an output model, then we compare its memory pointer with those in the list of `XPtr`s.  If there is a match, we simply return the already-created `XPtr`.  We only return a new `XPtr` if there is *no* match.

In this way, R should never have two *different* `XPtr`s that point to the same memory---if my understanding of R's memory management is right.

The diff might be a little bit hard to read (since it's the diff for the generator), so I'll print the relevant parts of the "before" and "after" code for the Adaboost binding.

#### adaboost.R

```R
adaboost <- function(input_model=NA,
                     iterations=NA,
                     labels=NA,
                     test=NA,
                     tolerance=NA,
                     training=NA,
                     verbose=FALSE,
                     weak_learner=NA) {
  # Restore IO settings.
  IO_RestoreSettings("AdaBoost")

  # Process each input argument before calling mlpackMain().
  if (!identical(input_model, NA)) {
    IO_SetParamAdaBoostModelPtr("input_model", input_model)
  }

  ...

  # Call the program.
  adaboost_mlpackMain()

  # Add ModelType as attribute to the model pointer, if needed.
  output_model <- IO_GetParamAdaBoostModelPtr("output_model")
  attr(output_model, "type") <- "AdaBoostModel"

  # Extract the results in order.
  out <- list(
      "output" = IO_GetParamURow("output"),
      "output_model" = output_model,
      "predictions" = IO_GetParamURow("predictions"),
      "probabilities" = IO_GetParamMat("probabilities")
  )

  # Clear the parameters.
  IO_ClearSettings()

  return(out)
}
```

#### adaboost.cpp

```c++
...

// Get the pointer to a AdaBoostModel parameter.
// [[Rcpp::export]]
SEXP IO_GetParamAdaBoostModelPtr(const std::string& paramName)
{
  return std::move((Rcpp::XPtr<AdaBoostModel>) IO::GetParam<AdaBoostModel*>(paramName));
}

...
```

#### adaboost.R

```R
adaboost <- function(input_model=NA,
                     iterations=NA,
                     labels=NA,
                     test=NA,
                     tolerance=NA,
                     training=NA,
                     verbose=FALSE,
                     weak_learner=NA) {
  # Restore IO settings.
  IO_RestoreSettings("AdaBoost")
  # Initialize an empty list that will hold all input models the user gave us,
  # so that we don't accidentally create two XPtrs that point to thesame model.
  inputModels <- vector()

  # Process each input argument before calling mlpackMain().
  if (!identical(input_model, NA)) {
    IO_SetParamAdaBoostModelPtr("input_model", input_model)
    # Add to the list of input models we received.
    inputModels <- append(inputModels, input_model)
  }

  ...

  # Add ModelType as attribute to the model pointer, if needed.
  output_model <- IO_GetParamAdaBoostModelPtr("output_model", inputModels)
  attr(output_model, "type") <- "AdaBoostModel"

  # Extract the results in order.
  out <- list(
      "output" = IO_GetParamURow("output"),
      "output_model" = output_model,
      "predictions" = IO_GetParamURow("predictions"),
      "probabilities" = IO_GetParamMat("probabilities")
  )

  # Clear the parameters.
  IO_ClearSettings()

  return(out)
}
```

#### adaboost.cpp

```c++
...

// Get the pointer to a AdaBoostModel parameter.
// [[Rcpp::export]]
SEXP IO_GetParamAdaBoostModelPtr(const std::string& paramName,
                                      SEXP inputModels)
{
  Rcpp::List inputModelsList(inputModels);
  AdaBoostModel* modelPtr = IO::GetParam<AdaBoostModel*>(paramName);
  for (int i = 0; i < inputModelsList.length(); ++i)
  {
    Rcpp::XPtr<AdaBoostModel> inputModel =
        Rcpp::as<Rcpp::XPtr<AdaBoostModel>>(inputModelsList[i]);
    // Don't create a new XPtr---just reuse the one given as input, so that we
    // don't end up deleting it twice.
    if (inputModel.get() == modelPtr)
      return inputModel;
  }

  return std::move((Rcpp::XPtr<AdaBoostModel>) IO::GetParam<AdaBoostModel*>(paramName));
}

...
```

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Uh-oh.

"In theory" the XPtr class will register a finalizer to free if and when the R object it represents is called by the garbage collector in R.  That should "usually" be good enough.  Now, in $dayjob I ran into something similar (or, rather, `valgrind` did at CRAN and somethere from that yelled told me to get my act together and yanked the package off CRAN.  Ahem.  Glory days.

But that is the only case I am aware where things are done explicitly.  The implicitly route _should_ work and I can help you maybe with some mocked examples adding verbose finalizers and whatnot.

**Comment by rcurtin** [comment]
Well, but if we go the finalizer route, then I think we have to somehow keep track of all the `XPtr`s that mlpack has ever made to be able to know whether or not this one should have the default finalizer, or whether we just don't free at all.  (And even then, how do we choose which of the `XPtr`s lives the longest?)

In local testing, this PR does seem to fix the issue, by simply never allowing the mlpack bindings to create a second `XPtr` pointing at the same memory.

**Comment by eddelbuettel** [comment]
Gee that is longer than a Tolstoi novel over in #3021.  But you say two things of relevance, one repeated here.

> Is there a way to mark an XPtr as an "alias", e.g., it doesn't need to be freed in its finalizer? 

Yes there is a bool argument is the very XPtr constructor.

> meaning that there were now two XPtrs in R that pointed to the same memory

That strikes me a design problem on your side.  We cannot know you ask us to remove the same stuff twice.

Now, you *should* be able to protect yourself with finalizer that properly sets a `nullptr` and, on reentry, checks that one.  Of course, it will not (and cannot) help you if you have a shadow clone pointing to the same memory (now freed) thinking it is its own and attemption to free it too...

**Comment by eddelbuettel** [comment]
> this PR does seem to fix the issue, by simply never allowing the mlpack bindings to create a second XPtr pointing at the same memory.

Haven't looked at the PR yet but the idea is right.  "Don't violate the contract".  If you instantiate an XPtr be prepared for it being called and freeing.   (Or inst it with finalizer=false to avoid this, not sure how battle-tested that is.)

**Comment by rcurtin** [comment]
> That strikes me a design problem on your side. We cannot know you ask us to remove the same stuff twice.

Definitely that is true!  The fundamental decision to allow a binding to return the same model it received as input isn't really something we can change (that type of functionality is important for, e.g., incremental training), so I am trying to resolve it here just by ensuring that we never make a *second* `XPtr` to the same memory.  Based on what you've written, this sounds like it's a reasonable approach in concept.

**Comment by eddelbuettel** [comment]
We could conceivably cook up a 'XPtr 2ndGen' that is also a smart pointer / resource aware.  May make for a nice little side project.  But that is not what XPtr currently is.

**Comment by coatless** [comment]
@rcurtin maybe unmark as stale. I'll give this a 👍  @zoq can you approve?

**Comment by zoq** [comment]
Let's see if the merge conflict is resolved.

**Review by zoq — APPROVED** [review]
Looks good to me.

**Pull request merged**
