### PR TITLE
Bump minimum Boost version to 1.58

### PR DESCRIPTION
**Pull request by rcurtin**
I noticed that the nightly build is failing for old Boost versions:

http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/armadillo_version=armadillo-8.400.0,boost_version=boost_1_49_0,buildmode=debug,compiler_version=gcc-6.1.0,label=docker/642/console

This is because the new string encoding support in #1960 actually depends on support that wasn't available until Boost 1.58.  Luckily, this version of Boost is avaiable in Ubuntu 16.04 and can be obtained fairly readily for RHEL6 and RHEL7, so it's not "too new".

I updated all the relevant documentation that I could find, and removed any now-unnecessary backported Boost code.

(Also, I noticed that on old CMake, the `list(FILTER)` command isn't available, so I added a patch for that too.)

### CODE REVIEW

**Comment by lozhnikov** [comment]
Hmm... We backported `boost::string_view` and added a workaround. Perhaps the workaround fails sometimes. Maybe it can be fixed.

**Comment by rcurtin** [comment]
Yeah, but if you go back before Boost 1.58, it looks like the macro `BOOST_CXX14_CONSTEXPR` isn't defined.  Given that Boost 1.58 seems to be available in all of the long-term support distributions, I think it's quickest to just go with that. :smile:

**Comment by lozhnikov** [comment]
Yeah, I've just "googled" it. It seems that `BOOST_CXX14_CONSTEXPR` appeared in Boost 1.57.

**Comment by rcurtin** [comment]
Yeah, so maybe Boost 1.57 would work, but there is no other code in Boost 1.57 that seems to use it; the macro is just defined once and there is some basic documentation for it.  So I figured just going with 1.58 should be fine, just in case there are some other things missing from 1.57 since the C++14 support appears to be preliminary.

**Pull request merged**
