### PR TITLE
Headers bits

### PR DESCRIPTION
**Pull request by shrit**
no description is needed, just a self-explanatory proposal

### CODE REVIEW

**Comment by shrit** [comment]
this is too far from being merged. just a new structure

**Comment by rcurtin** [comment]
Yeah, I think I can agree with most of this.  Here are the changes I see:

 * All header files from the main library to `include/`
 * Remove convenience includes from `mlpack/methods/`
 * No more `methods/` directory, all the methods directly into `include/mlpack/`
 * Bindings into `/bindings/`
 * Tests into `/tests/`

Maybe there are more changes, let me know if I missed something.  I have two main suggestions:

 1. I think the bindings/ and tests/ should stay in `src/` (so, `src/mlpack/bindings/` and `src/mlpack/tests/`).  This will be in line with other C++ projects where all the .cpp files are stored in `src/`, but the headers are all in `include/`.  For us, this won't change the fact that you can just copy the `include/` directory and everything will work.
 
 2. I think we should leave the `methods/` directory in place, including the convenience headers (even though they are very simple!), because otherwise this is a major change to the API of the library (the include paths like `#include <mlpack/methods/decision_tree.hpp>` will change).  I also think that it's nice for users to split things into `core/` and `methods/`.

Those convenience headers were added so that a user could do `#include <mlpack/methods/decision_tree.hpp>` to get only the headers needed for that method.  This is important so that users can reduce compile time by including less.  That short form is preferable to forcing a user to do `#include <mlpack/methods/decision_tree/decision_tree.hpp>`.

**Comment by shrit** [comment]
so if I understand correctly you want only to have the headers moved out to a new directory called include?

**Comment by rcurtin** [comment]
Sorry, just realized I never responded to this.  Yeah, that is the basic idea: the headers should move to `include/`, and we can leave other things as-is.

**Pull request closed without merging**
