### PR TITLE
LMNN optimization: use bounds from previous iterations in tree-based kNN search

### PR DESCRIPTION
**Pull request by rcurtin**
This PR is to solve #1445 and #1446.  It implements the following:

 * Reuse trees from previous calls to `Impostors()`.
 * Use bounded values of impostors from previous calls to set bounds for this iteration's call to `Impostors()`.
 * Prune points based on impostor bounds from #1448 so they are not recomputed with the tree-based search.
 * Allow rebuilding of trees when the transformation is different enough from the one when the trees were built.

It took me a long time of playing with this to get it to work reasonably.  I'll add benchmarking times in the next little while.  I don't yet know if rebuilding the trees is helpful, but I think I have seen reasonable speedup (think 20-30% or more) from the tree optimizations overall.

### CODE REVIEW

**Comment by rcurtin** [comment]
Note that this is dependent on #1494 being merged, since it won't work with the old style of SGD impostor calculation which only computed impostors for small batches at a time.  When that's merged I'll adapt the code here accordingly.

**Comment by rcurtin** [comment]
@manish7294: sorry, I forgot to tag you in this!  Take a look and let me know what you think when you have a chance.

**Comment by manish7294** [comment]
Hi Ryan, Thanks for working over it, It's good to see all this work. I am extremely sorry for delay from my side, just few more days and my mid-semester exams will be over.

**Comment by manish7294** [comment]
Great! This is a lot of intelligent work, It good to hear that you got such significant speedups. Sorry for asking this, but do you have any numbers on accuracy and timing? Please don't bother to run simulations in case you don't have them saved somewhere. Now, code looks much cleaner, specially lmnn_function_impl.hpp & constraints_impl.hpp :) 
I guess I should hurry up with #1494 as well.

**Pull request closed without merging**
