### PR TITLE
Adds ComputeRecall function to LSHSearch for easier tuning

### PR DESCRIPTION
**Pull request by mentekid**
This is a small change to add that function. I would have added it to the Multiprobe commit but though I should keep that one clean.

### CODE REVIEW

**Comment by rcurtin** [comment]
I hate to be picky but we should add a test for this function. It can be very easy... pass in the same vectors, make sure we get 100%, pass in half correct vectors, make sure we get 50%, pass in completely wrong vector, make sure we get 0%.

**Comment by mentekid** [comment]
You're right. I also added an exception for bad arguments to ComputeRecall, because I've found armadillo's error to not be informative enough.

I think grouping them as one testcase is better than adding 3-4 smaller ones, since we're testing the same function, do you agree?

**Comment by rcurtin** [comment]
Personally I would write three or four tests but I can't come up with any compelling reason with which I can convince you to do that, so one test is fine. :)

**Comment by mentekid** [comment]
I went ahead and split them, that way if one of them fails the error message is more informative - Before it would be about the ComputeRecall test failing but now you can see what the reason is. Which might be helpful, failing the exception requirement is completely different from failing the 100% recall requirement.

**Comment by rcurtin** [comment]
Sorry for not merging this sooner, it looked just fine.  I changed the `ComputeRecall` function to static in bee9567 since it uses no member functions.  I also removed the `ComputeRecall` function from the tests and instead used the one you wrote.

**Pull request merged**
