### PR TITLE
AMF, remove C++11 alternative branch.

### PR DESCRIPTION
**Pull request by zoq**
Simple adjustment.

### CODE REVIEW

**Comment by zoq** [comment]
Looks like it's not a simple adjustment, have to take a closer look.

**Comment by rcurtin** [comment]
Looks like `MLPACK_USE_CXX11` was never actually used completely, so it seems like something strange has been in there.

If I am remembering correctly, the original idea was that you would use `FactorizerType<MatType>` to specify what you wanted.  But pre-C++11, template typedefs were not supported.  So Sumedh chose to define `SVDBatchFactorizer` and `SparseSVDBatchFactorizer`, and when the switch to C++11 was done, a user would use `SVDBatchFactorizer<arma::mat>` or `SVDBatchFactorizer<arma::sp_mat>` instead.

So I think to make this work, all the `SparseSVD...` types need to be replaced in the code with `SVD...<arma::sp_mat>` and others replaced with `SVD...<>` (and probably a default parameter should be added to those template typedefs for `arma::mat`.

Let me know if I can clarify further.  Sorry for the strangeness here...

**Comment by zoq** [comment]
I see, so I guess the question is, can we remove the typedef? At least it's not backwards compatible. Perhaps there is no need to provide backwards compatibility, if we incorporate the change only in mlpack 3.0.

**Comment by rcurtin** [comment]
I think it's fine to remove backward compatibility, since the next release will be mlpack 3.0.0.

**Pull request merged**
