### PR TITLE
A small bug fix for SAC agent, while loading a pretrained model

### PR DESCRIPTION
**Pull request by nishantkr18**

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Nice catch, let me rerun the failed windows job to see if this was just a temporary issue, looks like it is.

**Review by zoq — APPROVED** [review]
Alright green build, thanks for the quick patch.

**Comment by zoq** [comment]
Thanks, I'll rebuild the mlpack package.

**Comment by zoq** [comment]
Okay, new image build and uploaded.

**Comment by zoq** [comment]
Will train the model with the script you send yesterday, later.

**Comment by nishantkr18** [comment]
> Will train the model with the script you send yesterday, later.

Sure 👍

**Pull request merged**
