### PR TITLE
[WIP] Add Constant, reflective and symmetric padding.

### PR DESCRIPTION
**Pull request by kartikdutt18**
Add support for constant, reflective and symmetric padding.

- [ ] Add reflective padding
- [ ] Add Symmetric padding 
- [x] Add constant padding
- [ ] Tests for new padding

Use Case:
Reflective padding used in Siamese Network.

Currently even comments aren't complete.
This will take me a day or two complete.
Thanks.

### CODE REVIEW

**Comment by codeboy5** [comment]
> Add support for constant, reflective and symmetric padding.
> 
> * [ ]  Add reflective padding
> * [ ]  Add Symmetric padding
> * [x]  Add constant padding
> * [ ]  Tests for new padding
> 
> Use Case:
> Reflective padding used in Siamese Network.
> 
> Currently even comments aren't complete.
> This will take me a day or two complete.
> Thanks.

@kartikdutt18 , would you like some help ? I can take one of these

**Comment by kartikdutt18** [comment]
Hi @codeboy5, I have implemented reflective padding and working my way through symmetric padding. You could add suggestions for the same or tests cases that I must add  when I push the code in the next couple of days (Hopefully, in the middle of mid-semester examinations right now). I would really appreciate any suggestions.

**Comment by saraansh1999** [comment]
Can I take up reflective padding if you are not already started with it?

**Comment by codeboy5** [comment]
> Hi @codeboy5, I have implemented reflective padding and working my way through symmetric padding. You could add suggestions for the same or tests cases that I must add when I push the code in the next couple of days (Hopefully, in the middle of mid-semester examinations right now). I would really appreciate any suggestions.

I would love to provide whatever suggestions I can think of after 

> Hi @codeboy5, I have implemented reflective padding and working my way through symmetric padding. You could add suggestions for the same or tests cases that I must add when I push the code in the next couple of days (Hopefully, in the middle of mid-semester examinations right now). I would really appreciate any suggestions.

I would love to write the test cases and provide any suggestions after you are done. Let me know after you are done !!

**Comment by codeboy5** [comment]
> Hi @codeboy5, I have implemented reflective padding and working my way through symmetric padding. You could add suggestions for the same or tests cases that I must add when I push the code in the next couple of days (Hopefully, in the middle of mid-semester examinations right now). I would really appreciate any suggestions.

@kartikdutt18  I would love to write the test cases and provide any suggestions after you are done. Let me know after you are done !!

**Comment by rcurtin** [comment]
This code touches the ANN code, and there was recently a big refactoring of the ANN code in #2259, so be sure to merge the master branch into your branch here to make sure that nothing will fail if this PR is merged. :+1: (I'm pasting this message into all possibly relevant PRs.)

**Comment by kartikdutt18** [comment]
Keep Open please. Thanks.

**Comment by kartikdutt18** [comment]
Keep open.

**Pull request closed without merging**
