### PR TITLE
Fix garbage collection for Julia mlpack models

### PR DESCRIPTION
**Pull request by rcurtin**
@spott pointed out in chat that mlpack models in Julia actually don't correctly deallocate.  In Julia, this is the definition of an mlpack model:

```julia
struct LARSModel
  ptr::Ptr{Nothing}
end
```

i.e., an mlpack model is just a wrapper around a C++ pointer that was allocated by mlpack.  But there's no way anything can free this pointer.

Therefore, this PR adds finalizers to these models, producing a definition like this:

```julia
mutable struct LARSModel
  ptr::Ptr{Nothing}

  function LARSModel(ptr::Ptr{Nothing})
    result = new(ptr)
    finalizer(
        x -> _Internal.lars_internal.DeleteLARS(x.ptr),
        result)
    return result
  end
end
```

This is more complex, but to my understanding this basically registers a destructor for that particular Julia object in its constructor.  That destructor, which calls `_Internal.lars_internal.DeleteLARS()` in the example above, is simply a function which itself calls a C++ function that just calls `delete` on the model:

```julia
# Delete an instantiated model pointer.
function DeleteLARS(ptr::Ptr{Nothing})
  ccall((:DeleteLARSPtr, larsLibrary), Nothing, (Ptr{Nothing},), ptr)
end
```

And then this is the implementation of `DeleteLARSPtr`, in C++:

```c++
// Delete a LARS pointer.
void DeleteLARSPtr(void* ptr)
{
  LARS* modelPtr = (LARS*) ptr;
  delete modelPtr;
}
```

I tested locally and it appears that the Julia garbage collector does now successfully deallocate mlpack models when they go out of scope and when the Julia garbage collector decides it's time to do so.

### CODE REVIEW

**Comment by rcurtin** [comment]
Actually, there is a bug here---a finalizer might be applied to multiple models and we may end up accidentally freeing a pointer multiple times.  So I will have to rework this some.

**Comment by rcurtin** [comment]
It turns out there was a bug in my approach.  Some bindings "pass through" the input model to the output, and in this situation my code was adding a finalizer twice.  This caused a double free situation.  So, I made things a little bit more complex, and now bindings keep track of all of the input model pointers they receive, and if an output model's pointer is in the set of input model pointers, no finalizer is added.

@spott I think this should fix your issue.  I also added a test case that tests this exact situation---it failed before, and then with the changes I just pushed, now it works. :+1:

**Review by zoq — APPROVED** [review]
Interesting issue, this looks good from my side.

**Comment by rcurtin** [comment]
All of the tests look like random failures unrelated to this PR (or Julia at all), so I'll go ahead and merge. :+1:

**Pull request merged**
