### PR TITLE
Naive bayes open mp

### PR DESCRIPTION
**Pull request by Param-29**
Updated Naive-bayers algorithm using OpenMP

Parallel performance
```
 Performance counter stats for './a.out':

          4,832.91 msec task-clock                #    2.228 CPUs utilized          
             1,361      context-switches          #    0.282 K/sec                  
                 5      cpu-migrations            #    0.001 K/sec                  
          2,68,842      page-faults               #    0.056 M/sec                  
   14,13,51,27,551      cycles                    #    2.925 GHz                    
   28,15,16,10,366      instructions              #    1.99  insn per cycle         
    3,96,58,59,478      branches                  #  820.595 M/sec                  
         72,48,991      branch-misses             #    0.18% of all branches        

       2.168900872 seconds time elapsed
```
Serial performance
```
  Performance counter stats for './a.out':

          2,340.65 msec task-clock                #    0.998 CPUs utilized          
                79      context-switches          #    0.034 K/sec                  
                 1      cpu-migrations            #    0.000 K/sec                  
          2,68,715      page-faults               #    0.115 M/sec                  
    7,14,82,79,708      cycles                    #    3.054 GHz                    
   14,69,13,09,319      instructions              #    2.06  insn per cycle         
    1,86,35,21,341      branches                  #  796.154 M/sec                  
         54,69,859      branch-misses             #    0.29% of all branches        

       2.346010126 seconds time elapsed

```
Compiled using 

`g++ test.cpp -fopenmp -lmlpack -larmadillo -g -lopenblas`

### CODE REVIEW

**Comment by jeffin143** [comment]
How it is different from #2286

**Comment by Param-29** [comment]
> How it is different from #2286

In this I tried updating naive bayes algorithm while in #2289 I tried updating naive method for kernel_pca. Please have a look on changes in files I have made.

**Comment by jeffin143** [comment]
> > How it is different from #2286
> 
> In this I tried updating naive bayes algorithm while in #2289 I tried updating naive method for kernel_pca. Please have a look on changes in files I have made.

That was. Mistake on my part, I just had a glance at pr title , and thought I have seen somewhere so I guessed that you might have opened it by mistake , but now I can see that it's for 2 different algorithms

**Comment by birm** [comment]
What's in test.cpp? Also, it may be a good idea to show how both scale. The chart in #2169 is nice, but 2-3 points would satisfy my curiosity, personally.

**Comment by Param-29** [comment]
> What's in test.cpp? Also, it may be a good idea to show how both scale. The chart in #2169 is nice, but 2-3 points would satisfy my curiosity, personally.

Hey @birm,Thanks for your response.
Following is the graph you requested.
Series and Parallel(Naive Bayes)

test.cpp is a file where I build and test the model.

Average Speed-up achieved :- 9.45%
Compiled using `g++ -fopenmp -lmlpack -larmadillo -lopenblas test.cpp`

**Comment by Param-29** [comment]
I also had a few questions and was hoping you could help me with that:

1) I wanted to know data-type of `variances.col(label)`.
2) I wanted to make reduction for `arma::mat` and other data-types as well. So I was hoping you can guide me with that :)

References:
https://software.intel.com/en-us/articles/openmp-40-new-features-supported-in-intel-compiler-160
https://gist.github.com/eruffaldi/7180bdec4c8c9a11f019dd0ba9a2d68c

thanks @kartikdutt18 for the idea.

**Comment by rcurtin** [comment]
Scaling between 100k and 140k points isn't very demonstrative of scaling properties; I would suggest going between, e.g., 1k and 10M on a log-scale.  There are other details that would be necessary to understand the difference here: (1) how many cores? (2) what happens as you scale OMP_NUM_THREADS? (3) what happens when OMP_NUM_THREADS is set to 1? (4) how much parallelism is already achieved by OpenBLAS for many of these Armadillo computations? (5) what are your system details? (6) Did you compile with any optimizations? (7) What were the details of compilation for mlpack (not just your test script)? (8) Of the runtime of your program, what are the speedups for the actual parts that you parallelized (and not the whole thing overall)?

**Comment by Param-29** [comment]
Hey @rcurtin , thank you for your quick response
> Scaling between 100k and 140k points isn't very demonstrative of scaling properties; I would suggest going between, e.g., 1k and 10M on a log-scale. There are other details that would be necessary to understand the difference here:

Yes completely agreed. So I performed additional tests as you asked. 
>(1) how many cores? 

4 cores

>(2) what happens as you scale OMP_NUM_THREADS? (3) what happens when OMP_NUM_THREADS is set to 1?

Serial Part of the graphs are the result when OMP_NUM_THREADS is set to 1.
 
>(4) how much parallelism is already achieved by OpenBLAS for many of these Armadillo computations?
 
Original results show performance achieved by parallelism achieved by OpenBLAS.
>(5) what are your system details? (6) Did you compile with any optimizations? 

I'll add my system's details. No I didn't. This is because I'll loose on profiling information of the functions.
>(7) What were the details of compilation for mlpack (not just your test script)?

I didn't really understand your question here. 
>(8) Of the runtime of your program, what are the speedups for the actual parts that you parallelized (and not the whole thing overall)?

This can be seen my comparing original and Updated lines/bars of the graphs.
Following are the required graphs.

Train Profiling

Train Profiling(1)

Test Profiling

Test Profiling(1)


> Unfortunately there's a lot of complexity to benchmarking and deciding whether something should be included or not. You may see 9.45% speedup on your system, but it's not a guarantee that people will in other situations, and that's what makes this task so difficult.

Yes, but this is what challenges me. I agree these tests are system dependent and this is what makes testing task even more difficult but someone needs to do these for making sure performance of mlpack's algorithms keep improving. 🙂

**Comment by Param-29** [comment]
Hey @rcurtin , I have updated the code after some profiling for better performance.
Following are the results:
Training function of Naive_bayes
Training function of naive_bayes
Testing function of naive_bayes
Testing function of Naive_bayes

[Here is the link for time taken and graphs.](https://docs.google.com/spreadsheets/d/1-DW20bHJjjp__BNuawSxNesMf1b18X-3coCtgfZHS6U/edit?usp=sharing)

compiled using
` g++ test.cpp -fopenmp -lmlpack -larmadillo -lopenblas -o2`

[Link for test.cpp](https://github.com/Param-29/mlpack-profiling/blob/master/naive%20bayes(mlpack)/test.cpp)

**Comment by Param-29** [comment]
Hello, I was hoping we if we could keep this issue open. I an waiting for review on this PR.
Thanks.

**Pull request closed without merging**
