### PR TITLE
Add Docker build support

### PR DESCRIPTION
**Pull request by NaxAlpha**
GSoC: Build testing with Docker and VMs
Hi, I have added basic docker build support

https://hub.docker.com/r/naxalpha/mlpack/
http://pastebin.com/K1dEDpMp

### CODE REVIEW

**Comment by NaxAlpha** [comment]
To use mlpack from Docker, follow these steps

- Install Docker
- Run Docker (Quickstart Terminal in Windows)
- `docker pull naxalpha/mlpack` This command will download docker image (Max Size: 1.5 GB)
- ` docker run --rm -it -v $PWD:/mlpack-run -w /mlpack-run naxalpha/mlpack` To run mlpack apps from current directory
- `mlpack_knn --k=5 --reference_file=input.csv --distances_file=distances.csv --neighbors_file=neighbors.csv` Make sure `input.csv` is in current directory, after running command, `distance.csv` and `neighbors.csv` will be in current directory of your **host OS**

**Comment by rcurtin** [comment]
Hi there,

I'm not sure what the goal of this Docker container is.  Is this for the build testing project?  That project is actually focused on using Docker containers to get different versions of the library dependencies, so that the build system can use these Docker containers to build mlpack.  So a Docker container that just contains mlpack would not be what's needed there.  If you can clarify the purpose here, we can figure out where to go with it.

Thanks!

**Comment by NaxAlpha** [comment]
Hi @rcurtin, 

At the moment, basic goal of Docker container is to provide build for testing project and testing mlpack latest version without install it on system. Later on, we can have build for multiple version of mlpack.

Thanks.

**Comment by rcurtin** [comment]
Right, I see.  If that is the case, the Dockerfiles to build the containers should be included in the `jenkins-conf` repository since that is where the containers will actually be built.  But I don't think there is reason to include this Dockerfile there until the build system is ready, and I don't think it's appropriate to include a Dockerfile in the main mlpack repository, so I'll go ahead and close this.  But, it is still a good start towards the testing project!

**Comment by NaxAlpha** [comment]
Ok got it!

**Pull request closed without merging**
