### PR TITLE
GCC 10 and Clang 10 build warnings fixes

### PR DESCRIPTION
**Pull request by lozhnikov**
The PR fixes the following types of warnings:

- GCC 10 warning types:
```
src/mlpack/methods/ann/layer/vr_class_reward_impl.hpp:43:31: warning: comparison of unsigned expression in ‘>= 0’ is always true [-Wtype-limits]
   43 |     Log::Assert(currentTarget >= 0 && currentTarget < input.n_rows

src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp:527:30: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  527 |   if (totalHorizontalPadding < 0 || totalVerticalPadding < 0)

src/mlpack/methods/amf/termination_policies/simple_tolerance_termination.hpp:31:7: warning: ‘<anonymous>.mlpack::amf::SimpleToleranceTermination<arma::Mat<double> >::V’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   31 | class SimpleToleranceTermination
```
Both `-Wtype-limits` warnings produce massive output many times.
- Clang 10 warning types:
```
src/mlpack/methods/gmm/gmm_train_main.cpp:253:13: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
            std::move(arma::diagmat(dgmm.Component(i).Covariance())));

src/mlpack/methods/ann/rnn_impl.hpp:93:41: warning: unused parameter 'optimizer' [-Wunused-parameter]
WarnMessageMaxIterations(OptimizerType& optimizer, size_t samples) const

src/mlpack/methods/ann/gan/metrics/inception_score_impl.hpp:35:21: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
  for (int i = 0; i < splits; i++)

src/mlpack/core/metrics/non_maximal_supression_impl.hpp:130:14: warning: unused parameter 'ar' [-Wunused-parameter]
    Archive& ar,
```

### CODE REVIEW

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by lozhnikov** [comment]
Actually, I didn't fix [static analysis issues](http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/5480/cppcheck/fileName.-1029166357/) in `recurrent_network_test.cpp`. The build should have failed.

**Comment by lozhnikov** [comment]
I think these failures are false positives. Anyway, it's better to check. Let me look into it.

**Comment by zoq** [comment]
> Hmm, strange that the `recurrent_network_test.cpp` failures don't show up anymore, but in any case, I think this is still a great improvement and we should merge it. 💯

Indeed, let me restart the build one more time.

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
Everything looks great.  Thanks @lozhnikov!

**Pull request merged**
