### PR TITLE
Disable auto-download by default + improve test stability

### PR DESCRIPTION
**Pull request by zoq**
Looks like we never disabled the auto-download by default (https://github.com/mlpack/mlpack/pull/2953).

### CODE REVIEW

**Comment by zoq** [comment]
It is and we download dependencies if `DOWNLOAD_DEPENDENCIES` is `OFF`, which is not correct.

**Comment by zoq** [comment]
@shrit does the cross-compiling expect that all deps are downloaded via the auto-downloader? When I run `cmake` inside the `mlpack/jenkins-amd64-debian` docker container it can find `ensmallen` but when I run `cmake` with the cross-compiling env enabled it can't find ensmallen anymore, the same applies to armadillo, but with https://github.com/mlpack/mlpack/pull/3076/commits/68cb6ee00ebe9b8054ca7169da1fc8e44416fde3 we download armadillo.

**Comment by shrit** [comment]
@zoq When cross-compiling we should only use the auto downloader to get the dependencies, we should not use the dependencies that are already installed on the machine.

**Comment by zoq** [comment]
What is the reason for this? ensmallen and stb is header only, so we could just use whatever is available. Or even if it isn't a user should be able to specify what to use. Maybe I'm missing something?

**Comment by zoq** [comment]
Thanks for the clarification, do you think another way would be to copy or symlink the files into the `build/deps` directory? A potential issue I see with the current approach is that you can't use your own package, like if someone uses a modified ensmallen lib or needs a specific version.

You are right that having a static system where we know exactly what packages are used is ideal since it removes dependency issues, so I don't like to change that; we just have to make sure this is documented somewhere because people might wonder why dependencies are downloaded that already exist on the host system.

**Comment by rcurtin** [comment]
> @rcurtin looks like some cert in the chain is outdated:
> 
> ```
> --2021-10-16 21:32:52--  https://mlpack.org/files/stb.tar.gz
> Resolving mlpack.org (mlpack.org)... 161.8.32.26
> Connecting to mlpack.org (mlpack.org)|161.8.32.26|:443... connected.
> ERROR: cannot verify mlpack.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
> ```

Seems like things are okay now?  I tested locally and wget didn't give any errors.



> @Yashwants19 do you make any sense out of:
> 
> ```
> Run Rscript -e "rcmdcheck::rcmdcheck('mlpack_3.4.3.tar.gz', args = c('--no-manual','--as-cran'), error_on = 'warning', check_dir = 'check')"
> Error: Error in loadNamespace(x) : there is no package called ‘rcmdcheck’
> Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
> ```
> 
> looks like the same command works on macOS and Windows.

Ah, I just encountered this elsewhere; I think https://github.com/mlpack/mlpack/pull/2973/commits/dfe3f465d11cf8574c00b7bba46cc1a81b4edd96 will fix it. :+1:

**Comment by rcurtin** [comment]
Hmm, maybe `acmetool` hadn't updated the certs or something, but I guess it's good to go now.  If it happens again let me know and I can investigate the configuration. :)

**Comment by zoq** [comment]
@rcurtin not sure if you have seen the Julia issue before, but I guess if we update the Julia version it's fixed?

**Comment by zoq** [comment]
```
MultiSplitTest2
-------------------------------------------------------------------------------
/Users/runner/work/1/s/src/mlpack/tests/decision_tree_regressor_test.cpp:636
...............................................................................

/Users/runner/work/1/s/src/mlpack/tests/decision_tree_regressor_test.cpp:654: FAILED:
  REQUIRE( preds[i] == responses[i] )
with expansion:
  1.6666666667 == 1.0
```

@RishabhGarg108 maybe you have an idea?

**Comment by zoq** [comment]
We have a second winner `LogisticRegressionSparseLBFGSTest`.

**Pull request merged**
