### PR TITLE
Use 0 to numClasses - 1, not 1 to numClasses in NegativeLogLikelihood

### PR DESCRIPTION
**Pull request by rcurtin**
This PR may warrant some discussion, since it's a breaking change.  (So, that said, if we do include it, we shouldn't merge it until 4.0.0.  But, that will surely be soon anyway with the cereal refactoring being breaking too...)

Our `NegativeLogLikelihood` class expects labels to be in the range from `1` to `numClasses`.  But all of the other mlpack algorithms that do classification expect labels to be in the range from `0` to `numClasses - 1`.  For a long time I think that this has been a point of confusion for users, although I don't have any examples of related issues handy.

This would change `NegativeLogLikelihood` to use labels in the range from `0` to `numClasses - 1` like the rest of mlpack.  Many tests needed to be changed to make this happen.

If we do decide that merging this is the right thing to do, then before merge:

 - [x] make sure this is a part of the 4.0.0 release and not anything earlier
 - [x] open corresponding PRs in the models/ and examples/ repositories to update behavior
 - [x] make sure a clear CHANGELOG entry is included
 - [x] update any tutorials or documentation
 - [x] merge all PRs at the same time :)

Let me know what you think! :)

### CODE REVIEW

**Comment by rcurtin** [comment]
Awesome, now we will have to wait to merge this until we are done with the 3.x.x series of releases. :)

**Comment by jeffin143** [comment]
@rcurtin Do you want to take a look at this again ?

**Comment by rcurtin** [comment]
@jeffin143 yeah, I think it's about time.  The only thing is it will probably break all the examples and everything, so some caution will be necessary.  I'll start by merging master in and at least getting it to pass the tests here. :)

**Comment by rcurtin** [comment]
https://github.com/mlpack/examples/pull/142 changes the behavior in the `examples` repository.

**Comment by rcurtin** [comment]
To the best of my understanding, the `models` repository doesn't require any changes.

**Comment by jeffin143** [comment]
@rcurtin If this is done, then let's merge it ?

**Comment by rcurtin** [comment]
Yeah---let's merge this as soon as the build comes back green (or... mostly green!), and then I'll focus on the PR in the `examples` repository to make sure it works. :+1:

**Comment by rcurtin** [comment]
Ok, I'll go ahead and merge this now that the tests are passing. :+1:  This may make a merge for #2777 difficult but hopefully not *too* hard. :)

**Comment by zoq** [comment]
hehe, I copied the current "CheckCopyMovingVanillaNetworkTest" test into my local branch and was wondering why it worked yesterday but now throws an error.

**Comment by rcurtin** [comment]
Sorry for any breakages! :smile: Luckily this one is easy to fix.

**Pull request merged**
