### PR TITLE
Add documentation for BallBound and BallTree.

### PR DESCRIPTION
**Pull request by rcurtin**
Using the existing `binary_space_tree.md` documentation, I added documentation for `BallTree` (which is just a typedef of `BinarySpaceTree`).  This included:

 * Documentation for `BallBound`: [link](http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/874/Built_20documentation/user/core/trees/binary_space_tree.html#ballbound)
 * Documentation for `BallTree`: [link](http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/874/Built_20documentation/user/core/trees/ball_tree.html)
 * Updates to the links in the developer documentation: [link](http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/874/Built_20documentation/developer/trees.html#a-list-of-trees-in-mlpack-and-more-information)

As with #3801, the `BallTree` documentation is basically the same as the `KDTree` documentation, but has been adjusted in a few places throughout for correctness.  I also included some details at the top of the page indicating why you might use a ball tree vs. a kd-tree.

~(I'll add links to each page when the documentation build succeeds.)~ done

### CODE REVIEW

**Review by shrit — COMMENTED** [review]
Looks nice, but I would modify it in a different way:

1. I would add on the left side in the side bar a list of docs in the Developer, will be easier to access all the articles inside without the need to go back to the main page.

2. I would move BallBound to ballTree,  as I expect it to be there. Also because the BinarySpaceTree page is becoming insanely big and need some adjustment


3. In the following:

Screenshot 2024-09-29 at 12-08-54 mlpack documentation

I would add another declaration with the real template parameters used instead of the at the middle of this paragraph. For instance, at the start you have this constructor `BallTree<DistanceType, StatisticsType, MatType>`, and at the end of the paragraph I would add something like `BallType<EuclideanDistance, EmptyStatistics, arma::mat>` it might look like hand holding, but this is really nice in understanding what are you trying to say in the paragraph, will make the point 100 percent more reachable, especially if someone is new to intermediate C++ user. I would do the same for the other tree PR's. 
Also I would do the same with the BinarySpaceTree so people can understand where BallTree is coming from.

It is annoying that the tree is called node in this class it gives the impression that we can have several nodes at the same time, and when you say calculate the distance from a node to a point, do you mean from the entire tree? if yes how does this work ? it 
is a bit confusing.

It would be nice to have one or two additional lines explaining what this example is doing, either inside the code or outside, up to you.

Screenshot 2024-09-29 at 12-23-31 mlpack documentation

**Comment by shrit** [comment]
Make sense, I like the idea you can add the default parameters and then assign it to the variable, nice

**Comment by shrit** [comment]
It is up to you, we will see how this will be in the future, I want to avoid having all the information in the Binary Space Tree page

**Review by shrit — APPROVED** [review]

**Comment by rcurtin** [comment]
I added the bit about default template arguments, and also added an image showing what the ballbound is (it's pretty simple).  I'll link to it when the build is done.  I also added some separators for clarity, but that's pretty minor.

I agree that we will need to figure out something to do with all the different bound types; but if you don't mind let's push that until later---when we have more, it may become clearer what we need to do (just like with the main page).

**Pull request merged**
