### PR TITLE
Replace boost enable if by std::enable_if

### PR DESCRIPTION
**Pull request by shrit**
This replacement should cover mlpack code base entirely. Some of them are replaced by hand while others using regular expression. I have tested them locally except Go lang.

### CODE REVIEW

**Comment by shrit** [comment]
I think the failures are not related, I remember there was a feature that allowed me to re-run the tests, but I can not find it anywhere. What did happen to this feature?

**Comment by jeffin143** [comment]
This is nice 🎉🎉

**Comment by zoq** [comment]
> I think the failures are not related, I remember there was a feature that allowed me to re-run the tests, but I can not find it anywhere. What did happen to this feature?

What test do you mean?

**Comment by shrit** [comment]
@zoq there was an unrelated failing test, but, after restarting Azure it passed.

**Review by rcurtin — COMMENTED** [review]
Awesome, looks great!  I know it is tedious, but do you think you can fix the style issues?  I think they are all line length issues. :)

I was going to say "now we can remove another boost header!" but it seems like `enable_if` and `disable_if` are included as parts of other functionality that includes boost.  But, soon hopefully we can get rid of those too! :smile:

**Comment by shrit** [comment]
Agreed, it is hard to get rid of `Boost`.

**Comment by shrit** [comment]
All green :+1:

**Review by rcurtin — APPROVED** [review]
Awesome, thank you for fixing those style issues! :+1:

**Review by zoq — APPROVED** [review]
Nice, looks great to me.

**Pull request merged**
