### PR TITLE
Fix mapping issue

### PR DESCRIPTION
**Pull request by stereomatchingkiss**
Fix the issue mentioned in #658

### CODE REVIEW

**Comment by rcurtin** [comment]
I agree, this is a nicer approach to the loading problem.  But I am a little concerned about speed: if we are loading the entire csv into `vector<vector<string>>`, this could mean lots of memory allocation if the dataset is of any significant size.  It's possible to do better with memory, by not storing the dataset entirely in memory: we read a row at a time, and if one of the dimensions has to be mapped, then we need to just read through the file again, getting the right columns, and applying the mappings and updating the matrix we have.  (If the matrix is not to be transposed, we only need to read through the row we are looking at.)

So it might be worth checking how long this takes on datasets that are, say, 100MB and make sure it does not take insanely long.  (Although realistically, if the user wants fast loading, they should not be using CSV!)

**Comment by stereomatchingkiss** [comment]
>this could mean lots of memory allocation if the dataset is of any significant size

I agree with that, this solution is not memory efficient. 

>we read a row at a time, and if one of the dimensions has to be mapped, then we need to just read through the file again, getting the right columns, and applying the mappings and updating the matrix we have

This solution will save much more memory, drawbacks are slower speed(IO manipulation is expensive) and more complicated file manipulation. 

I think the problem is, should we apply this optimization?Realistically, If the files are big, the users should not use CSV from the beginning.

>Although realistically, if the user wants fast loading, they should not be using CSV

Agree

>If the matrix is not to be transposed, we only need to read through the row we are looking at

This part already did, I only store the whole string into vector of vector when the users want to transpose the file.

**Comment by keonkim** [comment]
@stereomatchingkiss 
> Realistically, If the files are big, the users should not use CSV from the beginning.
Yes, but some companies/people do... I've seen csv with several gigabytes (14gb was the largest one I witnessed). Loading all them into memory could be troublesome. We can guide them to convert it to something else, but that might decrease mlpack's accessibility.

**Comment by rcurtin** [comment]
@keonkim I agree, unfortunately, you're right that CSV is a standard format.  I think that people should avoid using it, but you have a point that people will anyway, and I think if mlpack is very slow to load CSV in this setting, people may start avoiding mlpack because they think it is slow.

**Comment by rcurtin** [comment]
I should clarify, it is not unfortunate that you are right, it is unfortunate that CSV is a standard format. :)

**Comment by stereomatchingkiss** [comment]
Unfortunately, looks like we better try to optimized the speed of CSV loading. I do not think re-read the file is a good idea since IO manipulation is very time consuming, fetch from main memory took about 100 nanosec, read 1MB sequentially from memory took 250,000 nanosec(([This link give a measurement](http://norvig.com/21-days.html))). 

I think, if we want to make file reading faster, we could try our best to minimize the time of IO manipulation(trading memory for speed), next step is speed up the processing speed of string. 

I would generate a file around 50MB to do the test, write a new class to parsed the CSV file. Test the performance with different solutions, including boost::spirit and multithread. spirit is very fast, but the compile time error messages are crazy, I will write down details comments if we decide to use spirit to boost speed up.

**Comment by rcurtin** [comment]
It's worth considering that in the strategy I proposed, re-reading the file is a thing that will happen either very early on in the process, or not very much.  Basically the idea is, read in the file until we encounter something we can't cast to a double, then go back and re-read everything and convert that feature to categorical.  In the vast majority of datasets, this will happen very early on: I don't think there are many datasets that have 1M+ lines of valid numbers then suddenly a "hello".  So I think the performance will be fine, with the exception of crazy corner cases.

Another idea might be to scan through the entire file once, in order to determine which features are categorical, then go back to the beginning and re-scan the file.  But for large files I think the first approach might be faster.

I'm not familiar with boost::spirit, I'll go read a little bit about it later today.  For what it's worth, the mlpack compile-time error messages can already be pretty crazy (especially with serialization!). :)

**Comment by stereomatchingkiss** [comment]
>this will happen very early on: I don't think there are many datasets that have 1M+ lines of valid numbers then suddenly a "hello".

I guess you are right, ok, I will implement this strategy.Before I finish a faster, memory efficient version, could we treat this pull request as temporary solution?

**Comment by rcurtin** [comment]
Sure, I'll go ahead and merge this.  I've been reading a bit about Spirit, it seems very weird-looking, so please be sure to document thoroughly what everything does, so that some maintainer who doesn't know what Spirit is can have some idea of how the code works.

What version of Spirit are you planning to use?  I think we should stick with Spirit 2 (I guess 2.5 and up?) since that is available from Boost 1.47 onwards.

**Comment by stereomatchingkiss** [comment]
>I've been reading a bit about Spirit, it seems very weird-looking

I agree with you, learning curve is steep, but performance is very good

>so please be sure to document thoroughly what everything does

No problem.

>What version of Spirit are you planning to use?

2.5 and up

**Comment by stereomatchingkiss** [comment]
Hi, I use boost::spirit to implement the csv parser, it is more memory efficient and faster

spirit version : 

transpose : 2151 msec
non transpose : 4073 msec       

old version : 

transpose : 9616 msec
non transpose : 10131 msec

non transpose version is slower, I guess it is because arma::Mat is column wise.

**Pull request merged**
