### PR TITLE
Added support for multiple actions in action space for Soft Actor Critic

### PR DESCRIPTION
**Pull request by nishantkr18**
Missed an important update. This change will be required in the bipedal example.

### CODE REVIEW

**Comment by nishantkr18** [comment]
> Can we add a test for the changes as well?

I think this should work as a test. please have a look.

**Comment by nishantkr18** [comment]
> Looks good, let's see if the build comes back green.

Shall we get it merged. I'd like to try out BipedalWalker with SAC in examples :yum:

**Review by zoq — APPROVED** [review]
Looks great to me.

**Comment by zoq** [comment]
Awesome, thanks for another great contribution.

**Pull request merged**
