### PR TITLE
Added copy and move constructors to Linear3D Layer

### PR DESCRIPTION
**Pull request by RishabhGarg108**
In reference to #2625 
In this PR, I have added copy and move constructors to Linear3D layer, along with their corresponding tests.

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Looks good to me, thanks.

**Comment by jeffin143** [comment]
@RishabhGarg108 Can you fix the conflict and push ?

**Comment by RishabhGarg108** [comment]
@jeffin143 , can you please take a look again. I synced it with the latest master branch.

**Comment by jeffin143** [comment]
> @jeffin143 , can you please take a look again. I synced it with the latest master branch.

Once build passes I will merge thins in

Thanks for the contribution 👍

**Comment by RishabhGarg108** [comment]
Happy to contribute :)

**Comment by RishabhGarg108** [comment]
There are a lot of failing checks. Are they concerned to my PR or something else ?

**Comment by RishabhGarg108** [comment]
@jeffin143 @zoq , can we please get this one merged :-D. So that I don't have to resolve conflicts again and again :)

**Pull request merged**
