### PR TITLE
Attempt to Fix Azure pipeline

### PR DESCRIPTION
**Pull request by kartikdutt18**
Yet again, Python-2.7 MacOS build is failing python-bindings Ctest. This is an attempt to fix the same. At least I think the error is due to installing pandas. Reproduced this locally.
Thanks.

### CODE REVIEW

**Comment by kartikdutt18** [comment]
Might find something help here as [well](https://github.com/pandas-dev/pandas/issues/33035).

**Comment by kartikdutt18** [comment]
Hmm, This works does it also work without this?
Maybe the pandas fix, fixed this?

**Comment by kartikdutt18** [comment]
Okay so this does fail in new builds, reference tickets: [1](https://dev.azure.com/mlpack/mlpack/_build/results?buildId=1194&view=logs&j=1f0e5339-7d9e-540a-bfe0-fadee2eb16b9&t=020c88fb-1f83-5b5e-288a-72db9f1137d0) and [2](https://github.com/mlpack/mlpack/runs/535220389). Hey @favre49, I think this okay what do you think?

**Comment by favre49** [comment]
Thanks for looking into this and fixing it. I'm a bit confused though, what exactly is going wrong here? The logs say configparser 5.0.0 was installed, but errors due to not having it?

**Comment by kartikdutt18** [comment]
At least what I think is happening is that some library is installing configparser<3.5 which is causing the problem. Another solution might be to find the library and switch to a version that doesn't cause this issue but I think this is much simpler and would work without any problem.

**Comment by kartikdutt18** [comment]
Hmm, I agree but I think if azure gives us green builds I'm fine with it mainly because this won't effect the user.
Something even stranger is that I couldn't install pandas locally and it even failed on in this a36b0f7 commit however it automatically got fixed without any PR in pandas library. Not sure if this was a server issue but it was definitely strange for me.

**Comment by zoq** [comment]
Thanks, hopefully we don't have to touch the azure config every week.

**Comment by kartikdutt18** [comment]
I agree. I hope this the last fix for very long time.

**Pull request merged**
