### PR TITLE
Check Shape-Size in Random Forerst

### PR DESCRIPTION
**Pull request by AdarshSantoria**
This is to solve issue #2679.
As suggested in #3344, I have added check-shape size only in Random Forest in this pr.

### CODE REVIEW

**Comment by AdarshSantoria** [comment]
Hey @rcurtin, Can you please review this.

**Comment by AdarshSantoria** [comment]
Need review.

**Comment by rcurtin** [comment]
I am aware that it needs a review.  Please be patient---someone will review this when they are able to.  We all do this in our free time and have many other obligations too.

**Comment by AdarshSantoria** [comment]
keep open

**Pull request closed without merging**
