### PR TITLE
edge_boxes: feature extraction

### PR DESCRIPTION
**Pull request by nilayjain**
Feature extraction part of edge_boxes algorithm.

### CODE REVIEW

**Comment by nilayjain** [comment]
can armadillo be upgraded to a new version or should i add a new function for ind2sub ?

**Comment by stereomatchingkiss** [comment]
Thanks, this class is quite hard to implement. Will study your codes on next Thursday(9/6/2016).

**Comment by rcurtin** [comment]
`ind2sub()` and `sub2ind()` came in Armadillo 6.400, which in my opinion is too recent.  Ubuntu 14.04 (which many people are still using) still has Armadillo 4.200.  I think the better solution is just to backport `ind2sub()` and `sub2ind()` into `src/mlpack/core/arma_extend/`.  Basically this comes down to using preprocessor macros to detect the version and then including the function if the version is too old.  Take a look at `src/mlpack/core/arma_extend/typedef.hpp` to see an idea of what I mean (also `src/mlpack/core/arma_extend/arma_extend.hpp`).

**Comment by zoq** [comment]
Before I take a closer look at the code, it would be great if you could write some tests. This way, we can make sure everything works as expected even if we change something over time.

**Comment by nilayjain** [comment]
Seems like a good Idea, I will go ahead and do that.

**Pull request merged**
