### PR TITLE
Optimize load csv

### PR DESCRIPTION
**Pull request by stereomatchingkiss**
Hi, I use boost::spirit to implement the csv parser, it is more memory efficient and faster.

parse file with 1 million lines, 39796KByte

spirit version :

transpose : 2151 msec
non transpose : 4073 msec

old version :

transpose : 9616 msec
non transpose : 10131 msec

non transpose version is slower, I guess it is because arma::Mat is column wise.

Upload for code reviews, haven't integrate it into the load function and run the test cases yet.

ps : Single thread only, do not know multi-thread can make performance become better or worse, DataSetInfo is not a lock free data structure. If we want to utilize the power of multi-thread, I think we could read a bunch of string into the vector, create thread pool and DataSetInfo vectors, merge the DataSetInfo at last.

### CODE REVIEW

**Comment by stereomatchingkiss** [comment]
Why there are so many commits on this branch suddenly?

**Comment by keonkim** [comment]
@stereomatchingkiss hmm... did you amend it with the merge commit?

**Comment by rcurtin** [comment]
Someone force pushed to the repo and I am in the process of fixing it. That will fix this problem.

**Comment by stereomatchingkiss** [comment]
>@stereomatchingkiss hmm... did you amend it with the merge commit?

No, I only merge pull request(#650) one time.

>Someone force pushed to the repo and I am in the process of fixing it. That will fix this problem.

Thanks for the fix.

**Comment by stereomatchingkiss** [comment]
@rcurtin Would it make things easier to deal with if I delete this branch and open a new one?

**Pull request closed without merging**
