### PR TITLE
InceptionV3 (master branch)

### PR DESCRIPTION
**Pull request by hello-fri-end**
This is a follow up for #2848 which was built on ann-vtable branch and kept on crashing on my system. This PR builds the InceptionV3 layer from the master branch. All the inception modules & corresponding tests have been implemented. The test for all the modules pass except for Inception3B module where the assertion `REQUIRE (arma::accu(delta) == 0 )` fails. It seems there's some issue with the backward function of convolution layer but I'm unable to figure it out. Otherwise, this is ready for review @rcurtin @zoq.

PS: This may be helpful for reviewing.
[Pytorch Implementation of InceptionV3](https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py)

### CODE REVIEW

**Comment by zoq** [comment]
You are great, I'll test this out and see if I can reproduce the convolution issue.

**Comment by hello-fri-end** [comment]
Sounds great, thanks !

**Comment by zoq** [comment]
I was able to reproduce the issue, but I'm also not quite sure what the problem is, at least not yet.

**Comment by hello-fri-end** [comment]
I tried debugging the issue by  adding print statements in the code and found out at line 287 in `convolution_impl.hpp `([https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/ann/layer/convolution_impl.hpp#L287](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/ann/layer/convolution_impl.hpp#L287), when `output`is added to `gTemp.slice(inMap + batchCount * inSize) `, some garbage values are added ( maybe because of shape mismatch, not sure).

`output.print() ` before line 287:

>       
        0        0        0        0        0        0
        0        0        0        0        0        0
        0        0        0        0        0        0
        0        0        0        0        0        0
        0        0        0        0        0        0
        0        0        0        0        0        0

`gTemp.slice(inMap + batchCount * inSize).print()` before line 287:

> 
        0        0        0        0        0
        0        0        0        0        0
        0        0        0        0        0
        0        0        0        0        0
        0        0        0        0        0
 
`gTemp.slice(inMap + batchCount * inSize).print() `after line 287:

> 
            0            0            0            0            0  2.6512e-316
            0            0            0            0  6.3734e-322  4.9407e-324
            0            0            0            0            0  4.9407e-322
            0            0            0            0  2.6538e-316  1.5169e-154
            0            0            0            0  2.6383e-316   5.0149e-90
            0            0            0            0  2.6540e-316  6.9886e+228

**Pull request closed without merging**
