### PR TITLE
minor changes in comment

### PR DESCRIPTION
**Pull request by luffy1996**
Changing the comments to go inline with the initialisation .

### CODE REVIEW

**Comment by luffy1996** [comment]
I believe this commit doesn't have anything to do with build errors.

**Comment by luffy1996** [comment]
@zoq , Can you please check the errors.

**Comment by ShikharJ** [comment]
@luffy1996 As far as comment related changes are concerned, you can just reword the commit as 
```
[skip ci] minor changes....
```
That way, when you push, the CI builds will not be triggered.

**Comment by zoq** [comment]
Personally I don't use ``[skip ci]`` to keep the commit log cleaner. Anyway, no worries if a build fails for some unrelate reasons, there is no restriction that we can only merge if every build is green.

**Comment by luffy1996** [comment]
Thanks @rcurtin  , @zoq :)

**Comment by zoq** [comment]
Ok, with two approvals I will go ahead and merge this now. Thank you for the contribution! :)

**Pull request merged**
