### PR TITLE
Use CMAKE_CURRENT_SOURCE_DIR during files generation.

### PR DESCRIPTION
**Pull request by theranger**
I tried to use mlpack as a submodule of my project. Building such setup failed since some files were generated outside of mlpack source tree.

### CODE REVIEW

**Comment by rcurtin** [comment]
Ah, now I know the importance of the difference between `CMAKE_SOURCE_DIR` and `CMAKE_CURRENT_SOURCE_DIR`.  Thanks!

**Comment by rcurtin** [comment]
@theranger: Hey, I'm sorry I forgot about this when I merged this PR; I'd be happy to add your name to the list of authors in src/mlpack/core.hpp and COPYRIGHT.txt; would you want me to do that?  If so, let me know what name/email you'd like me to use.

**Comment by theranger** [comment]
Well, it was rather a minor change. But it would be fine by me. Please use Ivari Horm (ivari@risk.ee).

**Comment by rcurtin** [comment]
I set the cutoff at "more than 0 characters contributed to git master" to keep things simple, so, I've added your name to the contributors in 9f1d08a.  Thanks!  If you have any more issues feel free to submit more PRs. :)

**Pull request merged**
