### PR TITLE
Very minor style fix

### PR DESCRIPTION
**Pull request by sourabhvarshney111**
I have just done a very minor style fix which might cause other style builds to it.

### CODE REVIEW

**Comment by sourabhvarshney111** [comment]
@zoq @rcurtin You can merge it straightaway. It was just a small style fix.

**Comment by Prabhat-IIT** [comment]
Yes, a seperate commit like this is what I wanted for this fix otherwise it'll lead to commit duplication. @zoq after this merge all the style checks of recent prs can be fixed.

**Comment by zoq** [comment]
Thanks for the fix.

**Comment by sourabhvarshney111** [comment]
@zoq Welcome : )

**Pull request merged**
