### PR TITLE
NMF: allow user to specify one of initial W/H matrices

### PR DESCRIPTION
**Pull request by wenhaoh2**
This PR is follow-up of the discussion in #1261. It adds support to allow user to specify one of initial H/W matrices, and to randomly initialize the other one.

### CODE REVIEW

**Comment by Wenhao-H** [comment]
@zoq Thanks for the suggestion:) Actually there is a small difference between this implementation and what you meant. By this implementation, one of `W/H` matrix will be initialized randomly each time `Initialize()` is called. So if the same `GivenInitialization` instance is used multiple times, the randomly initialized matrices are different.
And to ensure I correctly understand, by combination of rules, do you mean that for example, `W` is initialized with existing `GivenInitialization` and `H` is initialized with existing `RandomInitialization`?

**Comment by zoq** [comment]
You are right, I thought about ``GivenInitialization`` as a one time initialization rule.

About the merge idea, you are right, my only concern is, right now each rule will initialize W and H,  maybe the performance in this case is negligible.

**Comment by Wenhao-H** [comment]
@zoq that's a good idea. What I have in mind is to use a class which takes two Initialization Rules as template parameters, and initialize `W` with the first and `H` with the second.
```C++
template<typename WInitializationRuleType, typename HInitializationRuleType>
class MergeInitializaition
{
  // ...
};
```
I think the performance overhead is negligible, compared to the time used to compute the iterations.
But my only concern is that this might not be a common usage.

**Comment by Wenhao-H** [comment]
I'm sorry for the late reply because I have been writing my bachelor thesis. I will refactor the code to  the `MergeInitialization` idea once I finish the thesis, which may take a week or so:)

**Comment by zoq** [comment]
Sounds good, hopefully you have some fun to finish the last part of your thesis.

**Pull request closed without merging**
