### PR TITLE
Camel Case updates to fix #902

### LINKED ISSUE #902: Upper Camel Case
As I implemented the first activation function in ``src/mlpack/methods/ann/activation_functions`` I used Lower Camel Case for the function names instead of Upper Camel Case as used throughout the codebase and as stated in the design guidelines: https://github.com/mlpack/mlpack/wiki/DesignGuidelines

The goal of this ticket is to find and to replace them with the correct style:

```
fn -> Fn
deriv -> Deriv
inv -> Inv
```

### PR DESCRIPTION
**Pull request by sam0410**
These are for issue #902 
fn to Fn
deriv to Deriv
inv to Inv

### CODE REVIEW

**Comment by sam0410** [comment]
Hi!
changed all instances of 'inv','deriv' and 'fn' in activation function
I'll be pulling another request after changing all instances in the tests.

**Comment by sam0410** [comment]
Hi !
I updated the activation functions as well as activation tests

**Comment by sam0410** [comment]
Hi !
This is now ready to be merged. 
Thanks!

**Comment by sam0410** [comment]
Hi @zoq !
Actually I was thinking, what is wrong in the code in my pull request? Because, it has been 3 days, u haven't reviewed it yet.

**Comment by zoq** [comment]
I think since you closed this issue once, I missed it somehow. Anyway, I checked the issue and you were the first who created the PR, so checking this now, so that we can merge it.

**Comment by zoq** [comment]
Could you also take a look at the elu.hpp and elu_impl.hpp file?

**Comment by sam0410** [comment]
Thanks @zoq !
Yes, It is done.

**Comment by zoq** [comment]
Thanks for looking into the issue. Would you like to add your name to the list of contributors in src/mlpack/core.hpp and COPYRIGHT.txt before I merge the code?

**Comment by sam0410** [comment]
Thanks @zoq !
I'll write my name after I work on more advanced issues. This one was trivial.
Thanks again!

**Comment by gaurav1024** [comment]
Hi @zoq !
Is this issue still open. Are there any more files I can look into?

**Comment by zoq** [comment]
@gaurav1024 All files are covered.

**Comment by zoq** [comment]
Thanks again for the contribution, looking forward to take a look at the next contribution.

**Pull request merged**
