### PR TITLE
Document `MeanSplitBallTree`

### PR DESCRIPTION
**Pull request by rcurtin**
The diff on this won't look right until #3802 is merged---but I just added documentation for `MeanSplitBallTree` in basically the exact same way I did for `MeanSplitKDTree` in #3801.

### CODE REVIEW

**Comment by shrit** [comment]
These docs are good, I pulled the link from Jenkins to see. I would say that the only comment that I have is related to having the default template parameters mentioned (same comment for Ball Tree and Ball bound). Once they are merged I can approve this if no modifications 👍

**Comment by shrit** [comment]
I did not approve it so it does not get merged accidentally 👍

**Comment by shrit** [comment]
could you solve the conflict here so I can merge it ?

**Comment by rcurtin** [comment]
Fixed now.  Also I realized the bits I put for default template parameters of `BallTree` was in the wrong place; so I moved it to the right place, and also added that language to the other trees (`KDTree` and `MeanSplitKDTree`).

**Review by shrit — APPROVED** [review]
I think the CI error is not related to the docs, probably armadillo website was down for a couple of minutes

**Comment by rcurtin** [comment]
Agreed, and I saw the documentation build pass earlier so I will merge. The Go build should be fixed in #3807.

**Pull request merged**
