### PR TITLE
AtrousConvolutionLayer stablize test

### PR DESCRIPTION
**Pull request by zoq**
Let's test out some solutions.

### CODE REVIEW

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by ShikharJ** [comment]
@rcurtin It feels kinda weird for me as well to think that, but I was unable to find a bug in the Atrous Convolution code (might be because I had a hand in it's implementation)? Anyways, I'm glad we found a fix.

**Comment by ShikharJ** [comment]
@zoq Please feel free to merge this in if you feel this is complete.

**Comment by zoq** [comment]
Agreed, this shouldn't be the final solution for the issue. On my system, the previous implementation fails in 1/10, so this isn't really easy to track down. Anyway, I will keep this on my list, but I think it makes sense to merge this in, for now, to avoid confusions in other PRs.

**Pull request merged**
