### PR TITLE
Allow  to build dlls

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by xantares** [comment]
@rcurtin The import lib is not created, I guess it's not that magical after all.
```
[00:08:35] Link:
[00:08:35]   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\projects\mlpack\build\Release\mlpack.dll" /INCREMENTAL:NO /NOLOGO /LIBPATH:C:/projects/mlpack/boost_libs /LIBPATH:C:/projects/mlpack/boost_libs/Rele
[00:08:35] ase kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib ..\..\..\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a ..\..\..\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a ..\..\.
[00:08:35] .\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a ..\..\..\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/projects/mlpack/build/Release/mlpack.pdb" /SUBSYST
[00:08:35] EM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/projects/mlpack/build/Release/mlpack.lib" /MACHINE:X64  /machine:x64 /DLL mlpack.dir\Release\discrete_distribution.obj
[00:08:35]   mlpack.dir\Release\gaussian_distribution.obj
[00:08:35]   mlpack.dir\Release\laplace_distribution.obj
...
[00:08:35]   mlpack.dir\Release\maximal_inputs.obj
[00:08:35]   mlpack.dir\Release\sparse_coding.obj
[00:08:35]   mlpack.vcxproj -> C:\projects\mlpack\build\Release\mlpack.dll
[00:08:35] FinalizeBuildStatus:
[00:08:35]   Deleting file "mlpack.dir\Release\mlpack.tlog\unsuccessfulbuild".
[00:08:35]   Touching "mlpack.dir\Release\mlpack.tlog\mlpack.lastbuildstate".
[00:08:35] Done Building Project "C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj" (default targets).
[00:08:35] Done Building Project "C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj.metaproj" (default targets).
[00:08:35] The target "_ConvertPdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)" does not exist in the project, and will be ignored.
[00:08:35] The target "_CollectPdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)" does not exist in the project, and will be ignored.
[00:08:35] The target "_CollectMdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,38)" does not exist in the project, and will be ignored.
[00:08:35] The target "_CopyMdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,71)" does not exist in the project, and will be ignored.
[00:08:35] Project "C:\projects\mlpack\build\ALL_BUILD.vcxproj.metaproj" (2) is building "C:\projects\mlpack\build\src\mlpack\methods\adaboost\mlpack_adaboost.vcxproj.metaproj" (12) on node 1 (default targets).
[00:08:35] Project "C:\projects\mlpack\build\src\mlpack\methods\adaboost\mlpack_adaboost.vcxproj.metaproj" (12) is building "C:\projects\mlpack\build\src\mlpack\methods\adaboost\mlpack_adaboost.vcxproj" (13) on node 1 (default targets).
[00:08:35] PrepareForBuild:
[00:08:35]   Creating directory "mlpack_adaboost.dir\Release\".
[00:08:35]   Creating directory "mlpack_adaboost.dir\Release\mlpack_adaboost.tlog\".
[00:08:35] InitializeBuildStatus:
[00:08:35]   Creating "mlpack_adaboost.dir\Release\mlpack_adaboost.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[00:08:35] CustomBuild:
[00:08:35]   Building Custom Rule C:/projects/mlpack/src/mlpack/methods/adaboost/CMakeLists.txt
[00:08:35]   CMake does not need to re-run because C:\projects\mlpack\build\src\mlpack\methods\adaboost\CMakeFiles\generate.stamp is up-to-date.
[00:08:35] ClCompile:
[00:08:35]   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /I"C:\projects\mlpack\armadillo-6.500.5\include" /IC:\projects\mlpack\boost.1.60.0.0\lib\native\include /IC:\projects\mlpack /IC:\projects\mlpack\src\mlpack\.. /nologo /W3 /WX
[00:08:35] - /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D ARMA_NO_DEBUG /D NDEBUG /D BOOST_TEST_DYN_LINK /D MLPACK_GIT_VERSION /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /Fo"mlpack_adaboost.dir\
[00:08:35] Release\\" /Fd"mlpack_adaboost.dir\Release\vc140.pdb" /Gd /TP /errorReport:queue  -O3 C:\projects\mlpack\src\mlpack\methods\adaboost\adaboost_main.cpp
[00:08:36] cl : Command line warning D9002: ignoring unknown option '-O3' [C:\projects\mlpack\build\src\mlpack\methods\adaboost\mlpack_adaboost.vcxproj]
[00:08:36]   adaboost_main.cpp
...
[00:10:11] c:\projects\mlpack\src\mlpack\core\tree\rectangle_tree\r_tree_split_impl.hpp(468): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\projects\mlpack\build\src\mlpack\methods\neighbor_search\mlpack_allkfn.vcxproj]
[00:10:13] Link:
[00:10:13]   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\projects\mlpack\build\Release\mlpack_allkfn.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:C:/projects/mlpack/boost_libs /LIBPATH:C:/projects/mlpack/boost_li
[00:10:13] bs/Release kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib ..\..\..\..\Release\mlpack.lib ..\..\..\..\..\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a /MANIFEST /MANIFESTUAC:"lev
[00:10:13] el='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/projects/mlpack/build/Release/mlpack_allkfn.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/projects/mlpack/build/Release/mlpack_allkfn.lib" /MACHINE:X64  /machine:x64 mlpack_all
[00:10:13] kfn.dir\Release\allkfn_main.obj
[00:10:13] LINK : fatal error LNK1181: cannot open input file '..\..\..\..\Release\mlpack.lib' [C:\projects\mlpack\build\src\mlpack\methods\neighbor_search\mlpack_allkfn.vcxproj]
[00:10:13] Done Building Project "C:\projects\mlpack\build\src\mlpack\methods\neighbor_search\mlpack_allkfn.vcxproj" (default targets) -- FAILED.
```

**Comment by xantares** [comment]
@rcurtin, optimization flags set in CMakeLists are not supported by all compilers, use
https://cmake.org/cmake/help/v3.0/module/CheckCXXCompilerFlag.html?highlight=checkcxxcompiler#module:CheckCXXCompilerFlag
instead of guessing:
if(CMAKE_COMPILER_IS_GNUCC OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")

```
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -O3")
```

**Comment by xantares** [comment]
@rcurtin, what about this less invasive change using CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ?
only a few static variables are treated using dllexport

**Comment by rcurtin** [comment]
This definitely looks better.  There are few static variables and I don't expect to add anymore anytime soon, and it's certainly not something that a typical maintainer/contributor would need to do.  I want to do a little research to understand whether or not we can make CMake automatically export static variables too, so let me do some reading and get back to you.

**Comment by rcurtin** [comment]
Yeah, I did a little reading and neither @zoq nor I can easily come up with a better solution, so I think this is the best way to go.  I added a little documentation in 7264d37.  Thanks for the contribution!

**Pull request merged**
