### PR TITLE
Remove strange characters situated at the end of each line

### PR DESCRIPTION
**Pull request by shrit**
I can not see what are these chars, but they are detect by kakoune
and represented by a strange question mark. So I am removing them.

Signed-off-by: Omar Shrit <omar@shrit.me>

### CODE REVIEW

**Comment by shrit** [comment]
2020-11-25-231316_1366x768_scrot
To give an idea this what my screen looks like having hundreds of small candles,

**Review by rcurtin — APPROVED** [review]
Oh, those are Windows line endings, not Unix line endings:

```
$ file load_image_impl.hpp 
load_image_impl.hpp: C++ source, ASCII text, with CRLF, LF line terminators

$ file load_impl.hpp
load_impl.hpp: C++ source, ASCII text
```

You can also fix this type of thing with the `dos2unix` utility. :+1:

**Review by zoq — APPROVED** [review]
Nice catch!

**Comment by shrit** [comment]
I have reiterated the entire mlpack code base, nothing left. :+1:

**Pull request merged**
