### PR TITLE
Remove matlab references

### PR DESCRIPTION
**Pull request by NippunSharma**
Removing matlab references.

### CODE REVIEW

**Comment by NippunSharma** [comment]
I have found some more references:
`doc/guide/bindings.hpp`, `src/mlpack/hmm/hmm_impl.hpp`, `src/mlpack/methods/sparse_coding/sparse_coding.cpp`,
`src/mlpack/tests/hmm_test.cpp`, `src/mlpack/tests/maximal_inputs_test.cpp`, `src/mlpack/test/pca_test.cpp`

should I remove these too ?

**Comment by zoq** [comment]
> I have found some more references in the following files:
> `doc/guide/bindings.hpp`, `src/mlpack/hmm/hmm_impl.hpp`, `src/mlpack/methods/sparse_coding/sparse_coding.cpp`,
> `src/mlpack/tests/hmm_test.cpp`, `src/mlpack/tests/maximal_inputs_test.cpp`, `src/mlpack/test/pca_test.cpp`
> 
> should I remove these references too ?

No, this are notes about how the line/code differs from MATLAB, which is there to help to understand the method if you are familiar with MATLAB.

**Review by zoq — APPROVED** [review]
Nice catch :+1:

**Review by shrit — APPROVED** [review]
Nice catch

**Pull request merged**
