### PR TITLE
Fixed whitespace bug and adjusted whitepace

### PR DESCRIPTION
**Pull request by atulim**
I have made two changes - 

(1) Solved again an extra whitespace bug.
(2) Adjusted whitespace according to documentation rules. Although this change doesn't affect the output but it was not according to documentation rules.

### CODE REVIEW

**Comment by atulim** [comment]
@rcurtin Sir, are you back from vacay ? I've got to ask an important question.

**Comment by rcurtin** [comment]
Yes, I am back.

**Comment by atulim** [comment]
Sir,

Sorry to ask a foolish question.

But being a competitive programmer, I want to design ML C++ programs so that they can be added into your library. How do I start? From where do I get relevant papers to read?

**Comment by rcurtin** [comment]
The resources we have available for getting started with mlpack can be found at http://www.mlpack.org/involved.html and maybe http://www.mlpack.org/gsoc.html is useful too.  But those don't have very much information about how to become knowledgeable in machine learning.  For that I might suggest finding an online course to take or book to read.  One courseight be Andrew Ng's Coursera course (it is very popular) and a good book might be 'AI: A Modern Approach'.  I hope that this is helpful. :)

**Comment by zoq** [comment]
@atulim just wanted to check in, were you still planning to handle the other whitespace changes? If not I can do it, just let me know.

**Comment by atulim** [comment]
Yes sir. I m currently busy bcoz of my exams. I will start fixing them from
next week.

**Comment by zoq** [comment]
@atulim Sounds good; good luck with your exams.

**Comment by ShikharJ** [comment]
@atulim Any update? If you're busy, we can handle the rest of the cases, and get this merged in.

**Comment by ShikharJ** [comment]
Thanks @atulim for the contribution!

**Pull request merged**
