### PR TITLE
add a test case for max-cut

### PR DESCRIPTION
**Pull request by stephentu**
this is just a random graph, and I verified the objective function with mosek.

### CODE REVIEW

**Comment by rcurtin** [comment]
The test itself looks great to me, but after checking out your branch and building the test I get the following output:

```
...
[WARN ] Penalty is 3.50223e-20 (threshold 1.93732e-20).
[WARN ] Updated sigma to 2e+06.
[WARN ] AugLagrangian on iteration 16, starting with objective -1.2748.
[DEBUG] L-BFGS iteration 0; objective -3672.74.
[DEBUG] Line search failed.  Terminating optimization.
/home/ryan/src/stephentu/mlpack/src/mlpack/tests/lrsdp_test.cpp(181): fatal error in "ErdosRenyiRandomGraphMaxCutSDP": difference{99.9653%} between finalValue{-1.274800020898166} and -3672.7{-3672.6999999999998} exceeds 0.10000000000000001%

*** 1 failure detected in test suite "MLPACKTest"
```

I'm actually on the road right now (figuratively, not literally) so I can't dig deeper into what's going on here, but the L-BFGS objective seems to be correct, but what's being returned by AugLagrangian isn't right.  I'll dig deeper if I have a chance in the next couple of days, but I did want to at least express that people don't often like to write test cases, so I really appreciate it.  I'm glad to see this LRSDP code finally be useful!  (Or, getting close to there, at least. :))

**Comment by stephentu** [comment]
Oops, I think this commit actually depends on #371, which I had locally when I tested it, but removed it for self contained pull requests. Since #371 is now merged upstream, I've corrected the issue. Should work now *fingers crossed*.

**Comment by rcurtin** [comment]
Outside of that comment, everything looks great, the test runs pretty quickly in debug and non-debug mode, so I'll merge it once that's addressed.  Also, I added you as a contributor (which I should have done earlier but forgot) in 1ab6257.

**Comment by stephentu** [comment]
the random value is out of laziness-- I was trying to find a starting point that wasn't just 11^T. 

i'll change it to something deterministic or add the starting point to a file+load.

**Comment by stephentu** [comment]
ok, I don't really have a good justification for this new starting point, other than it is feasible and deterministic

**Comment by rcurtin** [comment]
Great, merged!

**Pull request merged**
