### PR TITLE
Merge layer run parameter.

### PR DESCRIPTION
**Pull request by zoq**
This introduces the run parameter for the merge layer; if set the merge layer forwards the Forward/Backward/Gradient call. This enables us to use the FFN/RNN class to merge sub-networks.

Here is an example:

```c++
// Create a simple pseudo input/output pair.
arma::mat input = arma::randn(10, 1);
arma::mat target;
target.ones(1, 256);

// User sub-network.
Sequential<>* userModel = new Sequential<>();
userModel->Add<Linear<> >(10, 2);

// Item sub-network.
Sequential<>* itemModel = new Sequential<>();
itemModel->Add<Linear<> >(10, 2);

// Merge the user and item sub-network.
MultiplyMerge<> mergeModel(true, true);
mergeModel.Add(userModel);
mergeModel.Add(itemModel);

// Create the main network.
FFN<NegativeLogLikelihood<>, RandomInitialization> network;
network.Add<IdentityLayer<> >();
network.Add<MultiplyMerge<> >(mergeModel);
network.Add<IdentityLayer<> >();
network.Add<Linear<> >(2, 2);
network.Add<SigmoidLayer<> >();
network.Add<LogSoftMax<> >();

// Set some simple input/output data.
network.Predictors() = input;
network.Responses() = target;

// Gradient internally calls the Evaluate method.
arma::mat gradient;
// network.Evaluate(network.Parameters(), 0, 1);
network.Gradient(network.Parameters(), 0, gradient, 1);
```

### CODE REVIEW

**Comment by haritha1313** [comment]
That was a nice way to solve the issue :D. I have a few doubts though. Is there any reason the target matrix has been set to (1, 256) in the example you gave? I tried to perform network.Train() and am getting out of bounds. You invoked the gradient function manually so is there anything I am missing?

**Comment by zoq** [comment]
There is no good reason to set the ``target`` to ``(1, 256)`` and the input to ``(10, 1)``, note the second parameter are the number of samples. And I think the different number of samples is the issue here.

Here is the correct example:

```c++
// Create a simple pseudo input/output pair.
arma::mat input = arma::randn(10, 2);
arma::mat target;
target.ones(1, 2);

// User sub-network.
Sequential<>* userModel = new Sequential<>();
userModel->Add<Linear<> >(10, 2);

// Item sub-network.
Sequential<>* itemModel = new Sequential<>();
itemModel->Add<Linear<> >(10, 2);

// Merge the user and item sub-network.
MultiplyMerge<> mergeModel(true, true);
mergeModel.Add(userModel);
mergeModel.Add(itemModel);

// Create the main network.
FFN<NegativeLogLikelihood<>, RandomInitialization> network;
network.Add<IdentityLayer<> >();
network.Add<MultiplyMerge<> >(mergeModel);
network.Add<IdentityLayer<> >();
network.Add<Linear<> >(2, 2);
network.Add<SigmoidLayer<> >();
network.Add<LogSoftMax<> >();

// Set some simple input/output data.
network.Predictors() = input;
network.Responses() = target;

// Gradient internally calls the Evaluate method.
arma::mat gradient;
// network.Evaluate(network.Parameters(), 0, 1);
// network.Gradient(network.Parameters(), 0, gradient, 1);

network.Train(input, target);
```

About using the ``Gradient(...)`` function over the ``Train(...)``, just copied the step from the test above which does a Gradient check 😄

**Comment by zoq** [comment]
Let me know if this works for you.

**Comment by haritha1313** [comment]
Yes, adjusting sample size did solve the problem. And this works perfectly! :) . I think once I make the subview layer PR tomorrow (tests remain to be written), we will be closer to having the `CreateModel` method for `NCF` ready.

**Comment by zoq** [comment]
Agreed, excited to get that part done.

**Comment by zoq** [comment]
I'll let this sit for 2 days before I'll merge this in, to give anyone else a chance to take a look at the code.

**Pull request merged**
