### PR TITLE
Make sure feedforward_network_2_test.cpp gets compiled and run.

### PR DESCRIPTION
**Pull request by rcurtin**
I noticed while reviewing #2844 that this file actually isn't being compiled and run in the tests.  The PR is an easy fix. :)

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Easy to review as well :+1:

**Review by birm — APPROVED** [review]

**Comment by jeffin143** [comment]
This was my blundered, while migrating I might have missed to add it to new

**Comment by jeffin143** [comment]
Sorry

**Comment by rcurtin** [comment]
No worries!  It was an easy fix. :)

**Pull request merged**
