### PR TITLE
Fix random seed for tests

### PR DESCRIPTION
**Pull request by robertohueso**
I'm not sure if this is right but as far as I have tested seems fine, looking forward for your feedback :smile: 
Issue #1227

### CODE REVIEW

**Comment by ShikharJ** [comment]
@robertohueso Welcome to mlpack! It looks like you have opened a PR for an issue that is already being worked upon by @Prabhat-IIT in #1236. I think it might be worthwhile to talk to him before continuing to work on this :)

**Comment by Prabhat-IIT** [comment]
@robertohueso have you tested this fix? I've tried this already and it didn't work for me because `RandomSeed()` is not being called from `mlpack_preprocess_split` in this case. Please ensure that `RandomSeed()` is being called from `mlpack_preprocess_split` and not being called from `preprocess_split_test` either through debugging or by printing on the command line.

**Comment by robertohueso** [comment]
@ShikharJ Thank you! I didn't notice :)
@Prabhat-IIT I have been testing today and it's true it's not being called from `mlpack_preprocess_split`. Seems like `mlpack_preprocess_split` "BINDING_TYPE" is "BINDING_TYPE_TEST".
1. It should be "BINDING_TYPE_CLI " right?
2. Should we open another issue?

**Comment by Prabhat-IIT** [comment]
@robertohueso  there's a Macro conflict here!! I'll fix it after 3 days after my exams are over.

**Comment by rcurtin** [comment]
Hi @robertohueso, can you reopen this PR?  I glanced at the code (it appears to be gone now) and if I am remembering the code correctly, this is the right way to solve the issue.  So if you can reopen this, we can figure out if it is working correctly and go from there.  Thanks!

**Pull request closed without merging**
