### PR TITLE
Resolve Julia Binding Failure

### PR DESCRIPTION
**Pull request by Yashwants19**
In Azure Pipeline Julia binding is failing. This PR is a try resolve the failure.

### CODE REVIEW

**Comment by rcurtin** [comment]
Hey @yashwants19, thanks for looking into this.  I'm currently working on a patch, so I'll also open a PR shortly. :+1:  (For some reason the Julia binding PR did not actually run tests on Azure and I didn't notice when I merged :(... second merge failure in two days on my part, maybe I need to have a close look at my life or something :smile:)

**Comment by walragatver** [comment]
This PR is passing the MacOS build. Nice work :+1:

**Comment by jeffin143** [comment]
@Yashwants19 , how many languages do you know ?

**Comment by rcurtin** [comment]
I opened #2283, which should have a fix that works. :+1:

**Comment by Yashwants19** [comment]
Hi @rcurtin #2283 is looking great. I think so I must close this PR because our purpose is solving there. And for macOS build please take a look at #2278.

**Comment by Yashwants19** [comment]
> This PR is passing the MacOS build. Nice work

Thank you @walragatver.

**Comment by Yashwants19** [comment]
> @Yashwants19 , how many languages do you know ?

I know C++, python, octave, go and little bit of java. I had studied julia when I was working on my GSOC proposal so as to become familiar with mlpack bindings. :)

**Comment by Yashwants19** [comment]
Closing as our purpose is solving in #2283.

**Pull request closed without merging**
