### PR TITLE
Fix style issues

### PR DESCRIPTION
**Pull request by rcurtin**
I noticed in #2964 that there are a bunch of style checks that are failing.  I tried to fix them in this PR---let's see how successful I was. :)

### CODE REVIEW

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
I use the PR to check the cross-compilation job, hope that is fine.

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
Sounds good to me! :+1:

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Review by zoq — APPROVED** [review]
Looks great to me.

**Comment by shrit** [comment]
@mlpack-jenkins test this please

**Comment by shrit** [comment]
Great, CrossCompilation check is working :+1:

**Comment by shrit** [comment]
@rcurtin, this pull request seems to be cool,  I am really interested to know what tool did you use in order to find all these style errors.
PS: I will try to give it a look tomorrow if it is not too late, I do not have any neurons left to handle it today.

**Comment by rcurtin** [comment]
I have no idea actually---Marcus set up the style checks job, and I just used the output from it and manually fixed everything. :)

**Comment by zoq** [comment]
We use cpplint for the style checks, you can find the script here - https://github.com/mlpack/jenkins-conf/tree/master/linter

**Review by shrit — APPROVED** [review]
Great, pull request, thanks. :+1:

**Pull request merged**
