### PR TITLE
Update RcppArmadillo header locations

### PR DESCRIPTION
**Pull request by eddelbuettel**
As detailed in [issue #400 in the RcppArmadillo repo](https://github.com/RcppCore/RcppArmadillo/issues/400) we would like to (re)move some internal header files. `mlpack` is one of very few packages directly accessing one of these, and this PR suggests a simple way to at least access the new locations of these. (It would be preferable to only include RcppArmadillo.h. I did not see an immediate way but I didn't look hard or long and could try to help some more team mlpack is interested too; but maybe the class declaration are nested away too far down.)

With this PR, the package should still builds and check cleanly, though Actions seem currently borked. It would be lovely if you could consider this, possible merge this and get an updated version to CRAN in the next few months. If you do so, please leave a comment to at the linked issue so that we can keep track. Thanks for your consideration, and please don't hesitate to ask if anything seems unclear.

### CODE REVIEW

**Review by rcurtin — COMMENTED** [review]
The code changes all seem fine to me here.  Let's merge these changes, and then they'll be part of the 4.0.1 release.  However I do have a couple quick questions:

 * Should we wait until a new version of RcppArmadillo is on CRAN to upload the new version of mlpack to CRAN?  What will that version number be / can you notify us when that happens?

 * Do the new header files already exist in RcppArmadillo as packaged on CRAN?  (That is, will this compile as things currently stand for RcppArmadillo in CRAN?)

 * Any idea about the Github actions problem?  It seems related to maybe something that is linked inside of R: `libicui18n.so.66: cannot open shared object file: No such file or directory`.  I also saw it on another branch, so it's not specific to the code here.

**Comment by eddelbuettel** [comment]
Yes, that is a most excellent question. It likely does need a versioned depends.  I omitted that because of the four (one is a double count) repos I contacted only one moves at non-glacial speed :)   Kidding aside mlpack is big.

Other than CRAN, is there another place where we could shoot ourselves in the foot doing this?  All other builds co-update dependencies as they should?   The 'more ideal' solution would of course be to not much with the internal headers and just pull (only) RcppArmadillo.h but here (and for pense) that is not a one shot fix.  We may 'eventually' want to shimmy a converter package in between, or do it differently.  For mlapck 5.0.0 that is...

**Comment by eddelbuettel** [comment]
The current version at CRAN (now at 0.11.4.2.1) should be good enough. Here is eg the RNG alternate in its new location: https://github.com/cran/RcppArmadillo/tree/master/inst/include/RcppArmadillo/rng

**Comment by eddelbuettel** [comment]
So as for your three questions:

- CRAN is current
- It should build as is
- The libicu issue happens when package `stringi` gets out of whack with libicu, I have seen that happen.

My neat new project this year was a better, fully complete and fully system-dependency-integrated repository of _all of CRAN_ as .deb binaries:  https://eddelbuettel.github.io/r2u/.  I switched my CI to it, but I will not / should not impose that here.  I just mention it as 'yup, seen that before and can be a cost of a wider net of dependencies'.

**Review by rcurtin — APPROVED** [review]
Thanks for the clarifications.  In that case everything looks good here to me.

The primary reason I asked is that there could exist users who are hand-compiling the R bindings to create a package they can then install locally, so that they have the newest version.  Probably nobody is actually doing that, but, since the RcppArmadillo version in CRAN supports these updates, then even if anyone *was* doing that it should work fine. :)

**Comment by eddelbuettel** [comment]
Regarding the CI failure:  As mentioned, others will be more familiar with the particular choice of R-related actions and what aspects for example the cache may have.  Package `stringi` is out of what with the ICU library version, that may come from the cache.

I could suggest a few short-term fixes/workarounds.  As that is Ubuntu 22.04 (which I run here) you could try to inject / force `r-cran-stringi` which, while behind the 1.7.8 version at CRAN would at least be consistently built and (as installed by `apt`) bring in its ICU version 70.

<details

```sh
edd@rob:~$ apt-cache show r-cran-stringi
Package: r-cran-stringi
Architecture: amd64
Version: 1.7.6-1build1
Priority: optional
Section: universe/gnu-r
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian R Packages Maintainers <r-pkg-team@alioth-lists.debian.net>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1356
Depends: r-base-core (>= 4.1.2-1ubuntu2), r-api-4.0, libc6 (>= 2.29), libgcc-s1 (>= 3.0), libicu70 (>= 70.1-1~), libstdc++6 (>= 11)
Filename: pool/universe/r/r-cran-stringi/r-cran-stringi_1.7.6-1build1_amd64.deb
Size: 823310
MD5sum: 189c99484a552a67f15fa6c0e89f8ede
SHA1: b8f8504248a47d513ec09f495d3e8e9a7a5cf20d
SHA256: f2c42204ac8d63b00c513d8cdd7a25d5844533c4efe92c2f901d347a469c39fb
SHA512: df65f8b7aafafe3d5d4ce815bf157ad2d0de24a5af79ef5ff64e0ab96d047d7994e57f0730298330156b0b027f3ecb4a4c37cbe5c4d97631725c2caa27800ee0
Homepage: https://cran.r-project.org/package=stringi
Description-en: GNU R character string processing facilities
 Allows for fast, correct, consistent, portable, as well as convenient
 character string/text processing in every locale and any native
 encoding. Owing to the use of the ICU library, the package provides R
 users with platform-independent functions known to Java, Perl, Python,
 PHP, and Ruby programmers. Among available features there are: pattern
 searching (e.g. via regular expressions), random string generation,
 string collation, transliteration, concatenation, date-time formatting
 and parsing, etc.
Description-md5: 85ac5a24c94e62cafa0b0d03553977b0

edd@rob:~$ 

</details>

**Comment by rcurtin** [comment]
Honestly I was going to take the no-effort approach and let the problem resolve itself over time.

**Comment by eddelbuettel** [comment]
Yes it should indeed be transient --but maybe in the space of months? I just want to make sure it ... won't block a merge?

**Review by Yashwants19 — APPROVED** [review]
Looks good to me as well. Thanks @eddelbuettel 
 for all changes.

**Pull request merged**
