### PR TITLE
Addition of Mean Absolute Percentage Error

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
Addition of mean absolute percentage error in loss_functions

### CODE REVIEW

**Comment by Aakash-kaushik** [comment]
Hi @zoq this PR replaces #2603

**Review by kartikdutt18 — COMMENTED** [review]
Looks good to me. Thanks a lot for working on this. 👍

**Review by zoq — APPROVED** [review]
Yep, looks good to me as well, thanks again for the contribution.

**Review by birm — APPROVED** [review]

**Comment by Aakash-kaushik** [comment]
Hey, should i include this change is HISTORY.md ?

**Comment by kartikdutt18** [comment]
Yes, that would be a good idea.

**Comment by kartikdutt18** [comment]
Thanks @Aakash-kaushik for the contribution.

**Pull request merged**
