### PR TITLE
creates ModeImputation class

### PR DESCRIPTION
**Pull request by greatsharma**
I created a mode_imputation.hpp containing ModeImputation class. The Impute function searches through the input looking for mappedValue and replaces it with the mode of the given dimension. The result is overwritten to the input matrix. The purpose of this class is to impute mode for voids in the data just like we did for other imputation methods like mean and median.

I also added the test for ModeImputation in imputation_test.cpp.

### CODE REVIEW

**Comment by greatsharma** [comment]
@ShikharJ  please preview this

**Comment by rcurtin** [comment]
This has no tests and isn't integrated with any other parts of the mlpack codebase.  If we want to add new support for new features, then we have to also make sure that new feature is available for users of mlpack.  Can you please spend some time doing those two things?  Thanks.

**Comment by greatsharma** [comment]
> 
> 
> This has no tests and isn't integrated with any other parts of the mlpack codebase. If we want to add new support for new features, then we have to also make sure that new feature is available for users of mlpack. Can you please spend some time doing those two things? Thanks.

Yes sure I will.

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Can you remove the non imputation related changes from the PR.

**Comment by greatsharma** [comment]
> 
> 
> Can you remove the non imputation related changes from the PR.

@zoq I removed all unnecessary changes and also added the test corresponding to ModeImputation in imputation_test.cpp.

**Comment by greatsharma** [comment]
> This has no tests and isn't integrated with any other parts of the mlpack codebase. If we want to add new support for new features, then we have to also make sure that new feature is available for users of mlpack. Can you please spend some time doing those two things? Thanks.

@rcurtin I added the test for this new feature in this PR

**Comment by greatsharma** [comment]
> 
> 
> Can you remove the non imputation related changes from the PR.

@zoq can you please review this PR, is their anything wrong with this PR or the changes I made.

**Comment by rcurtin** [comment]
Closing for inactivity.

**Pull request closed without merging**
