### PR TITLE
Implemented Atrous Convolution

### PR DESCRIPTION
**Pull request by aarushgupta**
This PR adds Atrous(Dilation) Convolution as mentioned in this [paper](https://arxiv.org/pdf/1511.07122.pdf). There are some doubts regarding it. I will add the tests after their clarification and necessary changes.

### CODE REVIEW

**Comment by rcurtin** [comment]
Hi there,

This doesn't compile.  Can you handle that (and the other build issues) please?

**Comment by aarushgupta** [comment]
Yes, I will look into it.

**Comment by aarushgupta** [comment]
Yes, I will look into it.

**Comment by ShikharJ** [comment]
@aarushgupta I'd like to complete this if you don't mind?

**Comment by zoq** [comment]
Agreed, thanks @ShikharJ and @aarushgupta for the hard work.

**Pull request closed without merging**
