### PR TITLE
Cnn work around

### PR DESCRIPTION
**Pull request by stereomatchingkiss**
Use work around to fix the compile time error of vc2015(this fix could past the unit test).
I think the other algorithms like rnn may have the same issues, but I haven't check yet

### CODE REVIEW

**Comment by rcurtin** [comment]
I don't have a VS2015 system handy to check this with, but if you give me a few days I can probably get something together to see if I can reproduce the error on my setup.  The merge will have be manual so that only c60d6e2 and b385960 are merged.  And I guess I really need to look into the intermittently failing tests on Travis... :)

**Comment by stereomatchingkiss** [comment]
If you are test on the windows, the test case(VanillaNetworkTest and DropoutNetworkTest) of feedforward_network_test.cpp can not read the "thyroid_train.csv", the error message are 

[WARN ] Unable to detect type of 'thyroid_train.csv'; load failed. Incorrect extension?

error: Mat::submat(): indices out of bounds or incorrectly used

unknown location(0): fatal error: in "FeedForwardNetworkTest/VanillaNetworkTest": class std::logic_error: Mat::submat(): indices out of bounds or incorrectly used
C:\Users\yyyy\Qt\mlpack_test\feedforward_network_test.cpp(118): last checkpoint: "VanillaNetworkTest" entry.
[FATAL] unknown location(0): fatal error: in "FeedForwardNetworkTest/DropoutNetworkTest": class std::runtime_error: fatal error; see Log::Fatal output
C:\Users\yyyy\Qt\mlpack_test\feedforward_network_test.cpp(246): last checkpoint: "DropoutNetworkTest" entry.
Unable to detect type of 'thyroid_train.csv'; incorrect extension?

Another test cases have no problem

**Comment by zoq** [comment]
I have no idea why the load function can't figure out the correct type. Maybe a windows specific problem. Can you step through the load function (load_impl.hpp) and check if extension is 'csv' and loadType should be arma::csv_ascii?

**Comment by zoq** [comment]
Thanks for testing the changes. The pull request includes some other changes that aren't related with the visual studio CNN workaround, so maybe you can create a new pull request that includes just the workaround? If not I'll go and extract the changes from the pull request.

**Comment by stereomatchingkiss** [comment]
Sorry, looks like I mixed the commit of the work around with other branch, will create a new pull request in a few days

**Comment by stereomatchingkiss** [comment]
I create a new pull request already, call "ann_workaround"

**Pull request closed without merging**
