### PR TITLE
Fix github-actions build for R-bindings.

### PR DESCRIPTION
**Pull request by Yashwants19**

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Looks good to me.

**Comment by rcurtin** [comment]
@Yashwants19 can you explain why this works?  I looked at the build log on the cereal PR and this PR for the R Github actions, and the only difference I can see is that now `Rcereal` is not detected on this PR.

The cereal PR: https://github.com/mlpack/mlpack/pull/2680/checks?check_run_id=1290600548
```
...
-- Found R: /usr/local/bin/R (found suitable version "4.0.3", minimum required is "4.0") 
-- Found R_roxygen2: /home/runner/work/_temp/Library/roxygen2  
-- Found R_Rcpp: /home/runner/work/_temp/Library/Rcpp (found suitable version "1.0.5", minimum required is "0.12.12")  
-- Found R_RcppArmadillo: /home/runner/work/_temp/Library/RcppArmadillo (found suitable version "0.10.1.0.0", minimum required is "0.8.400.0")  
-- Found R_RcppEnsmallen: /home/runner/work/_temp/Library/RcppEnsmallen (found suitable version "0.2.14.2.1", minimum required is "0.2.10.0")  
-- Found R_BH: /home/runner/work/_temp/Library/BH (found suitable version "1.72.0.3", minimum required is "1.58")  
-- Found R_testthat: /home/runner/work/_temp/Library/testthat  
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
...
```

This PR:

```
...
-- Found R: /usr/local/bin/R (found suitable version "4.0.3", minimum required is "4.0") 
-- Found R_roxygen2: /home/runner/work/_temp/Library/roxygen2  
-- Found R_Rcpp: /home/runner/work/_temp/Library/Rcpp (found suitable version "1.0.5", minimum required is "0.12.12")  
-- Found R_RcppArmadillo: /home/runner/work/_temp/Library/RcppArmadillo (found suitable version "0.9.900.3.0", minimum required is "0.8.400.0")  
-- Found R_RcppEnsmallen: /home/runner/work/_temp/Library/RcppEnsmallen (found suitable version "0.2.14.2.1", minimum required is "0.2.10.0")  
-- Found R_BH: /home/runner/work/_temp/Library/BH (found suitable version "1.72.0.3", minimum required is "1.58")  
-- Found R_testthat: /home/runner/work/_temp/Library/testthat  
-- Found R_Rcereal: /home/runner/work/_temp/Library/Rcereal (found suitable version "1.2.1.1", minimum required is "1.1.2")  
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
...
```

So I guess somehow this is causing Rcereal to not be available, which in turn causes the RapidJSON warning to not be triggered on Windows, which makes the build work?  I'm not sure if I understood that right.

**Comment by Yashwants19** [comment]
Hey @rcurtin, In this PR I just fix the way we compare version of the package required for R-bindings, because after `RcppArmadillo` updates to `0.10.1.0.0` our `FindRModule.cmake` was not working properly. Hence I used the available functionality provided by `utils` of `R`, which was previously done with the help of `CMake` only.

**Comment by Yashwants19** [comment]
You can simply reproduce the error by:
```sh
Rscript -e "install.packages('RcppArmadillo')" # it will install latest RcppArmadillo
cmake -DBUILD_R_BINDINGS=1 .. # On master branch 
```

**Comment by Yashwants19** [comment]
I guess for cereal issue we can provide a latest copy of cereal with the package, just like this [package](https://github.com/cran/ANN2/tree/master/inst/cereal) is providing.

**Comment by rcurtin** [comment]
@Yashwants19 you're totally right, I somehow forgot that until the cereal PR is merged, we don't have any Rcereal support at all, and so it is expected that Rcereal isn't found in the master branch build.  Sorry about that!  I have been working on that PR for so long I forgot about everything else. :smile:

Thanks for the explanation!  It looks good to me. :+1:

**Pull request merged**
