### PR TITLE
Properly use Enum type.

### PR DESCRIPTION
**Pull request by MarcosPividori**

### CODE REVIEW

**Comment by MarcosPividori** [comment]
Hi, I think Travis test failed because of an external problem, could you restart the building?

**Comment by MarcosPividori** [comment]
If you prefer, I can wait until next commit on master, and rebase this, to force a new building.

**Comment by rcurtin** [comment]
I think maybe this problem exists in `methods/rann/` and `methods/range_search/` too, so if you want you can submit a PR for those too. :)

**Comment by MarcosPividori** [comment]
Thanks, yes I will work on that!

**Pull request merged**
