### PR TITLE
I do think these headers are useless here in this file.

### PR DESCRIPTION
**Pull request by shrit**
Let us see if the CI agrees with me.

Signed-off-by: Omar Shrit <omar@shrit.me>

### CODE REVIEW

**Review by rcurtin — APPROVED** [review]
Nice, looks good to me!  :+1:

**Review by zoq — CHANGES_REQUESTED** [review]
I guess  the failing markdown build is related with the changes from the PR.

**Comment by rcurtin** [comment]
> I guess the failing markdown build is related with the changes from the PR.

Oh wow, nice catch!  I looked through the other failing builds, but then just assumed that this one was random.  I imagine it can be fixed just by including the right Boost headers in `print_docs.cpp`...

**Review by zoq — APPROVED** [review]
Looks fine to me.

**Comment by rcurtin** [comment]
Excellent, more headers removed. :rocket:

**Pull request merged**
