### PR TITLE
added Isrlu activation function

### PR DESCRIPTION
**Pull request by PranavReddyP16**
added isrlu function using a different branch

### CODE REVIEW

**Comment by kartikdutt18** [comment]
Hi @PranavReddyP16 , if you need help clearing the mix up, I would be more than happy to help. I did the something similar on my first PR.

**Comment by PranavReddyP16** [comment]
@kartikdutt18 that would be great thank you. Right now I have worked on two issues: the first one is removing all stb related code into load_image.cpp. This issue I have worked on master branch instead of creating another branch for this issue. The second issue is adding isrlu activation function. Initially I did this also in master but then created a seperate branch for this. I want to put up a PR using this branch but this branch is showing all the commits from the first issue(stb related code) as you can see above. How should I go about cleaning this up

**Comment by kartikdutt18** [comment]
Method 1 involves using interactive `git revert`, you can use it to select commits you want to remove . It still requires at least one starting commit that you need to keep. Refer [this](https://www.clock.co.uk/insight/deleting-a-git-commit)
Method 2 (Not suggested but simpler)
Take the files you added and place them in a local folder and use` git reset ` and add the files again.

**Comment by PranavReddyP16** [comment]
So let's say I want to erase every commit I've ever made. How would I go about doing that?

**Comment by kartikdutt18** [comment]
You would have to use `git reset --hard`

**Comment by PranavReddyP16** [comment]
should I just enter this in my command line or should I add anything else?

**Comment by kartikdutt18** [comment]
Run 
```
git remote add upstream https://github.com/mlpack/mlpack.git
git fetch upstream
git reset --hard upstream/master
```

**Comment by PranavReddyP16** [comment]
Should I do this from my master branch?

**Comment by PranavReddyP16** [comment]
Ok I got it thank you. Now I will open a new PR from another branch

**Comment by PranavReddyP16** [comment]
@kartikdutt18 I have opened a PR for isrlu activation function. I have deleted the branch completely and have done everything again from scratch but it's still showing all my commits even from the previous branch. I hope it's ok

**Pull request closed without merging**
