### PR TITLE
Style fixes (line length, whitespace/end_of_line, whitespace comments).

### PR DESCRIPTION
**Pull request by zoq**
Let's see what is left to do, we probably have to ignore some of the style issues.

### CODE REVIEW

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Review by jeffin143 — APPROVED** [review]
I understand now why the style checks were not catching lines that are longer than 80, but always showed green

**Review by Yashwants19 — APPROVED** [review]
Thanks for looking into this. You are the best.

**Comment by Yashwants19** [comment]
Lets merge this.

**Pull request merged**
