### PR TITLE
implement CNN and LeNet1

### PR DESCRIPTION
**Pull request by HurricaneTong**
I implement CNN and write a test by constructing LeNet1 on MNIST dataset.

### CODE REVIEW

**Comment by zoq** [comment]
Hello,

Thank you for the contribution. I'll take a look at this in the next couple of days and make some comments on the code.

**Comment by HurricaneTong** [comment]
I implement convolution with fft and block.
When input and kernel scale is large, fft performs much better than simple loop convolution.
But in my experiment simple loop convolution performs better than block convolution.
As my convolution type is different from http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2012-January/003304.html, so the block convolution is also different.
My configuration:
cmake -D DEBUG=OFF -G "Xcode"
In Xcode in use Release Mode to do comparasion

**Comment by zoq** [comment]
Typically, convolutions in CNNs involve relatively small filters, so often it isn't beneficial to go with FFT. Since we need to transform the input using FFT and afterwards we need to transform the product of the transformed inputs back using the inverse FFT. So as you pointed out FFT performs better than the simple loop convolution. There is an interesting paper: "Fast Training of Convolutional Networks through FFTs" by Michael Mathieu, Mikael Henaff and Yann LeCun.

The code looks good, but I think we should make the convolution method a template parameter like we did it with the weight initialization method. That would give the user to implement other methods to do the convolution. What do you think?


I think the code is almost ready to be merged, two more points:

- Could you remove the debug messages? I know there is no downside when building with DEBUG=OFF.
- Maybe we can find another test which checks the code that takes under 10 minutes? We partially use travis to run all tests. Unfortunately the time is limited, so we are trying to minimize the time for a single testsuite. Maybe we can decrease the numbers of epochs by using a pre trained network?

**Comment by HurricaneTong** [comment]
I don't think the paper is proper for this CNN. The value of fft(kernel) can be stored, but it seems I can't store fft(input). There may be different partition of input for different kernel as kernel size may vary. So for each convolution just one fft operation is reduced, there still exists 1 fft and 1 ifft. I think this optimization can't help fft-based convolution beat simple convolution upon small input and small kernel.

**Comment by zoq** [comment]
The convolutional neural network is ready to be used. Thanks for the contribution! If this pull request needs to be reopened, feel free to leave a comment.

**Pull request closed without merging**
