### PR TITLE
Enforce ensmallen version check

### PR DESCRIPTION
**Pull request by rcurtin**
@jeffin143 noticed in IRC that if even old ensmallen versions are installed, CMake will still successfully configure (but then fail to build).

After a little while of digging I discovered that one single character is the culprit:

Since we call `find_package(Ensmallen ...)`, which calls `FindEnsmallen.cmake`, we must use the name `Ensmallen` not `ensmallen` in the call to `find_package_handle_standard_args()`, otherwise the version check is not enforced.

### CODE REVIEW

**Comment by zoq** [comment]
Hm, not sure should we release a patch (mlpack 3.2.1)?

**Comment by jeffin143** [comment]
> Hm, not sure should we release a patch (mlpack 3.2.1)?

I think we should !

**Comment by rcurtin** [comment]
Sure, easy enough to issue a patch release.

**Comment by zoq** [comment]
Great, two more to go.

**Pull request merged**
