### PR TITLE
Added LeakyReLU (and hardtanh) activation layer and its test. 

### PR DESCRIPTION
**Pull request by awhitesong**
@zoq #412 Hi, so i have added LeakyReLU and its tests. Also adding hard tanh activation. Please check if any modifications. I have not tested the Boost tests on my system yet. I might add PReLU as well if you'll agree, that will require training alpha as well. Thanks.

### CODE REVIEW

**Comment by awhitesong** [comment]
@zoq Previous commit completes #540 . The LeakyReLU layer's test has passed in the build (both activation and derivative test). Only some case is failing in HardTanH's derivative test (activation test has passed). Maybe i am writing the derivative values something else in the test. Could you please take a look. Thanks.

**Comment by arasuarun** [comment]
I think you added the functions and not the layers.
In the relevant issues, #540 and #412, @zoq instructed that the functions should be implemented directly in the layers as **/activation_functions** is only for parameter-less functions.

**Comment by awhitesong** [comment]
Yeah, i figured that out. I coded considering both the possibilities. If it ends up in the layers, i think less change might be needed. It has the forward and the backward passes :)

**Comment by zoq** [comment]
I would appreciate it if you could open a pull request for the LeakyReLU layer and another pull request for the HardTanh layer. It makes it a lot easier for me to go through the code and make comments.

Regarding the test, everything between min and max should be 1 min >= x <= max.

As you might have already noticed, writing tests in mlpack is done with the Boost Unit Test Framework. If you write a test suite called "TestSuite" (BOOST_AUTO_TEST_SUITE(TestSuite)), and then build 'mlpack_test' ('make mlpack_test'), you can run only the tests in that test suite with 'bin/mlpack_test -t TestSuite'.  A specific test case called 'TestCase' (BOOST_AUTO_TEST_CASE(TestCase)) could be run with 'bin/mlpack_test -t TestSuite/TestCase'.

**Comment by awhitesong** [comment]
Hi. Right now the implementation is under `/methods/ann/activation_functions`. Since i have included Backward and forwards passes, do you want me to move it to `/methods/ann/layer` before the separate pr? Thanks.

**Comment by zoq** [comment]
That, would be great, yes.

**Pull request closed without merging**
