### PR TITLE
Enable auto cancel build on new push and cache for build.

### PR DESCRIPTION
**Pull request by Yashwants19**
In this PR I have tried to enable auto-cancellation of the previous build on a pull request when we push new changes to it. I have also tried to add cache feature of github action for R-bindings dependices.

### CODE REVIEW

**Comment by Yashwants19** [comment]
I guess cache is restoring properly for R-bindings dependencies.

**Comment by Yashwants19** [comment]
I guess for auto-cancel the previous build we have to merge this first.

**Comment by Yashwants19** [comment]
> Also do you want to clean the commit history or should we squash and merge?

Done.

**Review by zoq — APPROVED** [review]
Awesome a green build, hopefully after this we can cancel builds as well.

**Review by kartikdutt18 — APPROVED** [review]
Hey @Yashwants19, Thanks a lot for this PR. It's really nice to have a green build. Thanks again.

**Pull request merged**
