### PR TITLE
Have AppVeyor run the tests too

### PR DESCRIPTION
**Pull request by rcurtin**
Let's see what this does...

### CODE REVIEW

**Comment by zoq** [comment]
Should be save to use ``set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")`` in release mode as well.

**Comment by zoq** [comment]
Perhaps, you can't enable the test upload inside a PR, so we would have to merge this first. I think this is ready once, all the test commands are removed.

**Comment by rcurtin** [comment]
Sure, we can merge this now if you like and see if the tests magically start working.  At the very least, running the tests at all is an improvement.  I can open an issue after this is merged about getting the test output to upload correctly.

**Comment by zoq** [comment]
Sounds good.

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Pull request merged**
