### PR TITLE
Removed r-value references from remaining functions [and some style fixes]

### LINKED ISSUE #2287: Hard Shrink Activation Function does not comply to new method signatures
The hard shrink activation function was added in #2186 before method signatures were changed in #2259 . Since it was merged before #2259 was merged, it still has the old method signatures.

### PR DESCRIPTION
**Pull request by kartikdutt18**
closes #2287.
I have made changes to remove r-value from remaining functions. There were also some style changes that I thought should be made so I have also made them. I hope that's okay. I can also open another PR for style but since they were simple enough I've made them in this PR.
Thanks.

### CODE REVIEW

**Comment by kartikdutt18** [comment]
I think the build is fine, no relevant test has failed that is related to this PR.

**Comment by kartikdutt18** [comment]
Yeah, I think they were merged when your PR was already open so I think they weren't changed. Also I went through the repo twice to ensure that there are no other functions / layers that need to be refactored so I guess we have completely removed r-values references in ann (for arma datatypes).

**Comment by rcurtin** [comment]
Thanks!  I think you might be more on top of things than I am. :smile:

**Comment by kartikdutt18** [comment]
Thanks a lot! Happy to help in anyway I can.

**Comment by kartikdutt18** [comment]
Thanks a lot!

**Pull request merged**
