### PR TITLE
Nonlinear conjugate gradient.

### PR DESCRIPTION
**Pull request by ranjan1990**
It is not ready to merge. I want some initial review feedback. 
Here I have not assumed that the objective function is  the sum of many other function.

### CODE REVIEW

**Comment by ranjan1990** [comment]
travis-ci build test is failing for RecurrentNetworkTest.

**Comment by rcurtin** [comment]
It looks like this is a good start, but I think it would be useful to add some more tests.  You might consider adding some of the test functions that are used for L-BFGS and simulated annealing (see lbfgs_test.cpp and sa_test.cpp).  Also, if you can add some documentation, that would be really nice.  I'll dig deeper into this then.

**Comment by rcurtin** [comment]
Also closing this one for inactivity.

**Comment by ranjan1990** [comment]
I have already implemented the algorithm and was for review, before
merging. I am not sure what was the problem in this  implementation.


Ranjan Mondal
Indian Statistical Institute,
Kolkata - 700108.

**Comment by rcurtin** [comment]
I was waiting for more tests to be added before I reviewed it fully, sorry if that was not clear.

**Pull request closed without merging**
