### PR TITLE
Added HardTanH Layer and its tests

### PR DESCRIPTION
**Pull request by awhitesong**
@zoq Hi so all the tests have passed on my system. Solution to #540 .  Currently recurrent network test is failing the build, hardtanh has passed.

### CODE REVIEW

**Comment by zoq** [comment]
I've looked over the code, and made some comments, once we fixed this minor issues, I'll go and merge the code.

**Comment by awhitesong** [comment]
@zoq Done. Build for other probabilistic cases are failing. Hardtanh passed.

**Comment by rcurtin** [comment]
@awhitesong: want to open a PR adding your name to `src/mlpack/core.hpp` and `COPYRIGHT.txt`?

**Comment by zoq** [comment]
Thanks for the contribution, I made minor modifications in 971213a377e27ac41 and removed the Forward function in 971213a377e27ac41 for a single value. Let me know if I messed anything up.

**Comment by awhitesong** [comment]
@zoq Its fine if you removed the single value Forward, Backward functions from tests as well. I intentionally created those to test `double fn(const double x);` and `double deriv(const double x);` separately, read somewhere it to be a good practice to test each private function separately to make later debugging in higher layers of abstraction easier. Its totally fine though. Thanks. @rcurtin sure, will do it.

**Pull request merged**
