### PR TITLE
Added braced lists to ann_layer_test.cpp

### PR DESCRIPTION
**Pull request by Abilityguy**
Reference Issue #2699 
This PR continues from PR #2705

### CODE REVIEW

**Review by rcurtin — APPROVED** [review]
Looks good to me---thanks @Abilityguy!  Do you want to make this change to other files in `src/mlpack/tests/` too?  I think there are other uses of `<<` to create Armadillo matrices in that directory.

I restarted a few of the failing builds, but I don't think any failures are related to the changes here.

**Comment by Abilityguy** [comment]
Hi @rcurtin , I believe that all of the files except ```ann_layer_test.cpp``` were covered in #2708 .
I will take a look at the files in ```src/mlpack/tests/``` to check if any files were missed out.

**Comment by Abilityguy** [comment]
Took a look and there were a few files that needed change. 
They have all been covered in #2794.

**Comment by rcurtin** [comment]
Thanks! :+1:

**Review by zoq — APPROVED** [review]
Looks good to me, thanks for putting this together.

**Comment by zoq** [comment]
Thanks again for the contribution.

**Pull request merged**
