### PR TITLE
Copy, move constructors and copy assignment operator added

### PR DESCRIPTION
**Pull request by piyush-jaiswal**
For issue #817 
Function declarations are in dtree.hpp
Function bodies are in dtree_impl.hpp

Awaiting your response and suggestions. :)

### CODE REVIEW

**Comment by rcurtin** [comment]
Hi there Piyush,

Thanks for the contribution.  Before we merge this, could I ask you to add some tests?  Take a look at the tests I wrote for the LSHSearch class's copy/move constructors and assignment operators:

https://github.com/rcurtin/mlpack/blob/bindings/src/mlpack/tests/lsh_test.cpp#L839

Thanks,

Ryan

**Comment by rcurtin** [comment]
I think there is still a bug here.  Can you change your tests so that you construct the DTree on the heap with the 'new' operator?  Then after you make the copy with the copy constructor, delete the first DTree. After that, check the values of the copied DTree.  This will ensure that we are not using memory that the first DTree allocated, and that we have a safe copy.  Let me know if I can explain this further.

**Comment by piyush-jaiswal** [comment]
Hey Ryan,
I built the DTree using the 'new' operator on the heap as you asked. Kindly provide any more changes if needed.

**Comment by rcurtin** [comment]
There are some issues here---the tests do not actually catch the fact that the tree is not properly copied or moved.  There is another PR open for this that is closer to working, I think maybe the right solution is to use that and then merge the tests from this PR too.

**Comment by piyush-jaiswal** [comment]
Sure, no problem.

**Comment by rcurtin** [comment]
Hi there Piyush, I merged some of your changes in the tests after merging #826 (specifically in 47a0a057 and a66a604c).  Thanks for your work on this PR.  I can add your name to the list of contributors---let me know if you want me to do that.

**Pull request closed without merging**
