### PR TITLE
Try to fix MacOS Python build

### PR DESCRIPTION
**Pull request by zoq**
Check if the latest pytest version introduced an issue.

### CODE REVIEW

**Comment by rcurtin** [comment]
Huh, I'm not sure if this is a Python version issue:

```
tests/test_python_binding.py .....F..Fatal Python error: Aborted
```

Do you think maybe this is actually, e.g., a memory leak in the Python bindings?  I think this is what's going on in the Julia bindings but I haven't gotten my hands on a system to reproduce and dig into it yet.  Maybe it's worth trying to comment out all non-matrix related tests here and see if things pass?

If pytest runs the tests in order, then the crashing test here is probably `testNumpyFContiguousMatrix`.

**Comment by zoq** [comment]
> Huh, I'm not sure if this is a Python version issue:
> 
> ```
> tests/test_python_binding.py .....F..Fatal Python error: Aborted
> ```
> 
> Do you think maybe this is actually, e.g., a memory leak in the Python bindings? I think this is what's going on in the Julia bindings but I haven't gotten my hands on a system to reproduce and dig into it yet. Maybe it's worth trying to comment out all non-matrix related tests here and see if things pass?
> 
> If pytest runs the tests in order, then the crashing test here is probably `testNumpyFContiguousMatrix`.

Agreed, I'll see if I can reproduce the issue on my local machine, easier to debug than using the CI pipeline.

**Comment by zoq** [comment]
Okay, let's try to fix the build.

**Comment by zoq** [comment]
Unfortunately, I can't reproduce the issue on my macOS setup, so I have to use azure.

**Comment by zoq** [comment]
Closing in favor of https://github.com/mlpack/mlpack/pull/2688

**Pull request closed without merging**
