### PR TITLE
Rename libgo_util.so to libmlpack_go_util.so.

### PR DESCRIPTION
**Pull request by rcurtin**
I noticed (while preparing JuliaPackaging/Yggdrasil#1346) that we distribute a library that's just called `libgo_util.so`.  I thought maybe this library name could potentially be confusing or interfere with another system library or another package's library, so this PR just changes the name from `libgo_util.so` to `libmlpack_go_util.so`, which should hopefully help make it clearer what the purpose of the library is.

@Yashwants19 let me know if you see any issue with this change. :+1:

### CODE REVIEW

**Comment by Yashwants19** [comment]
Hi @rcurtin This is looking great. But I think so we should also have to manage`LDFLAGS` in `arma_util.go` and `io_util.go`.
Thank You :).

**Comment by rcurtin** [comment]
@Yashwants19 good point, thanks!  Let's see if this passes the builds now. :)

**Comment by Yashwants19** [comment]
This looks awesome, Thank you for all the changes. :)

**Comment by favre49** [comment]
I'll go ahead and merge this now

**Pull request merged**
