### PR TITLE
Faster build times

### PR DESCRIPTION
**Pull request by arirang-pust**
Replaced all instances of `#include <mlpack/core.hpp>` with `#include <mlpack/prereqs.hpp>`.  This doesn't affect build times when building the whole project, but it greatly reduces build times after modifying only a few files.

### CODE REVIEW

**Comment by mikeizbicki** [comment]
This is a better version of #841.  It compiles fine now on my machine (g++ 4.9.2), I'm not sure why it doesn't compile on the appveyor machine.

**Comment by rcurtin** [comment]
```
C:\projects\mlpack\src\mlpack\core\math\lin_alg.cpp(233): error C2065: 'M_SQRT2': undeclared identifier [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
```

That's our offending line, but it's strange because `<mlpack/prereqs.hpp>` includes `<cmath>`.

http://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio

So, worth a shot is the explanation that something else is including `<cmath>` before `_USE_MATH_DEFINES` is defined.  A "shot in the dark" idea is to push that `<cmath>` include and `_USE_MATH_DEFINES` definition in `prereqs.hpp` up to be the first thing included.  If you like, push a change like that and let's see what AppVeyor thinks... :)

**Comment by rcurtin** [comment]
I guess the shot in the dark idea worked. :)  Thanks!  This is a nice improvement.

As far as credit goes, should we add the names of the students who did this fix (plus yours) to the list of contributors?

**Comment by mikeizbicki** [comment]
This was work that I did in order to make it easier for the students.

**Comment by rcurtin** [comment]
Ah, ok.  I was surprised not to see your name on the list of contributors, I thought you'd done some other fixes too.  Do you want me to add it? :)

**Comment by mikeizbicki** [comment]
Yeah, thanks.

I think I submitted a couple of other pull requests on the documentation,
but not anything code related.

**Comment by rcurtin** [comment]
Ok, added in d4b2c4b.

**Pull request merged**
