### PR TITLE
Move Sequentials to LayerType

### PR DESCRIPTION
**Pull request by kartikdutt18**
Hey everyone,
This PR moves sequential type to LayerType. 
The reason I have made the change is as follows :
```
  // Layer1 is identity layer.
  std::cout << (darknet.GetModel().Model()[0].type() == typeid(new mlpack::ann::IdentityLayer<>())) << std::endl;
  // Layer2 is sequential layer.
  std::cout << (darknet.GetModel().Model()[1].type() == typeid(new mlpack::ann::Sequential<>())) << std::endl;
```
The sequential layer comparison fails if the below change isn't made.

The reason I want to make the comparison is listed below : 
I need to load running mean and variance into BatchNorm Layer and in general the BatchNorm Layer might be wrapped in many sequentials or residual layers (darknet53) so I was applying something similar to dfs here.

```
// Queue containing csv paths for running mean.
std::queue<std::string> batchNormRunningMean;

template<typename LayerType = mlpack::ann::FFN<>>
void LoadRunningMeanAndVariance(LayerType& baseLayer, size_t i = 0)
{
  while (i < baseLayer.Model().size() && !batchNormRunningMean.empty())
   {
    if (baseLayer.Model()[i].type() == typeid(new mlpack::ann::Sequential<>()))
   {
     LoadRunningMeanAndVariance<mlpack::ann::Sequential<>>(*baseLayer.Model()[i]);
   }
   if (!batchNormRunningMean.empty() && baseLayer.Model()[i].type() == typeid(mlpack::ann::BatchNorm<>()))
   {
      arma::mat runningMean;
      mlpack::data::Load(batchNormRunningMean.front(), runningMean);
      batchNormRunningMean.pop();
      baseLayer.Model()[i]->RunningMean() = runningMean;
   }
   i++;
  }
}
```

We can also use this to create a model summary while maintaining an index and if each layer had Name Parameter in them.

Keeping this as draft for now, Will have to remove openmp change if build fails else we can restart the build for #2412 and merge that as well.

Kindly let me know if the above logic makes sense or if there is a better way of handling this.
Thanks.

Regards,
Kartik,

CC: @KimSangYeon-DGU, @saksham189

### CODE REVIEW

**Comment by kartikdutt18** [comment]
```
template<typename LayerType = mlpack::ann::FFN<>>
void LoadRunningMeanAndVariance(LayerType&& baseLayer, size_t i = 0)
{
  std::cout << baseLayer.Model().size() << std::endl;
  while (i < baseLayer.Model().size() && !batchNormRunningMean.empty())
  {
    if (baseLayer.Model()[i].type() == typeid(new mlpack::ann::Sequential<>()))
    {
      LoadRunningMeanAndVariance<mlpack::ann::Sequential<>>(&(baseLayer.Model()[i]));
    }

    if (!batchNormRunningMean.empty() &&
        baseLayer.Model()[i].type() == typeid(new mlpack::ann::BatchNorm<>()))
    {
      arma::mat runningMean;
      mlpack::data::Load(batchNormRunningMean.front(), runningMean);
      batchNormRunningMean.pop();
      baseLayer.Model()[i].TrainingMean() = runningMean;
      baseLayer.Model()[i].TrainingMean().print();
    }

    i++;
  }
}
```
Maybe I am missing something, but when the above code goes into recursive call for Sequential Layer the  following line prints : 
```
std::cout << baseLayer.Model().size() << std::endl;
```
0 for each sequential layer. Shouldn't this work or maybe I am missing something.

**Comment by kartikdutt18** [comment]
Having a separate function for sequential doesn't work (as I can't call to it (compile time error)). I'll try working on a solution using std::enable_if.

**Comment by KimSangYeon-DGU** [comment]
> The sequential layer comparison fails if the below change isn't made.
Hey @kartikdutt18, what is the "below change"?

**Comment by KimSangYeon-DGU** [comment]
Can you share a file to reproduce the same issue you mentioned?

**Comment by kartikdutt18** [comment]
Sure, The below change refers to changes in the PR.

**Comment by kartikdutt18** [comment]
Hey @KimSangYeon-DGU, I copied the files from converter repo to models repo so that it can be compiled without any other files. [Here](https://github.com/kartikdutt18/models/tree/DarknetModel) is the link to the branch.
Steps to follows to compile :
```
mkdir build && cd build
cmake -DUSE_OPENMP=ON ../
sudo make -j3 && ./bin/weight_converter
```
Kindly let me know if this works. After the code runs the output will be something like this : 
```
Sequential Layer. 13
Recursive Call0
Sequential Layer. 14
Recursive Call0
Sequential Layer. 15
```
Which shows that when sequential layer is passed recursively, it's network is empty.

**Comment by zoq** [comment]
> Maybe I am missing something, but when the above code goes into recursive call for Sequential Layer the following line prints :

Can you test the same code with a reference instead of move?

**Comment by kartikdutt18** [comment]
> Can you test the same code with a reference instead of move?

This gave me error that Model is defined for layers other than sequential. Somehow, we need to use std::enable_if to check if type is sequential or FFN. I added another function for sequential (input wasn't templated) and it still gives the error.

**Comment by zoq** [comment]
I guess I can use:

```C++
template<typename LayerType = mlpack::ann::FFN<>>
void LoadRunningMeanAndVariance(LayerType&& baseLayer, size_t i = 0)
{
  std::cout << baseLayer.Model().size() << std::endl;
  while (i < baseLayer.Model().size() && !batchNormRunningMean.empty())
  {
    if (baseLayer.Model()[i].type() == typeid(new mlpack::ann::Sequential<>()))
    {
      LoadRunningMeanAndVariance<mlpack::ann::Sequential<>>(&(baseLayer.Model()[i]));
    }

    if (!batchNormRunningMean.empty() &&
        baseLayer.Model()[i].type() == typeid(new mlpack::ann::BatchNorm<>()))
    {
      arma::mat runningMean;
      mlpack::data::Load(batchNormRunningMean.front(), runningMean);
      batchNormRunningMean.pop();
      baseLayer.Model()[i].TrainingMean() = runningMean;
      baseLayer.Model()[i].TrainingMean().print();
    }

    i++;
  }
}
```

for further testing?

**Comment by kartikdutt18** [comment]
Yes, I pushing all my changes in a branches with a make file. That would be easier. For the time being, I have hardcoded the running mean and variance.

**Comment by zoq** [comment]
Okay, great thanks for the clarification.

**Pull request closed without merging**
