### PR TITLE
ANN experiment for boost::visitor

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
issue #2647 , Help needed.

### CODE REVIEW

**Comment by Aakash-kaushik** [comment]
Hi @shrit, I haven't edited FFN yet but created a base class and made some changes to Linear class, Can you give it a look and see if the trajectory is right ?

**Comment by kartikdutt18** [comment]
I'm not sure but since we only want to check difference in runtime only and not compile time, why not simply create a folder with ffn_fast.hpp and linear_fast.hpp. That way you won't have to deal with the issues arising from other layers. Also it will be simpler to do that also since this isn't for making the change in the codebase but just to compare the difference, it should be simpler to the aforementioned. But again, I could've missed something.

**Comment by Aakash-kaushik** [comment]
Hey @kartikdutt18 this does seems like a better approach but I think that the linear and FFN class do use some other parts of the library and even when writing a example with just linear layers I think I would need some other parts of the library.

**Comment by kartikdutt18** [comment]
You can include them from library so it shouldn't be an issue. In my opinion you will need a activation and loss function which can include individually.

**Comment by Aakash-kaushik** [comment]
After some thought i can define a loss function in the example and generate arma::mat from random numbers with fixed seed for training the network, I think I can remove the library dependency from the example at least.

**Comment by Aakash-kaushik** [comment]
Hi, I will close this PR as i will be working on this in a seperate folder rather than making changes to the whole mlpack project, as @kartikdutt18 suggested. and i will be working on this [here](https://github.com/Aakash-kaushik/ann_exp).

**Pull request closed without merging**
