### PR TITLE
Fix codes and improve doc

### PR DESCRIPTION
**Pull request by AdarshSantoria**
Fixed the code example in doc as mentioned in #3397 and some other doc fixes.

### CODE REVIEW

**Review by rcurtin — APPROVED** [review]
Thanks, this looks good to me. :+1: Once #3398 is merged, do you want to add this PR to the general entry in `HISTORY.md`?

**Comment by rcurtin** [comment]
Do you mind adding this PR to `HISTORY.md`?  You can just add the PR number to the changelog entry here: https://github.com/mlpack/mlpack/blob/master/HISTORY.md?plain=1#L4

**Comment by AdarshSantoria** [comment]
Yes I will submit a fresh pr for this as it's causing conflicts.

**Comment by rcurtin** [comment]
Ok, sure---I think that you just merged the conflict successfully and could now make the changes, but #3414 is fine too. :+1:

**Pull request merged**
