### PR TITLE
Fix -Wpedantic

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Dear mlpack maintainers,

When I compile with GCC with `-Wpedantic` I got some warnings. This PR fixes these. 

I see that the causes of the warnings are all well-intended: for example, adding a semicolon after calling a macro that already has its own semicolon. I understand one wants the macro to be complete, yet removing that semicolon fixed the warning. I could have opted to remove the semicolons of each macro call, yet that felt inferior.

Good luck reviewing and keep up the good work!

Cheers, Richel Bilderbeek

### CODE REVIEW

**Review by rcurtin — APPROVED** [review]
Looks great.  Easy review!  Thank you so much for fixing this.  If you find other little things too, please do feel free to open more PRs. :)

**Review by shrit — APPROVED** [review]
LGTM

**Comment by richelbilderbeek** [comment]
There was a merge conflict that I tried to fix. It was a simple fix: use the latest and greatest from `master` and fix the pedantic warning :-)

I do guess this needs a new review. Sorry for that!

**Comment by richelbilderbeek** [comment]
@rcurtin I got the stickers, thanks so much!

**Pull request merged**
