### PR TITLE
Overhaul documentation homepage

### PR DESCRIPTION
**Pull request by rcurtin**
This PR remakes the homepage of the documentation in a clearer way, following the discussions in #3803.

Here is the built documentation:

 * [Index of most recent documentation build](http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/1065/Built_20documentation/)
 
(It took a little while to get Jenkins to render that correctly!  I am still playing with security policies.)

The basic bits of the overhaul are:

1. mlpack algorithms and functions are now organized by roughly where they might sit in a data science pipeline (which goes from data loading to preprocessing all the way to deployment).  The homepage has a drawn-out SVG (which has a 'narrow' version for mobile devices too) that organizes the documentation in an easily clickable way.  The 'landing pages' for each step in the pipeline have where they are in the pipeline at the top of the page.

2. The sidebar is now a complete page map; every `.md` file has a corresponding link in the sidebar.  The hierarchy of the sidebar matches the pipeline stages above.

3. The documentation now links to the Youtube videos I recorded some time back. :)

4. The community page was updated to have the mlpack video chat on the first Monday of every month.  And I will actually post about it in #mlpack each month...

5. I added `ci.md`, which documents the CI systems we have.  There is a lot of hidden knowledge about those, so I tried to write some of it down.  I'm sure that will improve over time.

6. I also added `compile.md`, a page detailing how you might compile a simple mlpack program, as well as a few other pages about installation, CMake options, and so forth.

7. A little bit of CSS changes to make the sidebar just a bit wider, because it looks really bad when things wrap.  (Also: I would like the sidebar to store the "state" of what's expanded and what isn't, but that will take some ~fairly simple Javascript.  I'll get to it at some point, but not for this PR.)

Whenever I add the links above (when the build passes), I'll add a link to each new page or page that I changed significantly.

Feedback appreciated!

### CODE REVIEW

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by shrit** [comment]
@rcurtin is this ready for review ?

**Comment by rcurtin** [comment]
Let me fix the documentation build... I thought that would be easy but it has taken a few iterations.  I should have marked this as a draft initially, I'll do that now until I get it passing.

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Review by shrit — COMMENTED** [review]
Looks very good, much better than before. 

Here are a couple of things that I have noticed:

1. The first output is equal to the second one, I expected different results as written above:
Screenshot 2024-12-02 at 16-02-01

2. Links to outside of CI (e.g., youtube) are not functional. (Probably this is because it is inside the CI, as we have already discuss it)

3. I think we can  the quick start guide to the start, instead of the middle

4. I think we can find a better name instead of the C++ API docs. 

5. We can also remove the gray color of the bindings because it looks like a separation bar.

6. Would be interesting to recall Matrics and data to "Matrices representation in mlpack".

7. Finally, in the CI page I have noticed that in the docs section we are referring to how to build the docs locally, I think we can keep it for now, but I do not think idealy this should be the place for it, it is better to have a unique page for the docs, as others might be interested contributing. 

Screenshot 2024-12-03 at 16-48-12

Overall looks good, we can get it merged when all of these small modifications get resolved. Amazing work

**Comment by rcurtin** [comment]
> 1. The first output is equal to the second one, I expected different results as written above:

They're actually not exactly the same, there is also a backtrace line in the first program output.

> 2. Links to outside of CI (e.g., youtube) are not functional. (Probably this is because it is inside the CI, as we have already discuss it)

Right, this had to do with the content security policy that Jenkins was using (more [here](https://content-security-policy.com)).  I'm still tuning this, but I have a configuration that works now.  (It's actually quite insecure, but I am trying to see how much I can lock it down without breaking the documentation build.)

> 3. I think we can the quick start guide to the start, instead of the middle

Agree, fixed in 3e28d76883.

> 4. I think we can find a better name instead of the C++ API docs.

Do you have any suggestions on this one?  I thought about it for a while but I haven't come up with anything.  I do want to distinguish it from the binding documentation (which is not in C++), so I think we need to keep the C++ term in there.

> 5. We can also remove the gray color of the bindings because it looks like a separation bar.

Done in 9cc2ae96.

> 6. Would be interesting to recall Matrics and data to "Matrices representation in mlpack".

How about "Data representation in mlpack"?  Changed in e4a2bf4.

> 7. Finally, in the CI page I have noticed that in the docs section we are referring to how to build the docs locally, I think we can keep it for now, but I do not think idealy this should be the place for it, it is better to have a unique page for the docs, as others might be interested contributing.

The `build-docs.sh` and `test-docs.sh` scripts are specifically for local development and CI usage though; a regular mlpack user generally shouldn't use those scripts, because they require a bunch of dependencies.  (Plus they can just read the raw markdown if they want or render it in a browser.)

I do agree that we should eventually have a page discussing how to write documentation, what needs to be documented, and how to test it (including these scripts); basically a guide for new contributors.  But I didn't write that yet; here I just wanted to write down that these scripts exist and are run in CI.

> Overall looks good, we can get it merged when all of these small modifications get resolved. Amazing work

Thanks!  It took forever to figure out how to do all the links in the SVGs and everything like that.

**Review by shrit — APPROVED** [review]
Looks good to me, and Data representation in mlpack works :100:

**Comment by rcurtin** [comment]
Sorry this sat for so long, but I got the documentation build to pass (still have not cleaned up that job yet) so let's go ahead and merge.

**Pull request merged**
