### PR TITLE
migrate arma_extend_test from boost to catch2

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
Regarding Issuse #2523

### CODE REVIEW

**Comment by Aakash-kaushik** [comment]
I will also add myself to the contributor's list in this PR as i feel like the PR for mean absolute percentage error may take time. : )

**Comment by Aakash-kaushik** [comment]
Hey, is there anything else that needs to be done with this PR, I think i have made all the required edits in cmake files and the actual arma_extend_test file, let me know if i am missing something.

**Review by zoq — APPROVED** [review]
Looks good to me, thanks for putting this together.

**Review by birm — APPROVED** [review]
We have a lot of these coming!

**Comment by Aakash-kaushik** [comment]
> We have a lot of these coming!

Well predicted.

**Pull request merged**
