### PR TITLE
Enable more parallelization on the R action worker via:  -j $(nproc)

### LINKED ISSUE #3707: Switch from `-j 2` to `-j ${nproc}`
Glancing at the runtime of the [R GitHub Actions workflow](https://github.com/mlpack/mlpack/blob/e851d0367ed2826e938eab02e77805f327185e42/.github/workflows/main.yml), I think we can use a few more cores. 

Currently, the number of cores is [set to 2](https://github.com/mlpack/mlpack/blob/e851d0367ed2826e938eab02e77805f327185e42/.github/workflows/main.yml#L119); however, GitHub Actions for public repositories allows for up to [4 cores/16 GB (`ubuntu-latest`) or 3 cores/7 GB (`macos-latest`)](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) to be present. 

I suppose this issue ticket is a note to switch: 

```
    env:
      MAKEFLAGS: "-j 2"
```

to:

```
    env:
      MAKEFLAGS: "-j $(nproc)"
```

Perhaps include this in the prior step as the `MAKEFLAGS` variables can be used when setting up R dependencies.

### PR DESCRIPTION
**Pull request by coatless**
Improves the `env` variable `MAKEFLAGS` to use all available cores instead of 2 due to variability in the GH runner.

Close #3707

### CODE REVIEW

**Comment by coatless** [comment]
Ahh, windows... Why don't you like `{nprocs}`? I'll poke around more tomorrow in a VM.

**Comment by shrit** [comment]
The problem with this is that mlpack needs a lot of RAM, for instance I have 24 cores on my machine which require at any time around 50 ~ 70 GB or RAM only to compile mlpack (whether compiling tests or not).
I am lucky to have 256 GB or RAM on my desktop, but If you do not have that amount of RAM then you have a high chance of freezing your entire machine.

**Comment by coatless** [comment]
@shrit perhaps it's a memory limitation; but, workers should have [4 cores/16 GB (`ubuntu-latest`, `windows-latest`) or 3 cores/7 GB (`macos-latest`)](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories). I suppose a question that needs to be answered is how much RAM is required per core assigned to compile `mlpack`?

**Comment by conradsnicta** [comment]
@coatless Anecdotally, suggest using 3 real cores per 16 GB, and certainly not more than 4 per 16 GB.  This is to allow for OS overheads, etc.  Additionally, do not consider any additional "fake" threads from HT/SMT (hyper-threading / simultaneous multi-threading).  For compiling code, these extra threads don't bring much gain, if any, while gobbling up memory.

**Pull request closed without merging**
