### PR TITLE
Build system for documentation

### PR DESCRIPTION
**Pull request by rcurtin**
This PR contains some simple build scripts for our documentation.  There are still a few things to get working before it's ready for review:

 - [x] Make CI tests for documentation build pass
 - [x] Add a script to extract and compile C++ examples from documentation
 - [x] Connect extracted C++ examples to CI job

If you run the script `scripts/build-docs.sh` from the root of the repository (and you have `kramdown`, `tidy`, and `checklink` installed), this will build all of the Markdown files in `doc/` into the directory `doc/html/`, from where you can browse the documentation in `doc/html/index.html`.

I've fixed numerous links and TODOs present in the Markdown documentation I've written so far, using the output of the script (specifically the output of `checklink`).

### CODE REVIEW

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
Ok, I think this is ready to review.  There are two scripts: `build-docs.sh` and `test-docs.sh`.  The first converts Markdown documentation to HTML and checks all the links, and the second actually builds the documentation.

I created a Jenkins job to run both of these scripts, and it fails if there is a problem: http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/93/

**Comment by shrit** [comment]
Many diffs in this PR look exactly the same as the last PR I reviewed.

**Comment by shrit** [comment]
Would you merge the last one and then merge it with this one, I am pretty sure that we will get a lot of merge conflicts.
Actually, I am not able to see clearly what this PR is adding.

**Comment by rcurtin** [comment]
> Would you merge the last one and then merge it with this one, I am pretty sure that we will get a lot of merge conflicts. Actually, I am not able to see clearly what this PR is adding.

Actually that is because the idea was that this one would be reviewed first, and then merged, and then the second PR would be a lot easier.  I suppose we could just close this one and merge the other one, which includes both the build system from here and the sidebar, especially if you've fully reviewed the other one... @shrit if you think that's the right way, maybe just close this one and we'll go with that one?

**Pull request merged**
