### PR TITLE
Add fastmks test

### PR DESCRIPTION
**Pull request by Prabhat-IIT**
#1152 
Here are the tests I've written for fastmks. As of now some tests are failing strangely and I'm trying to fix that. Any help is appreciated. Moreover, if anyone can suggest more test I'll be more than happy to add it.

### CODE REVIEW

**Comment by Prabhat-IIT** [comment]
One thing I've in mind is comparing the `indices` returned by Gaussian kernel and other shift-invariant kernels with `knn`. @rcurtin   can you confirm that both will always return the same result?

**Comment by Prabhat-IIT** [comment]
@zoq I need some help with one thing that while writing tests I couldn't pass `kernels` correctly. Neither setting input param directly like SetInputParam("kernels", "hyptan") works nor it works like SetInputParam("kernels", kernalName) where `string kernelName`="hyptan" for ex. It leads to tests running forever. I've commented out the code as of now.

**Comment by Prabhat-IIT** [comment]
> I dug into this one a little bit and I see there is a bug in the FastMKS program. Basically, we pass the reference set to the model, but then the reference set is deallocated before the model is saved. 
I've reported this bug on irc two times but you were busy that time. Thanks for the patch.I'll do the necessary changes soon!

**Comment by rcurtin** [comment]
Yes, and I saw it each time you posted but had not had a chance to look into it until now.

**Comment by rcurtin** [comment]
Since #1765 is merged, we can close this.  Thanks @Prabhat-IIT for your hard work on the initial PR. :+1:

**Pull request closed without merging**
