### PR TITLE
Document `UBTree`

### PR DESCRIPTION
**Pull request by rcurtin**
The `UBTree` is the last of the `BinarySpaceTree` typedefs to be documented.  It took a very long time to figure out how to document the `CellBound`, and I hope I did at least a mostly comprehensible job.  Code changes were pretty minimal.

I'll add a link below when the documentation is finished building for each changed page:

 * `ub_tree.md`
 * `binary_space_tree.md` section on `CellBound`
 * `binary_space_tree.md` section on `UBTreeSplit`
 * `trees.md` list of trees
 * `developer.md` list of trees

### CODE REVIEW

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by shrit** [comment]
@mlpack-jenkins test this please

**Review by shrit — APPROVED** [review]
last comment in #3814 applies in here

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Pull request merged**
