### PR TITLE
Fix drop out layer

### PR DESCRIPTION
**Pull request by stereomatchingkiss**
DropOutLayer forgot to initialize the scale parameter(I hope this is the correct way to initialize it)

### CODE REVIEW

**Comment by zoq** [comment]
I like to point out that we only need to initialize the scale parameter if we load an already trained network and use the model for prediction only. If we train the model the scale parameter is set in the else case of the forward pass. However, you pointed out an important case, we should take care of. One problem I see with the solution is that a change of the probability of setting a value to zero (ratio) has no effect, if we use the constructor list to initialize the scale parameter. So instead of using the constructor list or the else case of the forward pass, we could set the ratio at the beginning of the forward pass. Does this sound reasonable? Maybe there is a better solution?

**Comment by stereomatchingkiss** [comment]
Sorry for my misunderstanding, I should open an issue before I treat it as a bug next time.

>So instead of using the constructor list or the else case of the forward pass, we could set the ratio at the beginning of the forward pass

Do you mean you want to set the ration when you call the Forward function?

    template<typename eT>
    void Forward(const arma::Mat<eT>& input, arma::Mat<eT>& output)
    {
      ratio = 0.5;
      //......
    }

But how could the user setup the ration under this case?

> One problem I see with the solution is that a change of the probability of setting a value to zero (ratio) has no effect

What about do the value checking when construct the dropout layer(at runtime)?
Or write down the preconditions on the comments if you do not want to do any runtime check(ask the users do not set ratio as 1.0 or 0.0)
Maybe there are better solutions there, but these are what I could come up with now.

**Comment by zoq** [comment]
> Sorry for my misunderstanding, I should open an issue before I treat it as a bug next time.

No worries, I guess the pull request makes it sometimes easier to talk about changes.

> Do you mean you want to set the ration when you call the Forward function?

I would put ``scale = 1.0 / (1.0 - ratio);``at the beginning of the ``Forward(...)`` function, so the ``scale`` value is calculated even in prediction only mode. Additionally a user could change the scale value afterwards through the ``Ratio()`` function.

```
template<typename eT>
void Forward(const arma::Mat<eT>& input, arma::Mat<eT>& output)
 {	
    scale = 1.0 / (1.0 - ratio);

    // The dropout mask will not be multiplied in the deterministic mode
    // (during testing).
    if (deterministic)
    {
      output = input;

      if (rescale)
        output *= scale;
    }
    else
    {
      // Scale with input / (1 - ratio) and set values to zero with probability
      // ratio.
      mask = arma::randu<arma::Mat<eT> >(input.n_rows, input.n_cols);
      mask.transform( [&](double val) { return (val > ratio); } );
      output = input % mask * scale;
    }
}
```

**Comment by stereomatchingkiss** [comment]
Maybe we can set scale when the ratio is changed, but current api cannot do that. Something as following

    void SetRatio(double ratioValue)
    {
        ratio = ratioValue;
        scale = 1.0 / (1.0 - ratio);
    }

I think I would setup the value of scale as you suggested and specify the range of the ratio on the comments

    param ratio The ratio of the drop out(ratio > 0 && ratio < 1), by default it is 0.5

**Comment by zoq** [comment]
There are a few exceptions, but generally mlpack doesn't use setter methods. So, I'm not sure if it's a good idea to switch to another interface in this case. I'm interested to hear what @rcurtin things about the proposed change.

**Comment by rcurtin** [comment]
I've gone back and forth on this many times.  In this particular case it seems like the fastest code would result by a `void SetRatio(double ratioValue)` function instead of a `double& Ratio()` function, since some post-processing of the value needs to be done.  I'd suggest the function name `void Ratio(double ratio)` instead of `SetRatio()`, though, to be more consistent with the other mlpack code that has functions like this (I think this is also done in `GaussianKernel` and a few of the other kernels).

It's usually a subjective call to decide whether to go with a `void Parameter(type parameter)` or a `parameter& Parameter()` function, and I don't think there's a one-size-fits-all solution.  For instance, working with matrices means that something like `void Matrix(mat& matrix)` will be very slow.  Now that we use C++11, we can write `void Matrix(mat&& matrix)`, but this still can make expressions very awkward; consider adding 1 to the diagonals of the matrix.  That'll give something like... `Matrix(std::move(Matrix()) + arma::eye<arma::mat>(Matrix().n_rows, Matrix().n_cols)))`, but if you were able to work directly on the matrix you could just write `Matrix() += arma::eye<arma::mat>(Matrix().n_rows, Matrix().n_cols)`.

I think that in this case, moving the calculation of `scale` outside of `Forward()` may not actually give any noticeable runtime improvement, since the vast majority of the work spent in `Forward()` will be in the matrix operations.  A couple other thoughts in that vein: creating the `mask` object is going to take some amount of memory; it may be better to sequentially generate random numbers in a single loop over the input.  Also, if `deterministic` is true and `rescale` is true, you have to pass through the input matrix twice: once for `output = input` and once for `output *= scale`.  I think it will be faster to do this:

```
if (deterministic)
{
  if (!rescale)
    output = input;
  else
    output = input * scale;
}
```

Of course, it's probably worth running a quick test on either of those ideas to see if they're worth implementing or actually give a runtime improvement.

**Comment by stereomatchingkiss** [comment]
>I think that in this case, moving the calculation of scale outside of Forward() may not actually give any noticeable runtime improvement

I have same opinion on this one
    
>creating the mask object is going to take some amount of memory

This one I am not sure how good the optimization of armadillo can do, it would do things like

arma::mat randomMat;// build a random matrix
mask = randomMat; //copy the data of randomMat to mask

or overwrite the data of mask directly since the mask already allocate the buffer?

I do a small test on this

    int main()
    {
        arma::mat temp;
        while(1){
            temp = arma::randu<arma::mat>(1000, 1000);
        }    
    }

Then open the task manager on win8 and observe the usage of memory, it is always 8.3MB
So I guess armadillo5.x(or the compiler) do smart enough to avoid memory allocation under this case.

**Comment by rcurtin** [comment]
> This one I am not sure how good the optimization of armadillo can do, it would do things like
> 
> arma::mat randomMat;// build a random matrix
> mask = randomMat; //copy the data of randomMat to mask
>
> or overwrite the data of mask directly since the mask already allocate the buffer?

I'm not sure what you mean... in that code snippet, if `mask` is already initialized, then it will overwrite the data.

In your example, yes, Armadillo is smart enough to avoid allocating memory because it is always the same size.  But if you were to choose the size randomly inside your `while` loop, then memory would be reallocated for every iteration.

Basically what I am getting at is that the `mask` matrix is unnecessary: it's only being used to store random values, which are being accessed sequentially and only once.  So why not just generate the random values as they are needed?  i.e.

```
for (size_t i = 0; i < input.n_elem; ++i)
{
  const double rand = math::Random();
  if (rand > ratio)
    output = input[i];
  else
    output = 0.0;
}
```

**Comment by zoq** [comment]
Actually, we also need the same random values (``mask``), in the backward method.

**Comment by rcurtin** [comment]
Ah in that case my idea is useless. :)

**Comment by zoq** [comment]
It looks like we can solve the issues by introducing a function ```void Ratio(double ratio)``` to set the ratio parameter and to set the scale parameter once the ratio is changed. 

```
void Ratio(double r)
{
	ratio = r;
	scale = 1.0 / (1.0 - ratio);	
}
```

 To avoid passing through the input matrix twice if the deterministic and rescale is true, we should rewrite the block as @rcurtin suggested:

```
if (deterministic)
{
  if (!rescale)
    output = input;
  else
    output = input * scale;
}
```

**Comment by zoq** [comment]
Thanks for the contribution. I made minor formatting and comment fixes in fdd2ae00c4359e1f3 let me know if I messed anything up.

**Pull request merged**
