### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by LilyWangLL**
Mlpack is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for mlpack and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build mlpack, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here](https://github.com/microsoft/vcpkg/blob/master/ports/mlpack/portfile.cmake) is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

### CODE REVIEW

**Review by rcurtin — COMMENTED** [review]
Awesome, thank you for adding this!  But, we just revamped our README in another PR, so do you think that you could add this blurb to the section `Installing mlpack` in `doc/quickstart/cpp.md`?  That section has details for installing the library for use in C++, and I think these instructions would be appropriate there.

Thanks!

**Comment by LilyWangLL** [comment]
> Awesome, thank you for adding this! But, we just revamped our README in another PR, so do you think that you could add this blurb to the section `Installing mlpack` in `doc/quickstart/cpp.md`? That section has details for installing the library for use in C++, and I think these instructions would be appropriate there.
> 
> Thanks!

Done. I have removed vcpkg instructions to `doc/quickstart/cpp.md`.

**Review by rcurtin — APPROVED** [review]
Awesome, thanks so much!

**Comment by rcurtin** [comment]
Thanks so much! :rocket:

**Pull request merged**
