### PR TITLE
Try to fix CI with CMake 3.20

### PR DESCRIPTION
**Pull request by rcurtin**
It looks like the CI builds have started failing, and this might be a factor of the Linux CI systems now using CMake 3.20.  Let's see if this simple fix fixes things... (it's kind of a shot in the dark).

### CODE REVIEW

**Comment by shrit** [comment]
I do have cmake 3.20.2, I tried to run CMake, it did give a warning about the extension of the files. However, make files are generated correctly and mlpack is compiling on Linux.
They might have changed something in the CI, or a path issue.

**Comment by shrit** [comment]
We need to see if Azure has been updated recently, or maybe they are resetting the path of the project, so it went out of scope.
not sure, the log are very far from being comprehensive

**Review by shrit — APPROVED** [review]

**Comment by rcurtin** [comment]
Yeah, I suppose this PR does not fix the issue, but it at least fixes some CMake warnings, so that is good at least. :)

**Comment by zoq** [comment]
I think it makes sense to track the issue down before we merge this, unless someone will open another PR?

**Comment by rcurtin** [comment]
Sure, no problem---let me keep working in this PR to reproduce and isolate and fix the issue.

**Comment by rcurtin** [comment]
Oh now this is a strange one... take a look at these two rules from `linux-steps.yaml`:

```
    curl https://data.kurg.org/armadillo-8.400.0.tar.xz | tar -xvJ && cd armadillo*
    cmake . && make && sudo make install && cd ..
```

The way that is written means that if the download fails, the directory will never be changed to the Armadillo source, and as a result what will be built in the second line is mlpack, not Armadillo!

And, sure enough, the wget fails:

```
$ wget https://data.kurg.org/armadillo-8.400.0.tar.xz
--2021-06-10 11:40:43--  https://data.kurg.org/armadillo-8.400.0.tar.xz
Resolving data.kurg.org (data.kurg.org)... 95.216.240.218
Connecting to data.kurg.org (data.kurg.org)|95.216.240.218|:443... connected.
ERROR: The certificate of ‘data.kurg.org’ is not trusted.
ERROR: The certificate of ‘data.kurg.org’ has expired.
The certificate has expired
```

@zoq I think if you can update the certificate on data.kurg.org, this will work. :)  But, nonetheless, I'll go ahead and update the script to be a bit safer...

**Comment by zoq** [comment]
Hm, I just restarted nginx, worked fine from my side, can you check it from your side again?

**Comment by rcurtin** [comment]
Nice, the wget works now---so I suspect CI will pass also. :+1:

**Review by shrit — APPROVED** [review]

**Review by zoq — APPROVED** [review]
Nice :+1:

**Comment by rcurtin** [comment]
Ok, cool, let's merge this then. :+1:

**Pull request merged**
