### PR TITLE
WeightSize function for LSTM, adaptive max and mean pooling layers

### PR DESCRIPTION
**Pull request by gauravghati**
In reference to issue [#2590](https://github.com/mlpack/mlpack/issues/2590)
Weight Size function for : 
- Adaptive mean pooling
- Adaptive max pooling 
- LSTM layer with tests.

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Looks good to me, let me know if you need any help to fix the merge conflict.

**Comment by gauravghati** [comment]
> Looks good to me, let me know if you need any help to fix the merge conflict.

done!

**Comment by gauravghati** [comment]
> Looks good to me, let me know if you need any help to fix the merge conflict.

done!

**Review by zoq — APPROVED** [review]
Thanks for putting this together, no more comments from my side.

**Comment by zoq** [comment]
Thanks again for the contribution.

**Pull request merged**
