### PR TITLE
Move to `MatType` in bias svd

### PR DESCRIPTION
**Pull request by shrit**
I did not touch the code related to ensmallen in this file since I have no idea why it is here, and what it is supposed to do.
Maybe it should be moved to ensmallen at some point ? also why the template parameters are not filled in ?
I did not chance what is related to shuffle since we still do not have it in bandicoot.

### CODE REVIEW

**Comment by shrit** [comment]
I am not adding anything to this one, it is ready for review

**Comment by shrit** [comment]
@rcurtin this is the code that is related to ensmallen I am referring to that I did not touch:
Maybe it has been left here by error ? 
https://github.com/mlpack/mlpack/blob/3e2a677704adcba6b989e06391c0eca4aaf9ef63/src/mlpack/methods/bias_svd/bias_svd_function_impl.hpp#L184-L221

**Comment by rcurtin** [comment]
Oh, I see, that is a custom implementation of those two ensmallen optimizers for this specific problem.  I am guessing this is done for some speed reason, but with a quick glance at the code I can't immediately identify what is being accelerated.  I think it would be worthwhile to compare whether that implementation really gives a speed benefit, but, that can happen some other time, no need to do that for this PR.

**Review by rcurtin — APPROVED** [review]
Awesome, looks good to me.  This will make my life easier when I document BiasSVD :smile:

**Pull request merged**
