### PR TITLE
Fixed markdown pipe symbol issue

### PR DESCRIPTION
**Pull request by adithya-tp**
> 2. Make it so that any time programInfo.documentation() is called from any function in src/mlpack/bindings/markdown/, any instances of | are properly escaped (assuming that escaping works with Kramdown). Note that in src/mlpack/bindings/markdown/, any functions just call out to different bindings languages.

This hopefully fixes issue #2270 (escaping does work in kramdown! :)). This should take care of the "|" symbol issue in the markdown for all bindings.

### CODE REVIEW

**Comment by birm** [comment]
This looks good from my end; what testing have you done?

**Comment by adithya-tp** [comment]
> This looks good from my end; what testing have you done?

Well, I made the markdown locally, and checked if the problems @rcurtin specified in the issue were resolved with the help of a kramdown editor. Since I saw they were, I went ahead with this pull request.

**Comment by adithya-tp** [comment]
Hey there @birm , sorry, but I just noticed I left an extra "endl" right after printing the description. Just a heads up before I make a commit to fix the same.

Also, thanks for the kind words. Means a lot to me :)

**Comment by adithya-tp** [comment]
Thank you, I've made the commit. :+1:

**Comment by favre49** [comment]
@rcurtin mlpack bot broken again? :)

**Pull request merged**
