### PR TITLE
Resolve appVeyor issues

### PR DESCRIPTION
**Pull request by Yashwants19**
While working on go bindings appVeyor fails. In this pr I am trying to resolve the issue.

### CODE REVIEW

**Comment by rcurtin** [comment]
Ah, synchronicity, I just had the same issue in #1971. :+1:  Looks like an ADL failure on the part of the Visual Studio compiler...

**Comment by Yashwants19** [comment]
Oh This seems to duplicate of #1971 should I closed this PR. By the way I got the same issue when I was working on cli-bindings for LinearSVM.

**Comment by zoq** [comment]
This also fixes potential issues in the gradient step, so I think it is reasonable to merge this one and merge #1971 afterwards.

**Comment by rcurtin** [comment]
Agreed, #1971 doesn't actually have all the fixes that you made here, so let's merge this one.  Thanks! :+1:

**Pull request merged**
