### PR TITLE
Move mlpack_allknn and mlpack_allkfn

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/mlpack/mlpack/issues/532

### CODE REVIEW

**Comment by rcurtin** [comment]
This looks good to me, but the only thing is that it doesn't preserve the `mlpack_allknn` and `mlpack_allkfn` programs for reverse compatibility.  Can you look into how that might be done with CMake?  (I'm thinking a symlink on Linux and probably something else is required on Windows.  Not sure.)

Also a couple other notes:

 * want to modify HISTORY.txt and src/mlpack/core.hpp to add your name to the list of contributors? (I'll also add that to about.html on the mlpack website, or you can submit a PR to that repository too)
 * if you can please have more descriptive commit messages, that would be helpful for later... right now your commit messages just say which files you modified, which is information I could get just by using git to print the changed files... :)
 * I didn't think about it, but we should probably make this change for the `mlpack_allkrann` program too (it should change to `mlpack_krann`).  We can do that in another PR or in this one---your call.

Thanks for taking the time to look into this!

**Comment by ivmarkp** [comment]
@rcurtin I am working on making changes for the `mlpack_allkrann`. Also, looking into what can be done to preserve backward compatibility.

**Comment by theaverageguy** [comment]
@ivmarkp Hey! I am just about to fix this. Can you take up some other issue? :) Maybe ask @rcurtin

**Comment by ivmarkp** [comment]
Oh, I was not aware if you were still active on this issue. Apologies on my part. 
May be I can work on some other issue.

**Comment by theaverageguy** [comment]
No problem @ivmarkp . You can get started with the issues labeled easy. For example Issue #380 is an easy one. 
The core members are very helpful and will guide you if you get stuck. :)

**Comment by ivmarkp** [comment]
Looks like issue #380 is already taken up. I wouldn't want to get into another conflict. Thanks anyway :)

**Comment by Kirizaki** [comment]
@ivmarkp If You really like You can work on this issue #380 

The problem is partly done. It's working in Linux but still there are other platforms.

**Comment by rcurtin** [comment]
This was solved in #618.

**Pull request closed without merging**
