### PR TITLE
[WIP] Inception Layer

### PR DESCRIPTION
**Pull request by walragatver**
This is currently just a wrapper around the `Concat` Layer.  The inception module is completely Implemented.
I will add a test soon.

### CODE REVIEW

**Comment by zoq** [comment]
Sorry, I forgot to post, what I worked on some time ago, haven't seen good results with the code so either there is something wrong with the implementation or the data is just too small; anyway, maybe this is still helpful.

```cpp
/**
 * @file inception_v1.hpp
 * @author Marcus Edel
 *
 * Definition of the Concat class, which acts as a concatenation contain.
 *
 * mlpack is free software; you may redistribute it and/or modify it under the
 * terms of the 3-clause BSD license.  You should have received a copy of the
 * 3-clause BSD license along with mlpack.  If not, see
 * http://www.opensource.org/licenses/BSD-3-Clause for more information.
 */
#ifndef MLPACK_METHODS_ANN_LAYER_INCEPTION_V1_HPP
#define MLPACK_METHODS_ANN_LAYER_INCEPTION_V1_HPP

#include <mlpack/core.hpp>

#include <boost/ptr_container/ptr_vector.hpp>

#include "layer_types.hpp"
#include "layer_visitor.hpp"

namespace mlpack {
namespace ann /** Artificial Neural Network. */ {

/**
 * Implementation of the Concat class. The Concat class works as a
 * feed-forward fully connected network container which plugs various layers
 * together.
 *
 * @tparam InputDataType Type of the input data (arma::colvec, arma::mat,
 *         arma::sp_mat or arma::cube).
 * @tparam OutputDataType Type of the output data (arma::colvec, arma::mat,
 *         arma::sp_mat or arma::cube).
 */
template <
    typename InputDataType = arma::mat,
    typename OutputDataType = arma::mat
>
class InceptionV1
{
 public:
  /**
   * Create the Concat object using the specified parameters.
   *
   * @param model Expose the all network modules.
   * @param model Merge the error in the backward pass.
   */
  InceptionV1(const size_t inSize,
              const std::vector<size_t>& outSize,
              const std::vector<size_t>& kernelSize,
              const std::vector<size_t>& kernelStride,
              const std::vector<size_t>& reduceSize,
              const std::vector<size_t>& reduceStride,
              const size_t inputWidth = 0,
              const size_t inputHeight = 0) :
      inSize(inSize),
      inputWidth(inputWidth),
      inputHeight(inputHeight),
      model(true),
      outputWidth(0),
      outputHeight(0),
      moduleOutSize(0)
  {
    parameters.set_size(0, 0);

    for (size_t i = 0, j = 3; i < kernelSize.size(); ++i, j += 2)
    {
      Sequential<>* reduce = new Sequential<>();
      reduce->Add<Convolution<> >(inSize, reduceSize[i], 1, 1,
        reduceStride[i], reduceStride[i]);
      reduce->Add<ReLULayer<> >();

      reduce->Add<Convolution<> >(reduceSize[i], outSize[i],
          kernelSize[i], kernelSize[i], kernelStride[i], kernelStride[i],
          std::floor(kernelSize[i] / 2), std::floor(kernelSize[i] / 2));

      moduleOutSize += outSize[i];
      reduce->Add<ReLULayer<> >();

      network.push_back(reduce);
    }

    Sequential<>* poolingModule = new Sequential<>();
    poolingModule->Add<MaxPooling<> >(3, 3, 1, 1);

    if (reduceSize.size() > kernelSize.size())
    {
      poolingModule->Add<Convolution<> >(inSize, reduceSize[kernelSize.size()],
          1, 1, reduceStride[kernelSize.size()],
          reduceStride[kernelSize.size()]);

      poolingModule->Add<ReLULayer<> >();

      moduleOutSize += reduceSize[kernelSize.size()];
    }

    network.push_back(poolingModule);

    if (reduceSize.size() > (kernelSize.size() + 1))
    {
      Sequential<>* reduce = new Sequential<>();
      reduce->Add<Convolution<> >(inSize, reduceSize[kernelSize.size() + 1],
        1, 1, reduceStride[kernelSize.size() + 1],
        reduceStride[kernelSize.size() + 1]);

      moduleOutSize += reduceSize[kernelSize.size() + 1];
      reduce->Add<ReLULayer<> >();

      network.push_back(reduce);
    }
  }

  /**
   * Ordinary feed forward pass of a neural network, evaluating the function
   * f(x) by propagating the activity forward through f.
   *
   * @param input Input data used for evaluating the specified function.
   * @param output Resulting output activation.
   */
  template<typename eT>
  void Forward(arma::Mat<eT>&& input, arma::Mat<eT>&& output)
  {
    outputWidth = 0;
    outputHeight = 0;
    for (size_t i = 0; i < network.size(); ++i)
    {
      boost::apply_visitor(ForwardVisitor(std::move(input), std::move(
        boost::apply_visitor(outputParameterVisitor, network[i]))),
        network[i]);

      size_t moduleOutputWidth = boost::apply_visitor(outputWidthVisitor,
          network[i]);
      if (moduleOutputWidth > outputWidth)
      {
        outputWidth = moduleOutputWidth;
      }

      size_t moduleOutputHeight = boost::apply_visitor(outputHeightVisitor,
          network[i]);
      if (moduleOutputHeight > outputHeight)
      {
        outputHeight = moduleOutputHeight;
      }
    }

    outputTemp = arma::zeros<arma::Cube<eT> >(outputWidth, outputHeight,
        moduleOutSize);
    for (size_t i = 0, s = 0; i < network.size(); ++i)
    {
      size_t moduleOutputWidth = boost::apply_visitor(outputWidthVisitor,
          network[i]);
      size_t moduleOutputHeight = boost::apply_visitor(outputHeightVisitor,
          network[i]);
      size_t moduleOutSize = boost::apply_visitor(outputParameterVisitor,
          network[i]).n_elem / (moduleOutputWidth * moduleOutputHeight);

      if (moduleOutputWidth != outputWidth ||
          moduleOutputHeight != outputHeight)
      {
        size_t rowOffset = std::floor(
            (outputWidth - moduleOutputWidth) / 2);
        size_t colOffset = std::floor(
            (outputHeight - moduleOutputHeight) / 2);

        outputTemp.subcube(rowOffset, colOffset, s, rowOffset +
            moduleOutputWidth - 1, colOffset + moduleOutputHeight - 1,
            s + moduleOutSize - 1) = arma::cube(
            boost::apply_visitor(outputParameterVisitor, network[i]).memptr(),
            moduleOutputWidth, moduleOutputHeight, moduleOutSize);
      }
      else
      {
        outputTemp.slices(s, s + moduleOutSize - 1) = arma::cube(
            boost::apply_visitor(outputParameterVisitor, network[i]).memptr(),
            outputWidth, outputHeight, moduleOutSize);
      }

      s += moduleOutSize;
    }

    output = arma::Mat<eT>(outputTemp.memptr(), outputTemp.n_elem, 1);
  }

  /**
   * Ordinary feed backward pass of a neural network, using 3rd-order tensors as
   * input, calculating the function f(x) by propagating x backwards through f.
   * Using the results from the feed forward pass.
   *
   * @param input The propagated input activation.
   * @param gy The backpropagated error.
   * @param g The calculated gradient.
   */
  template<typename eT>
  void Backward(const arma::Mat<eT>&& /* input */,
                arma::Mat<eT>&& gy,
                arma::Mat<eT>&& g)
  {
    arma::cube mappedError = arma::cube(gy.memptr(), outputWidth, outputHeight,
        moduleOutSize);

    for (size_t i = 0, s = 0; i < network.size(); ++i)
    {
      size_t moduleOutputWidth = boost::apply_visitor(outputWidthVisitor,
          network[i]);
      size_t moduleOutputHeight = boost::apply_visitor(outputHeightVisitor,
          network[i]);
      size_t moduleOutSize = boost::apply_visitor(outputParameterVisitor,
          network[i]).n_elem / (moduleOutputWidth * moduleOutputHeight);

      arma::mat error;
      if (moduleOutputWidth != outputWidth ||
          moduleOutputHeight != outputHeight)
      {
        size_t rowOffset = std::floor(
            (outputWidth - moduleOutputWidth) / 2);
        size_t colOffset = std::floor(
            (outputHeight - moduleOutputHeight) / 2);

        arma::cube transformedError = mappedError.subcube(rowOffset, colOffset,
            s, rowOffset + moduleOutputWidth - 1, colOffset +
            moduleOutputHeight - 1, s + moduleOutSize - 1);

        error = arma::Mat<eT>(transformedError.memptr(),
            boost::apply_visitor(outputParameterVisitor, network[i]).n_elem, 1);
      }
      else
      {
        error = arma::Mat<eT>(mappedError.memptr() + (s *
            (moduleOutputWidth * moduleOutputHeight)),
            boost::apply_visitor(outputParameterVisitor, network[i]).n_elem, 1);
      }

      boost::apply_visitor(BackwardVisitor(std::move(boost::apply_visitor(
          outputParameterVisitor, network[i])), std::move(error), std::move(
          boost::apply_visitor(deltaVisitor, network[i]))), network[i]);

      if (i == 0)
      {
        g = boost::apply_visitor(deltaVisitor, network[i]);
      }
      else
      {
        g += boost::apply_visitor(deltaVisitor, network[i]);
      }

      s += moduleOutSize;
    }
  }

  /*
   * Calculate the gradient using the output delta and the input activation.
   *
   * @param input The input parameter used for calculating the gradient.
   * @param error The calculated error.
   * @param gradient The calculated gradient.
   */
  template<typename eT>
  void Gradient(arma::Mat<eT>&& /* input */,
                arma::Mat<eT>&& error,
                arma::Mat<eT>&& /* gradient */)
  {
    for (size_t i = 0; i < network.size(); ++i)
    {
      boost::apply_visitor(GradientVisitor(std::move(boost::apply_visitor(
          outputParameterVisitor, network[i])), std::move(error)), network[i]);
    }
  }

  /*
   * Add a new module to the model.
   *
   * @param layer The Layer to be added to the model.
   */
  template<typename LayerType>
  void Add(const LayerType& layer) { network.push_back(new LayerType(layer)); }

  /*
   * Add a new module to the model.
   *
   * @param args The layer parameter.
   */
  template <class LayerType, class... Args>
  void Add(Args... args) { network.push_back(new LayerType(args...)); }

  /*
   * Add a new module to the model.
   *
   * @param layer The Layer to be added to the model.
   */
  void Add(LayerTypes layer) { network.push_back(layer); }

  //! Return the model modules.
  std::vector<LayerTypes>& Model()
  {
    if (model)
    {
      return network;
    }

    return empty;
  }

  //! Return the initial point for the optimization.
  const arma::mat& Parameters() const { return parameters; }
  //! Modify the initial point for the optimization.
  arma::mat& Parameters() { return parameters; }

  arma::mat const& InputParameter() const { return inputParameter; }
  //! Modify the input parameter.
  arma::mat& InputParameter() { return inputParameter; }

  //! Get the output parameter.
  arma::mat const& OutputParameter() const { return outputParameter; }
  //! Modify the output parameter.
  arma::mat& OutputParameter() { return outputParameter; }

  //! Get the delta.e
  arma::mat const& Delta() const { return delta; }
  //! Modify the delta.
  arma::mat& Delta() { return delta; }

  //! Get the gradient.
  arma::mat const& Gradient() const { return gradient; }
  //! Modify the gradient.
  arma::mat& Gradient() { return gradient; }

  //! Get the input width.
  size_t const& InputWidth() const { return inputWidth; }
  //! Modify input the width.
  size_t& InputWidth() { return inputWidth; }

  //! Get the input height.
  size_t const& InputHeight() const { return inputHeight; }
  //! Modify the input height.
  size_t& InputHeight() { return inputHeight; }

  //! Get the output width.
  size_t const& OutputWidth() const { return outputWidth; }
  //! Modify the output width.
  size_t& OutputWidth() { return outputWidth; }

  //! Get the output height.
  size_t const& OutputHeight() const { return outputHeight; }
  //! Modify the output height.
  size_t& OutputHeight() { return outputHeight; }

 private:
  //! Locally-stored number of input units.
  size_t inSize;

  //! Locally-stored number of output units.
  size_t outSize;

  //! Locally-stored input width.
  size_t inputWidth;

  //! Locally-stored input height.
  size_t inputHeight;

  //! Parameter which indicates if the modules should be exposed.
  bool model;

  //! If true merge the error in the backward pass.
  bool same;

  //! Locally-stored network modules.
  std::vector<LayerTypes> network;

  //! Locally-stored model parameters.
  arma::mat parameters;

  //! Locally-stored delta visitor.
  DeltaVisitor deltaVisitor;

  //! Locally-stored output parameter visitor.
  OutputParameterVisitor outputParameterVisitor;

  //! Locally-stored delete visitor.
  DeleteVisitor deleteVisitor;

  //! Locally-stored empty list of modules.
  std::vector<LayerTypes> empty;

  //! Locally-stored delta object.
  arma::mat delta;

  //! Locally-stored input parameter object.
  arma::mat inputParameter;

  //! Locally-stored output parameter object.
  arma::mat outputParameter;

  //! Locally-stored gradient object.
  arma::mat gradient;

  //! Locally-stored transformed output parameter.
  arma::cube outputTemp;

  //! Locally-stored output width.
  size_t outputWidth;

  //! Locally-stored output height.
  size_t outputHeight;

  //! Locally-stored output width visitor.
  LastOutputWidthVisitor outputWidthVisitor;

  //! Locally-stored output height visitor.
  LastOutputHeightVisitor outputHeightVisitor;

  //! Locally-stored moudle output size.
  size_t moduleOutSize;
}; // class InceptionV1


} // namespace ann
} // namespace mlpack

#endif
```

```cpp
BOOST_AUTO_TEST_CASE(GoogLeNetTest)
{
  arma::mat XS;
  XS.load("mnist_first250_training_4s_and_9s.arm");

  // Normalize each point since these are images.
  arma::uword nPoints = XS.n_cols;
  arma::mat X(224 * 224, nPoints);
  for (arma::uword i = 0; i < nPoints; i++)
  {
    XS.col(i) /= norm(XS.col(i), 2);
    X.col(i).subvec(0, XS.col(i).n_elem - 1) = XS.col(i);
  }

  // Build the target matrix.
  arma::mat Y = arma::zeros<arma::mat>(1, nPoints);
  for (size_t i = 0; i < nPoints; i++)
  {
    if (i < nPoints / 2)
    {
      Y(i) = 4;
    }
    else
    {
      Y(i) = 8;
    }
  }


  size_t nClasses = 10;


  // Main0 subnetwork.
  Sequential<>* main0 = new Sequential<>();
  main0->Add<Convolution<> >(1, 64, 7, 7, 2, 2, 3, 3, 224, 224);
  main0->Add<ReLULayer<> >();
  main0->Add<Convolution<> >(64, 64, 1, 1);
  main0->Add<ReLULayer<> >();

  main0->Add<MaxPooling<> >(3, 3, 2, 2, false);
  main0->Add<Convolution<> >(64, 64, 1, 1);
  main0->Add<ReLULayer<> >();
  main0->Add<Convolution<> >(64, 192, 3, 3, 1, 1, 1, 1);
  main0->Add<ReLULayer<> >();
  main0->Add<MaxPooling<> >(3, 3, 2, 2, false);

  // main0:add(inc(192, {{ 64}, { 96,128}, {16, 32}, {3, 32}})) -- 4,5 / 3(a)
  InceptionV1<>* inception3a = new InceptionV1<>(192, {128, 32}, {3, 5}, {1, 1}, {96, 16, 32, 64}, {1, 1, 1, 1}, 0, 0);
  main0->Add(inception3a);
  InceptionV1<>* inception3b = new InceptionV1<>(256, {192, 96}, {3, 5}, {1, 1}, {128, 32, 64, 128}, {1, 1, 1, 1}, 0, 0);
  main0->Add(inception3b);
  main0->Add<MaxPooling<> >(3, 3, 2, 2, false);
  InceptionV1<>* inception4a = new InceptionV1<>(480, {208, 48}, {3, 5}, {1, 1}, {96, 16, 64, 192}, {1, 1, 1, 1}, 0, 0);
  main0->Add(inception4a);

  // Main1 subnetwork.
  Sequential<>* main1 = new Sequential<>();

  InceptionV1<>* inception4b = new InceptionV1<>(512, {224, 64}, {3, 5}, {1, 1}, {112, 24, 64, 160}, {1, 1, 1, 1}, 0, 0);
  main1->Add(inception4b);
  InceptionV1<>* inception4c = new InceptionV1<>(512, {256, 64}, {3, 5}, {1, 1}, {128, 24, 64, 128}, {1, 1, 1, 1}, 0, 0);
  main1->Add(inception4c);
  InceptionV1<>* inception4d = new InceptionV1<>(512, {288, 64}, {3, 5}, {1, 1}, {144, 32, 64, 112}, {1, 1, 1, 1}, 0, 0);
  main1->Add(inception4d);

  // Main2 subnetwork.
  Sequential<>* main2 = new Sequential<>();
  InceptionV1<>* inception4e = new InceptionV1<>(528, {320, 128}, {3, 5}, {1, 1}, {160, 32, 128, 256}, {1, 1, 1, 1}, 0, 0);
  main2->Add(inception4e);
  main2->Add<MaxPooling<> >(3, 3, 2, 2, false);
  InceptionV1<>* inception5a = new InceptionV1<>(832, {320, 128}, {3, 5}, {1, 1}, {160, 32, 128, 256}, {1, 1, 1, 1}, 0, 0);
  main2->Add(inception5a);
  InceptionV1<>* inception5b = new InceptionV1<>(832, {384, 128}, {3, 5}, {1, 1}, {192, 48, 128, 384}, {1, 1, 1, 1}, 0, 0);
  main2->Add(inception5b);

  // SoftMax0 subnetwork.
  Sequential<>* softMax0 = new Sequential<>();
  softMax0->Add<MeanPooling<> >(5, 5, 3, 3);
  softMax0->Add<Convolution<> >(512, 128, 1, 1);
  softMax0->Add<Linear<> >(128 * 4 * 4, 1024);
  softMax0->Add<ReLULayer<> >();
  softMax0->Add<Dropout<> >(0.7);
  softMax0->Add<Linear<> >(1024, nClasses);
  softMax0->Add<ReLULayer<> >();
  softMax0->Add<LogSoftMax<> >();

  // SoftMax1 subnetwork.
  Sequential<>* softMax1 = new Sequential<>();
  softMax1->Add<MeanPooling<> >(5, 5, 3, 3);
  softMax1->Add<Convolution<> >(528, 128, 1, 1);
  softMax1->Add<Linear<> >(128 * 4 * 4, 1024);
  softMax1->Add<ReLULayer<> >();
  softMax1->Add<Dropout<> >(0.7);
  softMax1->Add<Linear<> >(1024, nClasses);
  softMax1->Add<ReLULayer<> >();
  softMax1->Add<LogSoftMax<> >();

  // SoftMax2 subnetwork.
  Sequential<>* softMax2 = new Sequential<>();
  softMax2->Add<MeanPooling<> >(7, 7, 1, 1);
  softMax2->Add<Dropout<> >(0.4);
  softMax2->Add<Linear<> >(1024, nClasses);
  softMax2->Add<ReLULayer<> >();
  softMax2->Add<LogSoftMax<> >();

  // Macro blocks.
  Sequential<>* block2 = new Sequential<>();
  block2->Add(main2);
  block2->Add(softMax2);

  Concat<>* split1 = new Concat<>(true, false);
  split1->Add(block2);
  split1->Add(softMax1);

  Sequential<>* block1 = new Sequential<>();
  block1->Add(main1);
  block1->Add(split1);

  Concat<>* split0 = new Concat<>(true, false);
  split0->Add(block1);
  split0->Add(softMax0);

  ConcatPerformance<> performance(4);

  FFN<ConcatPerformance<> > model(std::move(performance));
  model.Add<IdentityLayer<> >();
  model.Add(main0);
  model.Add(split0);
  model.Add<Join<> >();
  // model.Add<Select<> >(0, 3 * nClasses);


  RMSprop<decltype(model)> opt(model, 0.01, 0.88, 1e-8, 3000, -1);
  model.Train(std::move(X), std::move(Y), opt);



  arma::mat predictionTemp;
  model.Predict(X, predictionTemp);


  for (size_t i = 0; i < predictionTemp.n_cols; ++i)
  {

    arma::colvec foo = predictionTemp.col(i);
    foo = foo.subvec(0, 9);

    std::cout << foo << std::endl;

    // std::cout << foo << std::endl;
    // prediction(i) = arma::as_scalar(arma::find(
    //     arma::max(predictionTemp.col(i)) == predictionTemp.col(i), 1)) + 1;
  }
}

BOOST_AUTO_TEST_CASE(InceptionNetworkTest) 
{
  arma::mat X;
  X.load("mnist_first250_training_4s_and_9s.arm");

  // Normalize each point since these are images.
  arma::uword nPoints = X.n_cols;
  for (arma::uword i = 0; i < nPoints; i++)
  {
    X.col(i) /= norm(X.col(i), 2);
  }

  // Build the target matrix.
  arma::mat Y = arma::zeros<arma::mat>(1, nPoints);
  for (size_t i = 0; i < nPoints; i++)
  {
    if (i < nPoints / 2)
    {
      Y(i) = 4;
    }
    else
    {
      Y(i) = 9;
    }
  }

  FFN<NegativeLogLikelihood<> > model;
  model.Add<IdentityLayer<> >();
  model.Add<Convolution<> >(1, 1, 5, 5, 1, 1, 2, 2, 28, 28);
  model.Add<ReLULayer<> >();
  model.Add<MaxPooling<> >(2, 2, 2, 2);
  model.Add<Convolution<> >(1, 2, 5, 5, 1, 1, 2, 2, 0, 0);
  model.Add<ReLULayer<> >();
  model.Add<MaxPooling<> >(2, 2, 2, 2);

  InceptionV1<>* inception1 = new InceptionV1<>(2, {32, 48}, {5, 3}, {1, 1}, {48, 64, 32, 32}, {1, 1, 1, 1});

  model.Add(inception1);
  model.Add<Linear<> >(7056, 10);
  model.Add<LogSoftMax<> >();

  // RMSprop<decltype(model)> opt(model, 0.01, 0.88, 1e-8, 5000, -1);

  // model.Train(std::move(X), std::move(Y), opt);


  RMSprop<decltype(model)> opt(model, 0.01, 0.88, 1e-8, 300, -1);

  for (size_t i = 0; i < 20000; ++i)
  {
    model.Train(std::move(X), std::move(Y), opt);

    arma::mat predictionTemp;
    model.Predict(X, predictionTemp);
    arma::mat prediction = arma::zeros<arma::mat>(1, predictionTemp.n_cols);

    for (size_t i = 0; i < predictionTemp.n_cols; ++i)
    {
      prediction(i) = arma::as_scalar(arma::find(
          arma::max(predictionTemp.col(i)) == predictionTemp.col(i), 1)) + 1;
    }

    size_t error = 0;
    for (size_t i = 0; i < X.n_cols; i++)
    {
      if (prediction(i) == Y(i))
      {
        error++;
      }
    }

    std::cout << "error: " << error << std::endl;
    std::cout << "samples: " << X.n_cols << std::endl;
    std::cout << "----------------------------------------------\n";
  }
  // double classificationError = 1 - double(error) / X.n_cols;


}
```

**Comment by walragatver** [comment]
Hi @zoq,
Thanks for the code, I have found some mistakes in my implementation with the help of it. 
I was just having some doubts. Should we allow `the user` to provide the `kernel size` and `stride`?
I have implemented straight away using the `kernel size` mentioned in the paper over here.
https://arxiv.org/abs/1409.4842
So just let me know whether I should add the option.

**Comment by zoq** [comment]
In the paper they used a stride parameter for different layer as well:

stride

maybe I missed something?

**Comment by walragatver** [comment]
Hi @zoq,
Sorry for the slow response. I didn't get what you intended to say. 
If we look into the table you have shared. Then we can see that every layer(In the Inception Layer) has a fix kernel size and stride.
But in the following code (which you shared) we take the `kernel size` and `stride` explicitly. So I was asking that, should I also give an option to take `kernel size` and `stride` from the user? (I have currently not done that.)

> ```c++
>               const std::vector<size_t>& kernelSize,
>               const std::vector<size_t>& kernelStride,
>               const std::vector<size_t>& reduceSize,
>               const std::vector<size_t>& reduceStride,
> ```

Also, I was thinking to `add different versions` of the inception module. So I was thinking to add one parameter in the layer namely `version` which will define the version of the `Inception Module` and then we will construct the layer based on version. Its default will be 1. Just let me know what you think.

**Comment by zoq** [comment]
Ahh, sorry I was thinking you are using the default stride value for each layer. I like the idea to wrap the parameters for the user, there might be need to overwrite the values, so I guess we could provide that option.

About the versions, what about we use a template parameter for this, that way we could provide an alias for the template class:

```c++
template<int version = 1>
class Inception
{
};

using InceptionV1 = Inception<1>;
using InceptionV2 = Inception<2>;
```

If we do this a user can just use ``InceptionV1`` and etc. Let me know what you think.

**Comment by rcurtin** [comment]
This code touches the ANN code, and there was recently a big refactoring of the ANN code in #2259, so be sure to merge the master branch into your branch here to make sure that nothing will fail if this PR is merged. :+1: (I'm pasting this message into all possibly relevant PRs.)

**Comment by hello-fri-end** [comment]
@zoq @walragatver: Hi! Is anyone currently working on Inception V2 & V3?

**Comment by hello-fri-end** [comment]
@zoq @conradsnicta Can we keep this one open? I can finish the pending work here after #2848 gets merged/reviewed.

**Comment by conradsnicta** [comment]
@hello-fri-end This hasn't had any substantial activity for over 2 years (since 2019), and may require non-trivial refactoring due to massive changes in the ANN code.  It may be more productive to open a fresh PR with a clean start and adapt the work from here.  However, if you want to do the refactoring or otherwise continue, please reopen this once #2963 is done.

**Pull request closed without merging**
