### PR TITLE
Fix macOS Python build on Azure

### PR DESCRIPTION
**Pull request by zoq**

### CODE REVIEW

**Comment by zoq** [comment]
Great the build is fixed, but now we have a memory access violation in `CFTest/CFGetRecommendationsAllUsersRegSVDTest`. Will look into it.

**Comment by zoq** [comment]
Hm, looks like the macOS issue resolved itself.

**Comment by zoq** [comment]
Nevermind, it's back again.

**Review by Yashwants19 — APPROVED** [review]
Thank you for looking into this. You are the best :+1:

**Comment by jeffin143** [comment]
@zoq  ? should we merge this in ?

**Comment by zoq** [comment]
Yep, feel free to hit the merge button.

**Pull request merged**
