### PR TITLE
Some Style Fixes.

### PR DESCRIPTION
**Pull request by kartikdutt18**
Hey everyone,
These are simple style fixes in the cellbound_impl.hpp. Other than this, I removed an unnecessary "else" statement from the codebase. Kindly let me know what you think.
Regards.

### CODE REVIEW

**Comment by birm** [comment]
Do we need a 'refactor' tag to differentiate from documentation?

**Comment by kartikdutt18** [comment]
> mlpack's style opinion on else after return, but I do think it looks good. 

Makes sense. Personally an extra, "else statement" felt redundant so I removed it. I found this [article](https://arne-mertz.de/2016/12/early-return/) for it. Let me know if we should add something like this to Style Guide for future reference.

**Comment by kartikdutt18** [comment]
Makes sense.

**Comment by rcurtin** [comment]
I'd say, if there is enough interest in modifying the style guide, we should probably just open an issue for discussion and then modify the style guide (or not) depending on the results of that discussion.  Up to you. :+1:

**Comment by kartikdutt18** [comment]
Thanks a lot everyone for the review, opened #2496 for further discussion.

**Comment by zoq** [comment]
> Thanks a lot everyone for the review, opened #2496 for further discussion.

Great thanks!

**Pull request merged**
