### PR TITLE
Added zip_safe to setup options in setup.py.in

### LINKED ISSUE #1231: Python import takes too long.
I built mlpack from source according to the documentation.
Importing mlpack in python 2.7 takes too much time, I timed it:
It takes about 30 seconds to import mlpack or any of its specific parts like knn.
Is it due to it being kept as an egg file in python dist-packages?

### PR DESCRIPTION
**Pull request by akhandait**
Resolves #1231
Here is the documentation : http://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag
It now extracts the files in dist-packages and import time in python is drastically reduced.

### CODE REVIEW

**Comment by akhandait** [comment]
What can I do to pass the travis check?

**Comment by rcurtin** [comment]
Don't worry about the failing travis build; I have seen this in some other PRs too.  I will be looking into it later today and I'll let you know what I find.  Also #1221 is open to try and help with the random Travis builds that are not starting correctly.

I think this change is just fine, but let me double-check that the zip_safe change isn't affecting the Python build by hand after I debug the other Python failure and then we can go ahead and merge.

**Comment by akhandait** [comment]
It will be nice to have my name in the list of contributors. Will you add it or should I add it myself and commit it here?

**Comment by rcurtin** [comment]
If you can just add it here as a commit, that would be great. :)

**Comment by rcurtin** [comment]
Thanks for the nice contribution! :)

**Pull request merged**
