### PR TITLE
Cosine distance metric

### PR DESCRIPTION
**Pull request by jeffin143**
I have implemented Cosine Similarity Metric, Cosine similarity is generally used as a metric for measuring distance when the magnitude of the vectors does not matter. 

Post Gsoc, Mlpack will have string utilities and thus Cosine similarity metric could be very useful since, it is used often to evaluate how 2 documents are related.

Optionally We might also want to apply cosine similarity for cases where some properties of the instances make so that the weights might be larger without meaning anything different. Sensor values that were captured in various lengths (in time) between instances could be such an example.

You could find relevance of cosine similarity in this [article](https://cmry.github.io/notes/euclidean-v-cosine), Under Cosine in Action - we could find an implementation of it.

### CODE REVIEW

**Comment by ShikharJ** [comment]
I don't know why, but again I feel this is too fundamental to not have been implemented somewhere within `mlpack` already.

**Comment by jeffin143** [comment]
> I don't know why, but again I feel this is too fundamental to not have been implemented somewhere within `mlpack` already.

@ShikharJ , What about `Jaccard similarity`. Would it be good to have that in our codebase ?

**Comment by rcurtin** [comment]
I haven't looked at the code to see what is implemented, but:

(a) cosine similarity is not actually a metric.
(b) we should have it already in `kernels/`.

Maybe there is some functionality difference, so perhaps we can improve that implementation if needed (like I said I haven't looked at the code here).

**Comment by jeffin143** [comment]
> I haven't looked at the code to see what is implemented, but:
> 
> (a) cosine similarity is not actually a metric.
> (b) we should have it already in `kernels/`.
> 
> Maybe there is some functionality difference, so perhaps we can improve that implementation if needed (like I said I haven't looked at the code here).

@rcurtin , Yes its there in kernels , I would go ahead and close it, Look same implementation wise :)

**Pull request closed without merging**
