### PR TITLE
Implemented multi-dimensional scaling

### PR DESCRIPTION
**Pull request by awhitesong**
Hi, 
I have created the implementation for metric MDS with euclidean dissimilarity. Scope for non metric and other dissimiliarity functions has been provided for now which could be extended later. The papers used for this have been mentioned in the comments documentaton too.

For testing it separately, i calculated the dissimilarity of input dataset and applied MDS to get the lower-dimensional datapoints. Then again calulated the dissimilarity matrix with reduced dataset. Both the dissimilarity matrices are approximately coming the same. So i guess the MDS code is working fine.I tested the working by calling these functions separately and have not run the code for executable(mds_main) though.

Also tried testing in comparison to scikit. But i guess scikit is using a different implementation internally for MDS since their answers for reduced data come different everytime.

So later, a few changes can be incorporated if needed:
1. Implementing non-metric
2. Implmenting bunch of other distance metrics than euclidean, since with euclidean MDS is approximately equal to PCA.
3. Returning the stress value and using other loss functions(like kruskal's).
4. Computing the r-squares etc for reliability testing, as mentioned on this page http://en.wikipedia.org/wiki/Multidimensional_scaling 

Please see or test for any changes. 
Thanks.

### CODE REVIEW

**Comment by rcurtin** [comment]
Thanks for the contribution!  I haven't looked through it yet, but could you write some tests (like those currently found in `src/mlpack/tests/`) so that we have a way to verify MDS is working right?

**Comment by awhitesong** [comment]
Hi, 
Just included the test files. The file is testing against the implementation of matlab and giving accurate results. Also included Kruskal's stress for estimating MDS test.

Thanks.

**Comment by rcurtin** [comment]
Sorry for the slow response here.  I hope to have a chance to look soon, but I can't promise anything with paper deadlines coming up.  I think maybe we can expand on the tests a little bit; could you consider corner cases?  For example, what happens if a user passes an invalid number of dimensions or invalid data to the reduce() function?

Another useful test to add might be to take a dataset and pad it with many dimensions which are all zero.  In this case, you should be able to reduce it to the original number of dimensions while preserving the exact dissimilarity matrix.

If you could please also take a look through the style guidelines (which are mostly complete), and make those changes, it would be helpful. :)  https://github.com/mlpack/mlpack/wiki/StyleGuidelines

**Comment by hussain7** [comment]
Hi Ryan ,
I was just wondering why this has not been continued again ? Can I work on the missing things so that it can be added ?

Regards
Muzahid

**Comment by rcurtin** [comment]
Hi Muzahid, I think that I simply ran out of time.  You are welcome to take up this issue and add the missing things and I can try to revisit it in the future.

**Pull request closed without merging**
