### PR TITLE
CMake Generated VS13 project fails to build

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/mlpack/mlpack/issues/508

### CODE REVIEW

**Comment by rcurtin** [comment]
Hi, thanks for the PR.  Have you tested this to ensure that it works?

**Comment by theaverageguy** [comment]
@rcurtin Why is the build failing?

**Comment by rcurtin** [comment]
Did you read the error message?  You should be able to reproduce this problem when you configure mlpack on your machine.  There is a syntax error.

**Comment by rcurtin** [comment]
Closing for inactivity.  Please feel free to reopen if you can test this.

**Pull request closed without merging**
