### PR TITLE
Remove execution rights from header files

### PR DESCRIPTION
**Pull request by shrit**
Signed-off-by: Omar Shrit <shrit@lri.fr>

### CODE REVIEW

**Comment by jeffin143** [comment]
Thanks for opening PR, But i can find any diff

**Comment by jeffin143** [comment]
What a great pick , I didn't notice it :)

**Comment by shrit** [comment]
@rcurtin, You are welcom, I had sent a similar pull request for ensmallen.
I do not think there is any thing left with execution permission.

**Comment by rcurtin** [comment]
Thanks again @shrit!

**Pull request merged**
