### PR TITLE
Smooth L1 loss

### PR DESCRIPTION
**Pull request by codeboy5**
Addition of Smooth L1 Loss function.

### CODE REVIEW

**Comment by mrityunjay-tripathi** [comment]
Hello @codeboy5
We already have this loss function.
See #2199

**Comment by codeboy5** [comment]
> Hello @codeboy5
> We already have this loss function.
> See #2199

Sorry, did not notice it.

**Comment by zoq** [comment]
@codeboy5 don't think we can combine the two PR's, so should we close this one? Also, feel free to take a look at #2199 I guess you might be able to provide some feedback about the implementation there.

**Comment by codeboy5** [comment]
> @codeboy5 don't think we can combine the two PR's, so should we close this one? Also, feel free to take a look at #2199 I guess you might be able to provide some feedback about the implementation there.

Yeah I don't there is any other option. 
It was nice working on it as my first issue tho.

**Comment by zoq** [comment]
Yeah, the implementation looks good.

**Pull request closed without merging**
