### PR TITLE
Improved variable names in all loss functions

### PR DESCRIPTION
**Pull request by RishabhGarg108**
In accordance with #2005 , I have made changes to the variable names of the remaining loss functions as discussed in #2714 .
Sine there are so many files that I have changed, so in order to make the review process easy, I have made 1 commit for each loss function. Hope that might help :)

### CODE REVIEW

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Let's see if the latex build is fixed.

**Review by shrit — COMMENTED** [review]
Everything looks good to me, also the Latex error has been fixed.
@zoq I can not understand the Static analysis error, it seems to be a bug.

**Comment by zoq** [comment]
> Everything looks good to me, also the Latex error has been fixed.
> @zoq I can not understand the Static analysis error, it seems to be a bug.

Yes, that is a false warning, save to be ignored.

**Review by zoq — APPROVED** [review]
This looks great to me, thanks for taking the time to improve the naming.

**Review by shrit — APPROVED** [review]
Nothing from my side, thanks for the contribution

**Comment by RishabhGarg108** [comment]
Thanks to both of you for taking time to review this big PR. :)

**Comment by zoq** [comment]
Thanks again for putting this together.

**Pull request merged**
