### PR TITLE
Added LeakyReLU layer and its tests

### PR DESCRIPTION
**Pull request by awhitesong**
@zoq All tests passing on my system.

### CODE REVIEW

**Comment by awhitesong** [comment]
Hi @zoq do i need to make any further changes here ? If its fine then i'll start working on another issue. thanks.

**Comment by zoq** [comment]
Sorry, but I didn't have time yet to look over the code; probably tomorrow.

**Comment by zoq** [comment]
The code looks good to me, once you solved the minor issues, I'll go and merge that in.

**Comment by awhitesong** [comment]
@zoq Done. Build for other probabilistic cases failing. LeakyReLU passed

**Comment by awhitesong** [comment]
@zoq Is it good to be merged? Should i start working on other issue?

**Comment by zoq** [comment]
Can you go over the modifications I made it 971213a377e27ac41 and do the same modifications for the LeakyReLU layer?

**Comment by awhitesong** [comment]
@zoq Made the required changes.

**Comment by zoq** [comment]
Hm, this pull request looks strange, why does it contain merge conflicts? Maybe you can open a new pull request or fix this one?

**Comment by awhitesong** [comment]
@zoq  i guess i've fixed the merge conflicts (It was because my LeakyReLU branch didn't have Hardtanh file which was recently merged in upstream/master?). Its showing "This branch has no conflicts with the base branch", is it showing problems while merging?

**Comment by zoq** [comment]
It looks like it first reverts the last commits: https://github.com/awhitesong/mlpack/commit/858e01088867d17cb7f1a3d740cd98234606f455 So I thought, it would be better to just open a new pull request.

**Comment by awhitesong** [comment]
@zoq I did a reverse merge from upstream/master into LeakyReLU branch (instead of rebase) to update it, that's why its showing previous changes as well. Its fine to merge, but i still created a separate pull request as you said though. Thanks.

**Pull request closed without merging**
