### PR TITLE
JOSS documentation fixes

### PR DESCRIPTION
**Pull request by rcurtin**
This is a collection of fixes for the issues brought up by @rasbt:

 * Clarify how to use the Python bindings without installation and mention when `LD_LIBRARY_PATH` might be needed. (#1416)
 * Print `output = ` before automatically-generated calls to Python bindings in documentation. (#1418)
 * Change name of `perceptron` variable in the perceptron code documentation. (#1419)
 * Rewrite the kRANN documentation since it was written specifically for command-line bindings and never updated.
 * Write the random forest documentation since it seems it never actually got written.

Since these fix some fairly important documentation issues from the Python angle, I would have no problem doing a release after this merge as mlpack 3.0.2.

### CODE REVIEW

**Comment by rcurtin** [comment]
Ok, I will go ahead and merge this in three days.

**Comment by rasbt** [comment]
That's great, as far as I can tell from the changelog, it addresses all the issues that came up during the JOSS review :).

Maybe I am too early, but in case this is not a temporary thing, the link's (e.g., under Python Bindings) don't work, yet:

```
Not Found

The requested URL /docs/mlpack-3.0.2/python/perceptron.html was not found on this server.
```

**Comment by rcurtin** [comment]
Yep, sorry about that---I was in the process of doing the release and accidentally changed the links on the homepage before the documentation was built, and then was interrupted by dinner and a movie. :)

The documentation works now, and addresses the various issues that you pointed out.  Thank you again!

**Comment by rasbt** [comment]
No worries, and it works fine now!

**Pull request merged**
