### PR TITLE
Use HDF 1.10 API instead of 1.08.

### PR DESCRIPTION
**Pull request by rcurtin**
This is a based on a [suggestion](https://github.com/mlpack/mlpack/commit/682d25f69b14b159a2ff44393aaa638f3a14588d#commitcomment-38061822).  Thanks @conradsnicta! :+1:

### CODE REVIEW

**Comment by conradsnicta** [comment]
For a long term solution it would be useful to find an alternative implementation of HDF5.  Even a home-made bare bones version is likely to be preferable.

Given the track record with the official HDF5 library, it's almost guaranteed that there will be more API breaks in the future.  Official "workarounds" (*) like `H5_USE_18_API` and `H5_USE_110_API` are adding to the technical debt within the HDF5 library. Eventually this debt will be too much to maintain effectively, which means there is a risk that these workarounds may stop working.

(*) In this context the term "workaround" is generous; the term "hack" is probably more appropriate. An even more precise description would be "sweeping poor design choices under the rug".

**Comment by rcurtin** [comment]
> For a long term solution it would be useful to find an alternative implementation of HDF5. Even a home-made bare bones version is likely to be preferable.
> 
> Given the track record with the official HDF5 library, it's almost guaranteed that there will be more API breaks in the future. Official "workarounds" (*) like `H5_USE_18_API` and `H5_USE_110_API` are adding to the technical debt within the HDF5 library. Eventually this debt will be too much to maintain effectively, which means there is a risk that these workarounds may stop working.
> 
> (*) In this context the term "workaround" is generous; the term "hack" is probably more appropriate. An even more precise description would be "sweeping poor design choices under the rug".

I agree, if another implementation is available, it would probably save us a lot of headache...

**Comment by favre49** [comment]
Any idea what happened to the Linux builds here?

**Comment by rcurtin** [comment]
I was wondering the same thing...  I restarted those builds, but they're still queued.

**Comment by Yashwants19** [comment]
Is it related to system.pullRequest.sourceBranch : hdf-110 in https://dev.azure.com/mlpack/mlpack/_build/results?buildId=1198&view=logs&jobId=6adfc145-8b38-5626-f6fc-b7e6c11304a1&j=78d03e4d-8ad3-5491-4bd6-a628ce23cf22 ?

**Comment by zoq** [comment]
> I was wondering the same thing... I restarted those builds, but they're still queued.

Users may experience build delays due to capacity constraints due to increased demand from the global pandemic. See this link for more detail: [link](https://azure.microsoft.com/en-us/blog/our-commitment-to-customers-and-microsoft-cloud-services-continuity/)

**Comment by favre49** [comment]
You're right, the pipeline now says 
` ##[error]An error occurred while provisioning resources (Error Type: Disconnect). `

I think we can merge this anyway though

**Comment by rcurtin** [comment]
Agreed, it really shouldn't make a difference.  Let's hope it doesn't cause any problems... :)

**Pull request merged**
