### PR TITLE
Documentation about the input weight and height of the Convolution layer

### PR DESCRIPTION
**Pull request by InterTriplete2010**
Apologies if my pull request is not orthodox, but this is the first time I do it. I would like to add more info to the documentation of the <convolution> layer regarding input **_weight_** and **_height_** to clarify how the input matrix is treated, especially if it is rectangular. 

Say that I pass a matrix M(2744x100) to add<Convolution>, which I have obtained from "flattening" 100 images (or Mel cepstral coefficients, if we talk about speech, or whatever you like) of dimension 196x14. In other words, the first 196 columns of each row of M will be made of the 196 columns of the first row of each of the 100 images (or Mel cepstral coefficients). Then  the next 295 columns of M (196 - 393) will be made of the 196 columns of the second row of the 100 images (or Mel cepstral coefficients), etc. I want my input to be 196x14 for , so my  add<Convolution> will be something like this:

model.Add<Convolution<>>(1,  // Number of input activation maps.
                                             14,  // Number of output activation maps.
                                                     3,  // Filter width.
                                                             3,  // Filter height.
                                                                     1,  // Stride along width.
                                                                             1,  // Stride along height.
                                                                                     0,  // Padding width.
                                                                                             0,  // Padding height.
                                                                                                     196, // Input width.
                                                                                                             14  // Input height.
                                                                                                                     );

By doing so, <convolution> will recreate the original 196x14 matrix for each image (or Mel cepstral coefficients) that will be used as input for the 14 filters of this example. 

I could not find this info in the current documentation, so I had to debug the function **naive_convolution.hpp** to see how the data were organized. I think this is something that would be helpful to include in the documentation.

### CODE REVIEW

**Comment by zoq** [comment]
@InterTriplete2010 Thanks for putting this together, I think this is really useful. Looking at the PR, it looks like it's based on mlpack-3.1.x? Can you open a new PR that is based on the latest master branch? Also it would be a good idea to use a feature branch, that will save you some trouble once the PR is merged.

The main workflow would look like:
- Fork https://github.com/mlpack/mlpack.
- Go to you fork https://github.com/InterTriplete2010/mlpack.git and clone that one.
- Make a feature branch `git checkout -b conv-doc`.
- Do all the changes in the branch.
- `git push --set-upstream origin conv-doc` (only needed for the first time) afterwards you can use `git push`
- Use GitHub to open a PR.

Hope that is helpful.

**Comment by zoq** [comment]
@InterTriplete2010 looks like the PR is based on the latest release and not the master branch, do you like to open a new PR?

**Comment by InterTriplete2010** [comment]
> @InterTriplete2010 looks like the PR is based on the latest release and not the master branch, do you like to open a new PR?

Sorry, this is still my first PR, so not sure how to get it right. Should I open a new PR following (again) the instructions that you gave me on Dec 8th?

**Comment by rcurtin** [comment]
@InterTriplete2010 if you'd be willing to do that it would be great!  Let us know if we can be helpful in that process.  If you make a branch in your fork with the changes here, you should be able to open a PR into the mlpack master branch.

**Comment by InterTriplete2010** [comment]
> @InterTriplete2010 if you'd be willing to do that it would be great! Let us know if we can be helpful in that process. If you make a branch in your fork with the changes here, you should be able to open a PR into the mlpack master branch.

@rcurtin Sure, I would be more than happy to do it. I know it sounds a dumb request (and I apologize for that), but would you mind telling me which steps I need to take to open a PR into the mlpack master branch with the changes been made so far?

**Comment by zoq** [comment]
> > @InterTriplete2010 if you'd be willing to do that it would be great! Let us know if we can be helpful in that process. If you make a branch in your fork with the changes here, you should be able to open a PR into the mlpack master branch.
> 
> @rcurtin Sure, I would be more than happy to do it. I know it sounds a dumb request (and I apologize for that), but would you mind telling me which steps I need to take to open a PR into the mlpack master branch with the changes been made so far?

You can find some tutorials online about how to open a PR - https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/ is one example.

Once you have your branch open you can just copy the modification into that branch.

**Comment by InterTriplete2010** [comment]
> > > @InterTriplete2010 if you'd be willing to do that it would be great! Let us know if we can be helpful in that process. If you make a branch in your fork with the changes here, you should be able to open a PR into the mlpack master branch.
> > 
> > 
> > @rcurtin Sure, I would be more than happy to do it. I know it sounds a dumb request (and I apologize for that), but would you mind telling me which steps I need to take to open a PR into the mlpack master branch with the changes been made so far?
> 
> You can find some tutorials online about how to open a PR - https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/ is one example.
> 
> Once you have your branch open you can just copy the modification into that branch.

Thank you for sending the link and again my apologies for my ignorance about opening PR correctly. I have just created a new PR following the instructions in the link you sent me and I hope it is have been correctly done into the master branch.

> > > @InterTriplete2010 if you'd be willing to do that it would be great! Let us know if we can be helpful in that process. If you make a branch in your fork with the changes here, you should be able to open a PR into the mlpack master branch.
> > 
> > 
> > @rcurtin Sure, I would be more than happy to do it. I know it sounds a dumb request (and I apologize for that), but would you mind telling me which steps I need to take to open a PR into the mlpack master branch with the changes been made so far?
> 
> You can find some tutorials online about how to open a PR - https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/ is one example.
> 
> Once you have your branch open you can just copy the modification into that branch.

Thank you for sending the link and again my apologies for my ignorance about opening PR correctly. I have just created a new PR following the instructions in the link you sent me and I hope it is have been correctly done into the master branch.

**Comment by zoq** [comment]
Thanks, closing in favour of https://github.com/mlpack/mlpack/pull/2829

**Pull request closed without merging**
