### PR TITLE
2818

### PR DESCRIPTION
**Pull request by onikolskyy**
The output of the error is still ugly: `RequireParamValue` will call e.g. `mlpack::bindings::python::PrintValue` (in python case) which outputs the whole matrix.

I would add a special case with arma::Mat as argument type for `PrintValue` or add a `PrintShape` function for the bindings so it can be reused in #2820. Should `mlpack::bindings::markdown` also be extended?

### CODE REVIEW

**Comment by birm** [comment]
Would you mind editing the title to be a bit more descriptive?

**Comment by NippunSharma** [comment]
Hey @onikolskyy thanks for opening this PR. As I mentioned in the issue description, I think that writing a function in `src/mlpack/core/util/param_check.hpp` and then calling that function from `_main.cpp` file might be a better idea as it will reduce code duplication across all bindings. So you will have to implement a function just like `RequireOnlyOnePassed` or `RequireParamValue` and then just call that single function from other bindings.

**Comment by rcurtin** [comment]
Agreed with @NippunSharma; in the best case, we can have a single generic utility that we can use to check the sizes of input matrices.  Then, adding all the checking to the different bindings would only entail adding a couple simple calls to the utility function at the top of each binding. :+1:

(Also, thanks @onikolskyy for giving this a shot! :rocket:)

**Comment by rcurtin** [comment]
Hey @onikolskyy, did you want to keep working on this one?

**Comment by onikolskyy** [comment]
Yes, I would like to, but only after the 13th of April.
If this is urgent or someone else is up to it, I'm happy to pass this over!

**Pull request closed without merging**
