### PR TITLE
package name upgrade python2 to python3

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
Name of packages upgraded in build.hpp from python2 to python3

### CODE REVIEW

**Comment by Aakash-kaushik** [comment]
This PR replaces #2612 .

**Review by birm — APPROVED** [review]
:snake: :snake: :snake:

**Review by rcurtin — APPROVED** [review]
Thanks @Aakash-kaushik! :+1:

**Comment by rcurtin** [comment]
(The build failures are unrelated, probably having to do with the mlpack.org downtime on Monday and Tuesday.)

**Pull request merged**
