### PR TITLE
Clean Coverage, no longer used

### PR DESCRIPTION
**Pull request by shrit**
Signed-off-by: Omar Shrit <omar@shrit.me>

### CODE REVIEW

**Comment by shrit** [comment]
Of course, I will remove the badge.
Also, do we need to keep the `appveyor` script? I can open another pull request for that one too

**Comment by zoq** [comment]
> Of course, I will remove the badge.
> Also, do we need to keep the `appveyor` script? I can open another pull request for that one too

We don't, don't mind to remove the script as part of the PR as well.

**Review by birm — APPROVED** [review]
Looks good to me, though I may have missed some conversation on removing versus fixing coverage builds.

**Review by rcurtin — COMMENTED** [review]
Awesome, thanks for taking the time to do this.  I see there's a reference to `BUILD_WITH_COVERAGE` in `doc/guide/build.hpp`---do you think you can remove that too?

@birm basically the coverage build has been failing for a very long time and doesn't have an "owner", so we thought it was reasonable to remove it.  (If anyone feels strongly and wants to bring it back, that's totally ok!  I just don't think anyone does. :))

**Review by rcurtin — APPROVED** [review]
Awesome, looks good to me. :+1:

**Pull request merged**
