### PR TITLE
Probable error in generator update of GANs.

### PR DESCRIPTION
**Pull request by walragatver**
This PR is for the gradient issue in  #1770.

### CODE REVIEW

**Comment by walragatver** [comment]
Hi @zoq, @ShikharJ,
Please let me know your thoughts regarding this.

**Comment by ShikharJ** [comment]
@walragatver I see your concern here. Let me dig into this today.

**Comment by zoq** [comment]
@ShikharJ let me know if I should take a closer look as well.

**Comment by ShikharJ** [comment]
@zoq Please do, it's good to have an extra set of eyes scouring through this.

**Comment by walragatver** [comment]
Hi I am testing this with the following code.
```
#include <mlpack/core.hpp>

#include <mlpack/methods/ann/init_rules/gaussian_init.hpp>
#include <mlpack/methods/ann/loss_functions/cross_entropy_error.hpp>
#include <mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error.hpp>
#include <mlpack/methods/ann/gan/gan.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/methods/softmax_regression/softmax_regression.hpp>

#include <boost/test/unit_test.hpp>
#include "mlpack/tests/test_tools.hpp"
#include "mlpack/tests/serialization.hpp"

using namespace mlpack;
using namespace mlpack::ann;
using namespace mlpack::math;
using namespace mlpack::regression;
using namespace std::placeholders;

int main() {
  size_t dNumKernels = 32;
  size_t discriminatorPreTrain = 6;
  size_t batchSize = 50;
  size_t noiseDim = 100;
  size_t generatorUpdateStep = 1;
  size_t numSamples = 50;
  double stepSize = 0.0003;
  double eps = 1e-8;
  size_t numEpoches = 251; 
  double tolerance = 1e-5;
  int datasetMaxCols = 70000;
  bool shuffle = true;
  double multiplier = 1;
  

  Log::Info << std::boolalpha
      << " batchSize = " << batchSize << std::endl
      << " generatorUpdateStep = " << generatorUpdateStep << std::endl
      << " noiseDim = " << noiseDim << std::endl
      << " numSamples = " << numSamples << std::endl
      << " stepSize = " << stepSize << std::endl
      << " numEpoches = " << numEpoches << std::endl
      << " tolerance = " << tolerance << std::endl
      << " shuffle = " << shuffle << std::endl;
 
  std :: cout << " batchSize = " << batchSize << std::endl
      << " generatorUpdateStep = " << generatorUpdateStep << std::endl
      << " noiseDim = " << noiseDim << std::endl
      << " numSamples = " << numSamples << std::endl
      << " stepSize = " << stepSize << std::endl
      << " numEpoches = " << numEpoches << std::endl
      << " tolerance = " << tolerance << std::endl
      << " shuffle = " << shuffle << std::endl
      << " multiplier = " << multiplier << std::endl
      << " discriminatorPreTrain" << discriminatorPreTrain << std::endl;

  arma::mat trainData;
  trainData.load("mnist_full.csv");
	  //Log::Info << arma::size(trainData) << std::endl;

  //trainData.
  //trainData.load("mnist_first250_training_4s_and_9s.arm");
  Log::Info << arma::size(trainData) << std::endl;

  std::cout << arma::size(trainData) << std::endl;
 
	size_t col = 0;
	for(size_t i = 0; i < 784; i++)
	{
		std :: cout << trainData(i, col) << " "; 
	}
	std :: cout << std :: endl;

	trainData = trainData - 127.5;
	trainData = trainData / 127.5;  

	for(size_t i = 0; i < 784; i++)
	{
		std :: cout << trainData(i, col) << " "; 
	}
	std :: cout << std :: endl;

  trainData = trainData.cols(0, datasetMaxCols - 1);

  //size_t numIterations = trainData.n_cols * numEpoches;
  //numIterations /= batchSize;

  size_t numIterations = 100300;
  std :: cout << numIterations << std::endl;

  Log::Info << "Dataset loaded (" << trainData.n_rows << ", "
            << trainData.n_cols << ")" << std::endl;

  std::cout<< "Dataset loaded (" << trainData.n_rows << ", "
            << trainData.n_cols << ")" << std::endl;

  Log::Info << trainData.n_rows << "--------" << trainData.n_cols << std::endl;

  // Create the Discriminator network
  FFN<SigmoidCrossEntropyError<> > discriminator;
  discriminator.Add<Convolution<> >(1, dNumKernels, 5, 5, 1, 1, 2, 2, 28, 28);
  discriminator.Add<ReLULayer<> >();
  discriminator.Add<MeanPooling<> >(2, 2, 2, 2);
  discriminator.Add<Convolution<> >(dNumKernels, 2 * dNumKernels, 5, 5, 1, 1,
      2, 2, 14, 14);
  discriminator.Add<ReLULayer<> >();
  discriminator.Add<MeanPooling<> >(2, 2, 2, 2);
  discriminator.Add<Linear<> >(7 * 7 * 2 * dNumKernels, 1024);
  discriminator.Add<ReLULayer<> >();
  discriminator.Add<Linear<> >(1024, 1);

  // Create the Generator network
  FFN<SigmoidCrossEntropyError<> > generator;
  generator.Add<Linear<> >(noiseDim, 3136);
  generator.Add<BatchNorm<> >(3136);
  generator.Add<ReLULayer<> >();
  generator.Add<Convolution<> >(1, noiseDim / 2, 3, 3, 2, 2, 1, 1, 56, 56);
  generator.Add<BatchNorm<> >(39200);
  generator.Add<ReLULayer<> >();
  generator.Add<BilinearInterpolation<> >(28, 28, 56, 56, noiseDim / 2);
  generator.Add<Convolution<> >(noiseDim / 2, noiseDim / 4, 3, 3, 2, 2, 1, 1,
      56, 56);
  generator.Add<BatchNorm<> >(19600);
  generator.Add<ReLULayer<> >();
  generator.Add<BilinearInterpolation<> >(28, 28, 56, 56, noiseDim / 4);
  generator.Add<Convolution<> >(noiseDim / 4, 1, 3, 3, 2, 2, 1, 1, 56, 56);
  generator.Add<TanHLayer<> >();

  // Create GAN.
  // Create GAN
  GaussianInitialization gaussian(0, 1);
  ens::Adam optimizer(stepSize, batchSize, 0.9, 0.999, eps, numIterations,
      tolerance, shuffle);
  std::function<double()> noiseFunction = [] () {
      return math::RandNormal(0, 1);};
  GAN<FFN<SigmoidCrossEntropyError<> >, GaussianInitialization,
      std::function<double()> > gan(trainData, generator, discriminator,
      gaussian, noiseFunction, noiseDim, batchSize, generatorUpdateStep,
      discriminatorPreTrain, multiplier);

  Log::Info << "Training..." << std::endl;
  double objVal = gan.Train(optimizer);

  // Test that objective value returned by GAN::Train() is finite.
  std :: cout << objVal << std :: endl;
  BOOST_REQUIRE_EQUAL(std::isfinite(objVal), true);

  // Generate samples.
  Log::Info << "Sampling..." << std::endl;
  arma::mat noise(noiseDim, batchSize);
  size_t dim = std::sqrt(trainData.n_rows);
  std::cout<< dim << std::endl;

  arma::mat generatedData(dim * dim, numSamples);
  std:: cout << generatedData.n_rows<< " " << generatedData.n_cols << std:: endl;

  for (size_t i = 0; i < numSamples / batchSize; i++)
  {
    arma::mat samples;
    noise.imbue( [&]() { return noiseFunction(); } );

    gan.Generator().Forward(noise, samples);
    //samples.reshape(dim, dim);
	std::cout<<samples.n_rows << " " << samples.n_cols << std :: endl; 
    //samples = samples.t();

    generatedData.submat(0, i * batchSize, dim * dim- 1, (i + 1) * batchSize - 1) = samples;

    /*samples = trainData.col(math::RandInt(0, trainData.n_cols));
    samples.reshape(dim, dim);
    samples = samples.t();

    generatedData.submat(dim,
        i * dim, 2 * dim - 1, i * dim + dim - 1) = samples;*/
  }

  std:: cout << generatedData.n_rows<< " " << generatedData.n_cols << std:: endl;
  //generatedData.t();
  generatedData = generatedData * (127.5);
  generatedData = generatedData + 127.5;
  generatedData = round(generatedData);
  
  for(size_t i = 0; i < 784; i++)
  {
	std :: cout << generatedData(i, col) << " "; 
  }
  std :: cout << std :: endl;
  
  std::string output_dataset = "output_mnist.csv";	
  Log::Info << "Saving output to " << output_dataset << "..." << std::endl;
  mlpack::data::Save(output_dataset, generatedData, false, true);
  Log::Info << "Output saved!" << std::endl;

  Log::Info << "Output generated!" << std::endl;
}
```


Here are the results before and after making changes. Note: This is not complete training but yes It trains for 2-3 days.
Figure_1

Figure_2

Based on this we can say that the results are good after making these changes.

**Comment by walragatver** [comment]
Hi @rcurtin, 
Thanks for looking in to the issue. Because it look like that one of the change I made got removed while rebasing or reverting.

At first, I will explain you about the change I made in the last commit which I pushed today.
Previously I made a change over [here](https://github.com/mlpack/mlpack/pull/1770/commits/b6eab0d2d973803f5f708e265ab67f71929ebd78) 

The bug is that the generator was not getting trained with the correct error.

We all know that in GANS, the Generator's do not have any responses to train i.e they are trained in an `unsupervised ` way.

Earlier we were calculating Gradient of Generator with the help of `FFN :: EvaluateWithGradient()` function called in FFN:: Gradient(). However, if we look at the code in `FFN:: EvaluateWithGradient()` the first step is (After forward pass)

```
outputLayer.Backward(
      std::move(boost::apply_visitor(outputParameterVisitor, network.back())),
      std::move(responses.cols(begin, begin + batchSize - 1)),
      std::move(error));
```

This calculates error with the help of responses . This is incorrect for `Generators` as we do not have any responses for them.

`We set responses of Generator with the help of set_size which by default set them to zeros. Thus with the earlier setting the Generator was only learning about making pixels to zero.`
   
`So in order to avoid this The FFN::BackWard() , FFN::ResetGradients() and FFN::Gradient(predictors)` should be called directly instead of `GAN::EvaluateWithGradient()` function in GANs.

**Comment by walragatver** [comment]
Now about the following change. 

```
    discriminator.outputLayer.Backward(
        std::move(boost::apply_visitor(outputParameterVisitor,
        discriminator.network.back())), std::move(discriminator.responses.cols(
        numFunctions, numFunctions + batchSize - 1)),
        std::move(discriminator.error));
    discriminator.Backward();
```

One important rule while training gan is that `When generator is trained discriminator parameters should'  **not**  ' be trained as they are trained for opposite work.`

Earlier when 
```
discriminator.Gradient(discriminator.parameter, numFunctions,
        noiseGradientDiscriminator, batchSize);
```

was executed `Discriminator parameters were also getting trained` because of `Gradient()` function.
So to prevent I am just calling `discriminator.Backward()` as it will only calculate deltas and will not update parameters of discriminator.

I am posting two comments as explanation is quite big. Thanks again for the approval :+1:

**Comment by rcurtin** [comment]
@walragatver thanks, I appreciate the explanation---it makes sense.  I hadn't realized that the existing call to `Gradient()` would incorrectly call the last layer's `Backward()` function. :+1:

**Comment by rcurtin** [comment]
@walragatver you'd said that you wanted to review this further, so I won't hit the merge button.  Whenever you're happy with it go ahead and merge (or ask us to review again, up to you). :+1:

**Comment by birm** [comment]
@walragatver is your thumbs up on rcurtin 's comment meant to show merge approval?

**Comment by walragatver** [comment]
Hi @birm,
There are some things needed to fix. I will merge it myself soon. Sorry for the delay. Slightly busy at this moment.

**Comment by himanshupathak21061998** [comment]
I am also waiting for this finish @walragatver.

**Comment by rcurtin** [comment]
@walragatver we can push this to later than 3.3.0 if you prefer, just feel free to update the milestone.  I'm aiming for end of this week to release 3.3.0 (which probably means it will be next week :smile:).

**Comment by rcurtin** [comment]
This code touches the ANN code, and there was recently a big refactoring of the ANN code in #2259, so be sure to merge the master branch into your branch here to make sure that nothing will fail if this PR is merged. :+1: (I'm pasting this message into all possibly relevant PRs.)

**Comment by walragatver** [comment]
I am closing this because #1888 is giving better results compared to this. I will merge it directly.

**Comment by saksham189** [comment]
> I am closing this because #1888 is giving better results compared to this.

Did you make the same fix in that PR?

**Comment by walragatver** [comment]
Nope basically the underlying code itself is getting changed. So I think
it's better to close it.
Let me know what you think. If you wish we can also merge this in.

**Comment by saksham189** [comment]
Yes maybe we should just merge in these changes first (because it seems like an important bug fix) and then we can merge the changes in the other PR later.

**Comment by walragatver** [comment]
Okay no problem.

**Pull request merged**
