### PR TITLE
Changes done to open all links in a new tab

### PR DESCRIPTION
**Pull request by mouli-16**
previously all links in README was opening on the same tab that made it difficult to toggle. I have made changes so that they open in a new tab

### CODE REVIEW

**Comment by rcurtin** [comment]
Hi @mouli-16, thanks for the PR!  But I think it would be more reasonable to just expect the user to ctrl+click (or use whatever their browser's functionality is to open a link in a new tab).

**Review by birm — APPROVED** [review]
Looks reasonable to me! Though I wouldn't be surprised if someone disagrees, and I don't feel strongly either way.

**Comment by rcurtin** [comment]
Personally, I'd actually vote against merging this one (happy to send stickers of course!), but I'm not sure if anyone else has an opinion.

**Review by zoq — COMMENTED** [review]
I agree with @rcurtin I can open a new tab using `ctrl` but I can't use it to do it the other way around.

**Comment by jeffin143** [comment]
True, I agree ctrl + click is a universal shortcut across popular browsers , So that wouldn't be much of an issues. So i agree too with @zoq and @rcurtin

**Comment by jeffin143** [comment]
Let's close this in favour of the majority number of no 

We will re open if someone has a strong opinion

Thanks for the contribution , although we weren't able to merge it.

**Pull request closed without merging**
