### PR TITLE
Adapting non invert-able activation layers

### PR DESCRIPTION
**Pull request by IWNMWE**
This pull request is created to adapt the non invert able layers as mentioned in #3506 
- [x]  Elish function
- [x] Gaussian function
- [x]  Gelu function
- [x]  Hard Swish

The above will be the ones that I will adapt in the near future and also may add other layers going forward

Also added tests for the ELU layer ad may add tests for other layers

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Thanks for looking into this, is this ready for a review?

**Comment by IWNMWE** [comment]
> Thanks for looking into this, is this ready for a review?

Hey sorry for the delays. Due to my exams and projects I will take one more week to finish this up

**Comment by IWNMWE** [comment]
Hey @zoq for the gaussian function I have adapted the layers but kept the original function object(removed from base layer as well) so that there are no issues with the radial basis function .I think keeping these function objects for famous functions could be really helpful for the user. Please let me know if this is fine or if I should remove the function class as Well and change the rbf to have gaussian layer initialised for the forward method

**Comment by IWNMWE** [comment]
hey in light of the pull request #3547 i would be closing this pull request as there have been changes made in the activation functions that deal with the issue

**Pull request closed without merging**
