### PR TITLE
Loss_function_test from boost to catch2

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
Issue #2523

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Looks good to me, let's see if the build comes back green.

**Review by kartikdutt18 — APPROVED** [review]
Hey @Aakash-kaushik,
Thanks a lot for working on this. This looks good to me.

**Review by zoq — APPROVED** [review]
Looks good, thanks for putting this together.

**Comment by kartikdutt18** [comment]
Thanks again @Aakash-kaushik for the contribution.

**Comment by Aakash-kaushik** [comment]
Happy to contribute.

**Pull request merged**
