### PR TITLE
Removed trailing underscores in header guards. Resolved issue #533

### PR DESCRIPTION
**Pull request by Falit**
Deletion of (leading)underscores in macros header guards as they being [deprecated now](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29)
#533

### CODE REVIEW

**Comment by rcurtin** [comment]
Hi, I can't accept this because it doesn't compile.  Please test this on your system before filing a PR.

**Comment by elfring** [comment]
How do you think about the wording "Deletion of leading …" (instead of "… trailing …")?
Would you like to explain the suggested changes a bit more in your commit messages?

**Comment by rcurtin** [comment]
I agree, the commit message is a bit misleading.  Please consider changing that to what was actually done instead---accuracy in commit messages is really important for later maintenance.

Also, can you please test one thing:

 * compile mlpack with your proposed changes, then run `mlpack_allknn --version`.  The output should be something like `bin/mlpack_allknn: part of mlpack git-48bfcac`.

Lastly, and I forgot about this when I commented on this ticket earlier, there is a bit of complexity involved with changing `__MLPACK_VERSION_MAJOR`, `__MLPACK_VERSION_MINOR`, and `__MLPACK_VERSION_PATCH`, since those may be used by downstream projects.  In accordance with the versioning principles (https://github.com/mlpack/mlpack/blob/master/UPDATING.txt) we should not rename those macros until version 3.0.0.  I think a better idea is to provide both `__MLPACK_VERSION_*` and `MLPACK_VERSION_*`, but note that the macros with the underscores are deprecated and will be removed in future versions (HISTORY.txt should be updated to reflect this change).  Do you think you could change your patch to handle this?

Thanks! :+1:

**Comment by elfring** [comment]
* How much do the version identification macros belong to your application programming interface?
* Is there any more planing of software releases evolving?
* Would you like to collect corresponding changes on a topic branch?

**Comment by Falit** [comment]
@rcurtin  .. I apologize for my unclear commit message .. I would change to make it more understandable.

I compiled my changes and ran `mlpack_allknn --version` and got the following output : 
`mlpack_allkfn: part of mlpack 2.0.x

**Comment by Falit** [comment]
@rcurtin  .. Regarding the changing of versions and to provide both `__MLPACK_VERSION_*`  and `MLPACK_VERSION_*` , as I understand from the versioning principles (https://github.com/mlpack/mlpack/blob/master/UPDATING.txt)

**Comment by rcurtin** [comment]
@elfring:

I'm not sure what you mean.  The versioning macros can be used by downstream, so they are part of the "public API".

@falit:
> I compiled my changes and ran mlpack_allknn --version and got the following output :
> ```mlpack_allkfn: part of mlpack 2.0.x```

This isn't the correct output; your modifications have caused this to be wrong.  You should compare with an unmodified version of mlpack.

And yes, we will need both version of the versioning macros (with and without underscores), probably accompanied by a note that says the underscored macros will be removed in mlpack 3.0.0.

**Comment by Falit** [comment]
@rcurtin 
I ran mlpack_allknn --version with the original version of the mlpack, it gave the following output
`mlpack_allkfn: part of mlpack 2.0.1`.. Could you  guide me where to look now .

Regarding both version.. i think we should have another branch having without underscored macros

**Comment by rcurtin** [comment]
No, I meant that you should check with an unmodified git master branch version, which will give also different output.  Please make sure that the output of your modified branch is the same as the current git master.  If it's different, take a look in `version.cpp` to figure out what is going on.

I don't understand what having a second branch without underscored macros will achieve...

**Comment by elfring** [comment]
How do you think about to split the clean-up for the affected identifiers like the following?
* Include guards
* Versioning macros
* Remaining update candidates?


How much are you used to [work with topic branches](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows#Topic-Branches "Branching workflows")?

**Comment by rcurtin** [comment]
@falit: are you planning to finish this?

Splitting the clean-up like @elfring suggested would be just fine (and topic branches are a good way to do this).  In this case we only have two things: the header guards, and the versioning macros.  @falit, if you want to redo this PR as changing just the include guards, we can take care of the versioning macros another time.

**Comment by rcurtin** [comment]
Okay, I just went ahead and made the necessary changes in e0e9d04 and merged this in. @falit, if you want, you can add your name to the list of contributors in `src/mlpack/core.hpp` and `COPYRIGHT.txt` and open another PR and I'll merge it in.

**Pull request merged**
