### PR TITLE
Updated contributor's list

### PR DESCRIPTION
**Pull request by Hsankesara**
Hey @rcurtin,  I added my name in the contributor's list in this PR. Thanks for the suggestion in #1809.

### CODE REVIEW

**Comment by jeffin143** [comment]
> Just checking mlpack-bot :)

Ohh , I didn't see , I am under different team , so I couldn't check . 

PS : ignore :)

**Comment by jeffin143** [comment]
> Hey @rcurtin, I added my name in the contributor's list in this PR. Thanks for the suggestion in #1809.

@Hsankesara , I noticed , that my name is not there probably I might have missed it.  Could you add mine too in same ?

Jeffin Sam , sam.jeffin@gmail.com

**Comment by Hsankesara** [comment]
> > Hey @rcurtin, I added my name in the contributor's list in this PR. Thanks for the suggestion in #1809.
> 
> @Hsankesara , I noticed , that my name is not there in contributors list probably I might have missed it. Could you add mine too in same ?
> 
> Jeffin Sam , [sam.jeffin@gmail.com](mailto:sam.jeffin@gmail.com)

No issues @jeffin143, I'll add your name also.

**Comment by Hsankesara** [comment]
Thanks, @ShikharJ for merging it.

**Pull request merged**
