### PR TITLE
use constexpr to replace static const

### PR DESCRIPTION
**Pull request by stereomatchingkiss**
As the title said

### CODE REVIEW

**Comment by rcurtin** [comment]
Looks good to me.

**Comment by zoq** [comment]
I'm not sure I get the intention to prefer constexpr in this case. There is no expression that can be evaluated during compilation using one of the parameter. Also, removing static isn't a good idea, since once the program is compiled, constexpr is no longer relevant and I would prefer to initialize the variable once.

**Comment by rcurtin** [comment]
Ack, maybe I pulled too early, sorry about that; feel free to revert.  I think I misunderstood constexpr a little bit.

**Comment by stereomatchingkiss** [comment]
I prefer constexpr because I hope the variables can be initialize at compile time, as [this post](http://stackoverflow.com/questions/13346879/const-vs-constexpr-on-variables) stated, but I may wrong, the compilar may not do what I think it should.

ps : on vc2015, static const double and constexpr, both of them can evaluate at compile time

**Comment by zoq** [comment]
I think, it would be reasonable to use constexpr if the initialization is time-consuming at runtime or if we could evaluate an expression at compile time. But that's not the case here, anyway I think what we could do here is to use ```static constexpr``` as we do it with ```log2pi``` in ```gaussian_distribution.hpp```.

```
static const constexpr double log2pi = 1.83787706640934533908193770912475883;
```

I'm almost sure the first const is obsolete, I'll need to check that.

**Comment by stereomatchingkiss** [comment]
>I'm almost sure the first const is obsolete, I'll need to check that.

Don't worry, const could be removed, unlike constexpr function, constexpr variable must be able to evaluate at compile time(as I remember).

example : 

    constexpr double log2pi = 3.14159;
    log2pi = 3.14; //compile time error

I will add the static back to the variable, this should make sure the variable can be evaluated at compile time and would not recreate every time.

**Comment by stereomatchingkiss** [comment]
>I think, it would be reasonable to use constexpr if the initialization is time-consuming at runtime or if we could evaluate an expression at compile time. But that's not the case here

I have different opinion about this one, I think it is reasonable to change it from const to constexpr because

1 : It may(not will) help the compiler generate better binary, smaller and faster
2 : It is not premature optimization, because changing from const to constexpr do not seem like adding any burden on the programmers

These are what I think about, just take it as reference.

**Comment by zoq** [comment]
Sorry to sound so picky. You are absolutely right, there is no particular penalty for using constexpr in this case.

**Pull request merged**
