### PR TITLE
Random forest test stability fixes

### PR DESCRIPTION
**Pull request by rcurtin**
Just some quick fixes that I put together based on looking at the recent Jenkins nightly build failures.  I found a logical error in one test and increased the number of trials for another.

### CODE REVIEW

**Comment by walragatver** [comment]
@rcurtin, I have also seen.  /mlpack/src/mlpack/tests/main_tests/radical_test.cpp failing some times.

**Comment by rcurtin** [comment]
@walragatver I have seen it too, but I can't reproduce it.  If you can reproduce it, do you want to try to debug it?

**Comment by walragatver** [comment]
@rcurtin, I tried producing locally, but I failed to do so. However, my Dual Optimizer PR #1888  is failing on it. I will try reproduce it and if possible debug it.

**Comment by rcurtin** [comment]
> @rcurtin, I tried producing locally, but I failed to do so. However, my Dual Optimizer PR #1888 is failing on it. I will try reproduce it and if possible debug it.

Sounds good; if I can help out, just let me know. :)

**Pull request merged**
