### PR TITLE
Change Serialize() to serialize()

### PR DESCRIPTION
**Pull request by rcurtin**
This PR changes all instances of `Serialize()` to `serialize()` and removes the serialization shim.  It fixes issue #1120.  A lot of the work is from @kaushik-rohit; thank you!  If you like I will add your name to the list of contributors in `src/mlpack/core.hpp` and `COPYRIGHT.txt`.

In many cases this allows us to significantly simplify serialization code; for instance, std::vector can now be serialized directly instead of iterating over each element.

### CODE REVIEW

**Comment by rcurtin** [comment]
Ok, I am done working on this one.  I'll leave it open for a week before merge.

@kaushik-rohit: let me know if you have any comments on the code.  Also I would be happy to add your name and email to the list of contributors; alternately you can open a PR for that and I'll merge it.  In addition, Marcus and I had this idea that we should mail new contributors mlpack stickers.  Do you want one?  (http://ratml.org/misc_img/mlpack_stickers.jpg)  If so send me an email to ryan@ratml.org with shipping information and I can try to figure out how to mail internationally. :)

**Comment by kaushik-rohit** [comment]
@rcurtin The code seems good to me. I will open a PR for adding my name to list of contributors. Thank you :)

**Comment by rcurtin** [comment]
Sounds good, thanks so much for the help with this. :)

**Comment by rcurtin** [comment]
Sorry for the delay on this one, I got sick and wasn't in a condition to click the 'merge' button. :)

**Pull request merged**
