### PR TITLE
Fix ownership of kernels for FastMKS

### PR DESCRIPTION
**Pull request by rcurtin**
This bug arises when using FastMKS with a kernel that has state (like the polynomial kernel, which holds a degree and an offset).  If the FastMKS model is saved, and then used to compute maximum kernels for new points, the resulting kernel values are all 1:

```
$ bin/mlpack_fastmks -r test_data_3_1000.csv -K "polynomial" --degree 2 --offset 3 -M model.bin
$ bin/mlpack_fastmks -q test_data_3_1000.csv -m model.bin -k 5 -p p.csv -i i.csv
$ head p.csv
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00,1.00000000000000e+00
```

The reason for this is that the kernel is not being properly serialized.  Specifically, in `fastmks_main.cpp`, the model is built like this:

```
    ...
    else if (kernelType == "polynomial")
    {
      PolynomialKernel pk(degree, offset);
      model->KernelType() = FastMKSModel::POLYNOMIAL_KERNEL;
      model->BuildModel(std::move(referenceData), pk, single, naive, base);
    }
    ...
```

But this means that `pk` goes out of scope right after `BuildModel()`; so when `model->Search()` is called later, the kernel that the model was built on now points to invalid memory.

This is fixed in this PR by ensuring that kernels are copied by the `IPMetric` copy constructor, and also ensuring that metrics are copied when the `CoverTree` is constructed.

### CODE REVIEW

**Comment by zoq** [comment]
I guess we should look into: http://ci.mlpack.org/job/pull-requests%20mlpack%20memory/5099/valgrindResult/pid=1312818/

**Comment by rcurtin** [comment]
Ahh, looks like I broke something instead of making it better. :)  I'll look into it tomorrow.

**Comment by rcurtin** [comment]
I ran the entire `mlpack_test` with `valgrind` (which took a while!) but didn't find any issues having anything to do with the `FastMKS` tests.  So I'm not quite sure how to debug this.  Let's see if the memory issues happen again...

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
I merged in the changes from #2470 so that hopefully I can reproduce the memory issues.  I am still trying to reproduce the issue...

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@zoq I've tried everything I know how to try with this one but I can't reproduce the error.  I tried to build and produce the issue locally; I tried by running all tests in `mlpack_test`; I tried running on polar after building in my home directory; I tried running the executable as built by Jenkins directly; none of these things managed to reproduce the error.  So, I'm kind of at a loss as to what to do.  What do you think?

**Comment by zoq** [comment]
Sorry missed the update on this one, looks like I can't see the log anymore, what about we run the memory test one last time on master? We can temporary let master handle the memory job and trigger the build one more time?

**Comment by rcurtin** [comment]
Sure, let's try that---let me set it up then fire it off...

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Maybe a good idea, to post the IRC messages here, for future reference.

**Comment by rcurtin** [comment]
:+1: agreed.  Here's the transcript:

```
18:32 < rcurtin> zoq: I had a breakthrough for the FastMKS test memory issue!
18:32 < rcurtin> I noticed this in the logs:
18:32 < rcurtin> /home/jenkins-mlpack/workspace/pull-requests mlpack memory@2/src/mlpack/tests/main_tests/fastmks_test.cpp(510): fatal error: in
                 "FastMKSMainTest/FastMKSOffsetTest": Cannot load test dataset data_3d_ind.txt!
18:32 < rcurtin> so I ran locally and was able to reproduce it... tons of memory errors
18:33 < rcurtin> then I moved data_3d_ind.txt to the working directory... no memory errors
18:33 < rcurtin> so I think this really just boils down to the datasets not being in the right place for the memcheck job
18:34 < rcurtin> however, I noticed that even with these test failures, they actually aren't reported in the job... so I'll look into setting up the memcheck job to
                 also report failed tests
18:54 < zoq> rcurtin: Ohh, that makes sense, not sure why we missed the message.
18:55 < zoq> rcurtin: I think I configured the memory check, sorry for the trouble.
18:55 < rcurtin> well part of it is that the logs of the memory check are... in the GBs :-D
18:56 < rcurtin> no worries, just happy to have it figured out (I think) :)
18:56 < rcurtin> I know that if I encounter the issue, someone else will too
18:56 < zoq> yes
18:56 < rcurtin> maybe it is a variant of Murphy's Law but it seems like every possible un-debugged weird issue will come back and have to be debugged... so there is
                 no hiding from it :)
18:57 < zoq> haha, yes you are probably right
18:57 < rcurtin> I'm just elated to have actually figured it out
18:57 < rcurtin> I was getting really unhappy... "how could there be a problem I can't solve?  why can't I figure it out?"
18:57 < rcurtin> but really I just got lucky while watching the build go
18:58 < rcurtin> in any case I have learned a new trick for debugging, so, hopefully it will help in the future regardless :)
18:58 < zoq> what is the new trick - watching the build log? :)
18:59 < rcurtin> yeah, basically, the thing that I didn't think of was "are the tests passing?"---I had just assumed that they were, and that's how I overlooked the
                 problem
18:59 < rcurtin> that's also why I couldn't reproduce it---every time I tried, I was running from the "correct" working directory with the test data available
19:00 < rcurtin> but the issue can only be reproduced when running from a "wrong" working directory :)
19:03 < zoq> Great that you figured it out, so much time 'lost' on this.
19:04 < rcurtin> the time would have only been "lost" if I hadn't learned something in the end :)
```

So, I think that I can fix the memory checks before we merge this.  So we can wait until all the builds succeed.  (I will be debugging/updating the job behind the scenes; but since it takes so long to build, it might be a little while until everything is passing.)

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
Success! :trophy: I'll go ahead and merge this---the memory checks now appear to be working fine.

**Pull request merged**
