### PR TITLE
latex formula output is pixelated

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/mlpack/mlpack/issues/313

### CODE REVIEW

**Comment by rcurtin** [comment]
Can you provide a screenshot or something to show that this fixes the issue?  Thanks!

**Comment by theaverageguy** [comment]
Errr.. can you tell me why the build is failing?

**Comment by rcurtin** [comment]
It was just unlucky. :) Some mlpack tests are probabilistic so there is some very small chance of failure. Often the tolerances of these tests need to be loosened or tuned though and that is what has happened here.

**Comment by rcurtin** [comment]
Closing for inactivity.  If you can provide a screenshot to show that this fixes the issue, I'll merge it.

**Pull request closed without merging**
