### PR TITLE
Rework how output with `Log` is enabled and disabled

### PR DESCRIPTION
**Pull request by rcurtin**
Since we transitioned to a header-only library, there is no longer one `libmlpack.so` that holds a single `Log::Info`, `Log::Warn`, and `Log::Fatal` object.  Instead, each translation unit will get its own.  This means that, like ensmallen, we need to have users control whether output is enabled through header macros, instead of by changing the `.ignoreInput` value.

So, this PR adds support for the following macros:

 - `MLPACK_PRINT_DEBUG`
 - `MLPACK_PRINT_INFO`
 - `MLPACK_PRINT_WARN`
 - `MLPACK_SUPPRESS_FATAL` (this one is only used by the tests, if `TEST_VERBOSE` is off in the CMake configuration)

The changes also mean that all of the manual setting of `Log::Fatal.ignoreInput` in the tests is no longer necessary, and so that has been removed (that's probably the majority of the diff).

### CODE REVIEW

**Comment by conradsnicta** [comment]
@rcurtin As a point of comparison and discussion, I made a related change to Armadillo not that long ago.  The solution is somewhat different to what is proposed here.

Armadillo used to by default print messages (warnings and errors) about failed decompositions, failed solvers, failed loading, possibly bad input data (eg, non-symmetric matrices), etc.  These type of messages can be quite annoying when they're not wanted.  Armadillo had a blunt way to disable all errors and warnings, by defining `ARMA_DONT_PRINT_ERRORS`.  However, warnings about poorly conditioned systems and bad data can be useful in many contexts (while ignoring other errors), so the blunt approach was not the best.

To address this, Armadillo now has (since version 10.4) a more fine-grained control of the printed messages, via the`ARMA_WARN_LEVEL` define.  The default setting for this is a trade-off.  Extract from [docs.html](http://arma.sourceforge.net/docs.html#config_hpp): 
```
ARMA_WARN_LEVEL
The level of warning messages printed to ARMA_CERR_STREAM.
Must be an integer ≥ 0. By default defined to 2.
0 = no warnings; generally not recommended
1 = only critical warnings about arguments and/or data which are likely to lead to incorrect results
2 = as per level 1, and warnings about poorly conditioned systems (low rcond) detected by solve(), spsolve(), etc
3 = as per level 2, and warnings about failed decompositions, failed saving / loading, etc

Example usage:
#define ARMA_WARN_LEVEL 1
#include <armadillo>
````

On the one hand, having only one `#define` instead of four (`MLPACK_PRINT_DEBUG`, `MLPACK_PRINT_INFO`, `MLPACK_PRINT_WARN`, `MLPACK_SUPPRESS_FATAL`) may simplify internal code, enforce consistency, and be possibly easier to employ by mlpack users.  On the other hand, it can be argued that having four defines with unique names may be preferable as it's easier to figure out what they do, instead of using a semi-opaque warning level number.

**Review by conradsnicta — APPROVED** [review]

**Comment by shrit** [comment]
To be honest, If you ask me what do you think about our logging system, I would say that I am not too fan of wrappers that we do around the standard output because I fail to see the reason behind it.

For example, I used `spdlog` in MagicFlock which is a header-only logging library. The reason for this choice is that I needed to have a full logging system that is creating a copy of what goes to the standard output and registers it in rotating files with a specific size for each file. Also, another feature is having time stamps and being able to change their format easily. A logging system should be simple to use and be able to provide complex features such as collecting datasets. 

I know that this is not the case for mlpack and a small wrapper is nice to have. But currently, we are making things more complex if we need to add more debugging levels.

Here is what I think:

* I like the idea from @conradsnicta to use numbering and one define.
* Two debugging levels are more than enough, INFO and FATAL, I do not see the reason for WARNING because the output message would tell that this is a warning. Also, DEBUG can be useful in some cases but it is not essential.
* Build the wrapper around `printf` instead of `std::cout` because the latter is a huge header that slows our life. There is a contradiction in our design while we are focusing on speed by using metaprog and we are using `stdcout` for output. This does not make too much sense.
* The last point is hard to achieve because armadillo is including `iostream` and it is using it for debugging as well.

I think that our logging system needs a complete revamp, maybe we can leave it to mlpack 5, while during this time maybe there will be a way to disable `iostream` from armadillo

**Review by shrit — APPROVED** [review]
LGTM

**Comment by conradsnicta** [comment]
Suggest we merge this as is, in the interests of getting mlpack 4 released.

Further changes would probably need a longer discussion.  The proposed solution with `MLPACK_PRINT_INFO` etc macros is workable and sufficient.

**Comment by rcurtin** [comment]
I'm definitely open to other solutions.  `spdlog` looks cool, but it's worth pointing out that mlpack doesn't generally print anywhere near the kinds of log messages that, e.g., a game might---so fast logging at runtime is probably not totally necessary.  However, if there are compilation-time improvements to be had, that might be interesting.

I agree with @conradsnicta though that this is fine for an mlpack 4 release, and then we can revisit it later.

To me, I don't have much particular interest in the logging system, so I probably won't end up pursuing too many further changes to it and will devote my time elsewhere, but if someone else wants to take up the cause that is great. :)

**Pull request merged**
